### DISCUSSION TITLE
Installation error with permissions “The HTTP server must have write permission”

### DISCUSSION THREAD

**Discussion by p-jones** [FreshRSS/FreshRSS#5037] [Q&A] [answered]
I am attempting to install FreshRSS on an up-to-date Ubuntu server.

I spin up the container with no problems using a docker compose stack in Portainer (never mind the following indenting - it is correct in the Portainer stack).

```yaml
version: '3.3'
services:
    linuxserver:
        container_name: freshrss
        ports:
            - '9009:80'
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Americas/Toronto
        volumes:
            - '/home/myusername/docker/freshrss:/config'
        restart: always
        image: ghcr.io/linuxserver/freshrss
```

Step 2 of install, all is green except for 

![Installation · FreshRSS step 2](https://user-images.githubusercontent.com/117534773/213872816-23d41942-a678-4146-8514-02c5afab70e1.png)

Any help would be much appreciated!
