### DISCUSSION TITLE
When using MySQL with FreshRSS, the items may not be sorted by time properly.

### DISCUSSION THREAD

**Discussion by jerryc127** [FreshRSS/FreshRSS#5447] [Q&A]
I have created a MySQL database and installed FreshRSS using Docker Compose.

```
version: "3"
services:
  freshrss:
    image: freshrss/freshrss:edge-arm
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    ports:
      - 8080:80
    logging:
      options:
        max-size: 10m
    volumes:
      - ./data:/var/www/FreshRSS/data
      - ./extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: Asia/Hong_Kong
      CRON_MIN: '*/10'

volumes:
  data:
  extensions:
```

During the initialization process, I selected MySQL as the database, and the connection to the database is working correctly. 
However, I have noticed an issue with the sorting order. 
Currently, the items are sorted based on groups, and within each group, the sorting is done by time. 
However, I expected all the RSS feeds to be sorted by time instead of being grouped.

![image](https://github.com/FreshRSS/FreshRSS/assets/16351105/25109b58-f8b1-49db-add7-62ecc2307547)
