### DISCUSSION TITLE
docker-compose.yml for Container Manager on a Synology NAS

### DISCUSSION THREAD

**Discussion by fabiosirna** [FreshRSS/FreshRSS#5459] [Q&A] [answered]
**Describe the bug**

I've built FreshRSS using docker and there is an error in this file:
https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose.yml
```
      dockerfile: Docker/Dockerfile-Alpine
```
should be:
```
      dockerfile: ./Docker/Dockerfile-Alpine
```
It would be nice to have also to put:

```
  freshrss:
    ports:
      - "${PUBLISHED_PORT:-8080}:${LISTEN:-80}"
```
In the same file (maybe as a comment), so that we have all the informations in one file.

**Comment by Alkarex** [comment]
Hello,
Please show the command you are trying to run and the error you get, as well as the platform and versions you are using.

Works fine for me as it is:

```console
alex@UBUNTU:~/GitHub/FreshRSS/Docker/freshrss$ docker-compose -f docker-compose.yml -f docker-compose-local.yml up -d --remove-orphans
Creating freshrss ... done
```

Regarding the ports, see https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#docker-compose
And https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose-local.yml
Having ports open by default is not good. See suggestions for deployment in production https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#run-in-production

**Comment by fabiosirna** [comment]
Hi @Alkarex,
I'm using the docker compose.yml provided in the source and launch it from the Container Manager on a Synology NAS.
I pulled the git from FreshRSS repository. 
Then edited the compose.yml adding the relative path `./` in front of `dockerfile: Docker/Dockerfile-Alpine` and also the port section. 
I configured the `.env` and now it works very well!

I was suggesting also to added the port section in main compose.yml - maybe commented - because probably this is the most common configuration.

```
version: "2.4"

volumes:
  data:
  extensions:

services:

  freshrss:
    image: freshrss/freshrss:latest
    # Optional build section if you want to build the image locally:
    build:
      # Pick #latest (stable release) or #edge (rolling release) or a specific release like #1.21.0
      context: https://github.com/FreshRSS/FreshRSS.git#latest
      dockerfile: ./Docker/Dockerfile-Alpine
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - data:/var/www/FreshRSS/data
      - extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: Europe/Paris
      CRON_MIN: '3,33'
    ports:
      - "${PUBLISHED_PORT:-8080}:${LISTEN:-80}"
```

This is the `.env`:

```
# Example of environment file for docker-compose
# Copy this file into your own `.env` file

# ================================
# FreshRSS
# ================================

ADMIN_EMAIL=<redacted>

# Published port for development or local use (optional)
PUBLISHED_PORT=<port>

# =========================================
# For automatic FreshRSS install (optional)
# =========================================

ADMIN_PASSWORD=<redacted>
ADMIN_API_PASSWORD=<redacted>

# Address at which the FreshRSS instance will be reachable:
BASE_URL=https://192.168.10.1:<port>

# Database server (not relevant if using default SQLite)
# Use the name of the Docker container if running on the same machine
DB_HOST=freshrss-db

# ===========================================================
# Database credentials (not relevant if using default SQLite)
# ===========================================================

# Database to use
DB_BASE=freshrss

# User in the freshrss database
DB_USER=freshrss

# Password for the defined user
DB_PASSWORD=freshrss
```

**Comment by Alkarex** [comment, marked as answer]
I had a quick look at a demo of the Synology Container Manager.
It looks like it only supports a single docker-compose file and accessing a service via a Docker network does not seem possible.
In the demo, the local build failed for me due to missing git, but you can just remove the whole optional build section:

```yml
version: "2.4"

volumes:
  data:
  extensions:

services:

  freshrss:
    image: freshrss/freshrss:edge
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - data:/var/www/FreshRSS/data
      - extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: Europe/Paris
      CRON_MIN: '3,33'
    ports:
      - "${PUBLISHED_PORT:-8080}:${LISTEN:-80}"
```
