### DISCUSSION TITLE
Cannot access database

### DISCUSSION THREAD

**Discussion by Stainless5792** [FreshRSS/FreshRSS#5564] [Q&A] [answered]
**Describe the bug**
Have used the Freshrss for months in docker, however today I can not open the website and got error in the log as below:

```
FreshRSS seems to be already installed!
Please use `./cli/reconfigure.php` instead.
ℹ️ FreshRSS already installed; no change performed.
FreshRSS warning: username already exists “admin”
ℹ️ FreshRSS user already exists; no change performed.
[Thu Aug 03 16:38:50.038973 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.54 (Debian) configured -- resuming normal operations
[Thu Aug 03 16:38:50.039020 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

FreshRSS[102]: [_] [Thu, 03 Aug 2023 16:40:01 +0800] [notice] --- FreshRSS starting feeds actualization at 2023-08-03T16:40:01+08:00
FreshRSS[102]: [_] [Thu, 03 Aug 2023 16:40:01 +0800] [notice] --- FreshRSS actualize admin…
^@^@FreshRSS[102]: [admin] [Thu, 03 Aug 2023 16:42:41 +0800] [error] --- Access to database is denied for `postgres`: SQLSTATE[08006] [7] timeout expired
^@^@^@^@^@^@^@^@FreshRSS[107]: [_] [Thu, 03 Aug 2023 16:50:01 +0800] [notice] --- FreshRSS starting feeds actualization at 2023-08-03T16:50:01+08:00
FreshRSS[107]: [_] [Thu, 03 Aug 2023 16:50:01 +0800] [notice] --- FreshRSS actualize admin…
^@^@FreshRSS[107]: [admin] [Thu, 03 Aug 2023 16:52:41 +0800] [error] --- Access to database is denied for `postgres`: SQLSTATE[08006] [7] timeout expired
^@^@^@^@^@^C
```

**Expected behavior**
Work as before.

**Screenshots**

<img width="1439" alt="image" src="https://github.com/FreshRSS/FreshRSS/assets/5257915/f1668435-421c-4272-8b5e-37bcb4a0d36d">

**Environment information (please complete the following information):**
- FreshRSS version: [1.21.0]
- Database version: [PG 13.10]
- Installation type: [Docker]

**Additional context**
1. The DB is in good shape, and can be accessed as normal.
2. Docker compose as below :

```
version: "2.4"

volumes:
  data:
  extensions:

services:
  freshrss:
    image: freshrss/freshrss:1.21.0
    container_name: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - data:/var/www/FreshRSS/data
      # Optional volume for storing third-party extensions
      - extensions:/var/www/FreshRSS/extensions
      # Optional file providing custom global settings (used before a FreshRSS install)
      # - ./config.custom.php:/var/www/FreshRSS/data/config.custom.php
      # Optional file providing custom user settings (used before a new user is created)
      # - ./config-user.custom.php:/var/www/FreshRSS/data/config-user.custom.php
    ports:
      # If you want to open a port 8080 on the local machine:
      - "8020:80"
    environment:
      TZ: Asia/Shanghai
      CRON_MIN: '2,32'
      FRESHRSS_ENV: development
      # Optional advanced parameter controlling the internal Apache listening port
      LISTEN: 0.0.0.0:80
      # Optional auto-install parameters (the Web interface install is recommended instead):
      # ⚠️ Parameters below are only used at the very first run (so far).
      # So if changes are made (or in .env file), first delete the service and volumes.
      # ℹ️ All the --db-* parameters can be omitted if using built-in SQLite database.
      FRESHRSS_INSTALL: |-
        --api_enabled
        --base_url https://freshrss.xx.xx
        --db-base freshrss
        --db-host xxx.xxx.xxx.xxx
        --db-password xx
        --db-type pgsql
        --db-user xx
        --default_user admin
        --language en
      FRESHRSS_USER: |-
        --api_password xx
        --email xx@outlook.com
        --language en
        --password xx
        --user admin
```
