### DISCUSSION TITLE
Struggling with OIDC (Authelia & Traefik)

### DISCUSSION THREAD

**Discussion by arcoast** [FreshRSS/FreshRSS#5684] [Q&A] [answered]
Hi,

Wondering if anyone can help me?

I'm installing FreshRSS with docker and a mariadb database, can get it working beautifully with web based auth (which I used to test FreshRSS itself) behind traefik, but I'm very keen on adding OIDC which I already have implemented with Authelia and successfully working with other applications (gitea, immich, nextcloud, podfetch, synapse)

FreshRSS is being served on `https://freshrss.domain.com`
Authelia is being served on `https://login.domain.com`

My docker-compose.yml
```yaml
networks:
    freshrss:
        external: false
        name: freshrss
        
services:
    freshrss:
        image: freshrss/freshrss:edge
        container_name: freshrss
        networks:
            - freshrss
            - traefik
        ports:
            - 8003:80
        environment:
            - TZ=${TZ}
            - PUID=${PUID}
            - PGID=${PGID}
            - CRON_MIN=${CRON_MIN}
            - OIDC_ENABLED=${OIDC_ENABLED}
            - OIDC_PROVIDER_METADATA_URL=${OIDC_PROVIDER_METADATA_URL}
            - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
            - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
            # - OIDC_CLIENT_CRYPTO_KEY=${OIDC_CLIENT_CRYPTO_KEY}
            - OIDC_REMOTE_USER_CLAIM=${OIDC_REMOTE_USER_CLAIM}
            - OIDC_SCOPES=${OIDC_SCOPES}
            - OIDC_X_FORWARDED_HEADERS=${OIDC_X_FORWARDED_HEADERS}
        volumes:
            - ${CONFIG}/freshrss/.htaccess:/var/www/FreshRSS/p/i/.htaccess
            - ${CONFIG}/freshrss/.htpasswd:/var/www/FreshRSS/data/.htpasswd
            - ${CONFIG}/freshrss/freshrss/data:/var/www/FreshRSS/data
            - ${CONFIG}/freshrss/freshrss/extensions:/var/www/FreshRSS/extensions
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik"
            - "traefik.http.services.freshrss.loadbalancer.server.port=80"
            - "traefik.http.routers.freshrss.entrypoints=https"
            - "traefik.http.routers.freshrss.rule=Host(`freshrss.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.routers.freshrss.middlewares=authelia@file, securityHeaders@file"

    freshrss-mariadb:
        image: lscr.io/linuxserver/mariadb
        container_name: freshrss-mariadb
        networks:
            - freshrss
#        ports:
#            - 3306:3306
        environment:
            - TZ=${TZ}
            - PUID=${PUID}
            - PGID=${PGID}
            - MYSQL_ROOT_PASSWORD=${FRESHRSS_MARIADB_ROOT_PASS}
            - MYSQL_USER=${FRESHRSS_MARIADB_USER}
            - MYSQL_PASSWORD=${FRESHRSS_MARIADB_PASS}
            - MYSQL_DATABASE=${FRESHRSS_MARIADB_DB_NAME}
        volumes:
            - ${CONFIG}/freshrss/freshrss-mariadb:/config
        restart: unless-stopped
  ```

My `.env`
```
FRESHRSS_MARIADB_ROOT_PASS=rootpassword
FRESHRSS_MARIADB_USER=freshrss
FRESHRSS_MARIADB_PASS=password
FRESHRSS_MARIADB_DB_NAME=freshrss
CRON_MIN=13,43
OIDC_ENABLED=1
OIDC_PROVIDER_METADATA_URL=https://login.DOMAIN.COM/.well-known/openid-configuration
OIDC_CLIENT_ID=freshrss
OIDC_CLIENT_SECRET=autheliaclientsecret
OIDC_CLIENT_CRYPTO_KEY=
OIDC_REMOTE_USER_CLAIM=preferred_username
OIDC_SCOPES=openid groups email profile
OIDC_X_FORWARDED_HEADERS="X-Forwarded-Host X-Forwarded-Proto"
```

Reading the [docs](https://github.com/FreshRSS/FreshRSS/blob/edge/docs/en/admins/16_OpenID-Connect.md#setup) I need to setup FreshRSS with http based auth first so I've volume mounted both:

 - `.htaccess`
 - `.htpasswd`

and can successfully use http auth to login, the contents of each file are:

`.htaccess`
```
AuthUserFile /var/www/FreshRSS/data/.htpasswd
AuthName "FreshRSS"
AuthType Basic
Require valid-user
```

`.htpasswd` (username **admin** password **password**)
```
admin:{SHA}W6ph5Mm5Pz8GgiULbPgzG37mj9g=
```
However once I've completed the initial setup, logged in as `admin` with http-auth I cannot see any option in the webui to change the auth to OIDC.

![Screenshot_20231003_212955](https://github.com/FreshRSS/FreshRSS/assets/81871508/53df1315-376f-4609-a9b1-9f5a4b04c539)

I'm clearly doing something wrong but I don't know what and would really appreciate a second pair of eyes and any suggestions anyone could be kind enough to give.

For reference, here's how I currently have the Authelia OIDC client config:

```yaml
      - id: freshrss
        description: FreshRSS
        secret: $pbkdf2-sha512xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        public: false
        authorization_policy: one_factor
        redirect_uris:
          - https://freshrss.DOMAIN.COM/i/oidc/
        scopes:
          - openid
          - groups
          - email
          - profile
        userinfo_signed_response_alg: none
 ```
