### DISCUSSION TITLE
Traefik 404 error when deploying on subpath

### DISCUSSION THREAD

**Discussion by honnip** [FreshRSS/FreshRSS#5846] [Q&A] [answered]
## Describe the bug
Cannot host freshrss on `example.com/rss`

### with `X-Forwarded` headers
traefik reverse proxy with custom request headers:
|key|value|
|---|---|
|X-Forwarded-Prefix |/rss|
|X-Forwarded-Proto| https| 

it redirects to `/rss/i/?rid=123456789` then `/rss/rss/i/?rid=123456789` then `/rss/rss/rss/i/?rid=123456789` then repeating. (the browser shows `the page isn't redirecting properly`)

### without `X-Forwarded` headers
it redirects to `/rss/i/?rid=123456789`. (the browser shows `the page isn't redirecting properly`)

## To Reproduce
1. deploy linuxserver/freshrss:latest ([ebdc263cdbe8](https://hub.docker.com/layers/linuxserver/freshrss/latest/images/sha256-29305a5bac80b4db9ca85edf9b671f2e3a917bb724a2f319e1bf672917f54442)),
2. setup reverse proxy `example.com/rss` to freshrss instance

## Expected behavior
Proceed to the installation page

## Environment information
- Device: firefox desktop
- OS: linux
- Browser: firefox 119.0
- FreshRSS version: 1.22.1
- Database version: ?
- PHP version: ?
- Installation type: Docker linuxserver/freshrss:latest ([ebdc263cdbe8](https://hub.docker.com/layers/linuxserver/freshrss/latest/images/sha256-29305a5bac80b4db9ca85edf9b671f2e3a917bb724a2f319e1bf672917f54442))

**Comment by Alkarex** [comment]
Could you please try with one of our official Docker images, e.g. `freshrss/freshrss:edge`?

**Comment by Alkarex** [comment]
And could you please share the relevant Traefik configuration (e.g. the docker-compose), so I can give it a try?

**Comment by honnip** [comment]
My server is arm64 machine, so I tried it on my desktop. I was able to reproduce the same bug with an image from linuxserver.

I cannot reproduce the same with `freshrss/freshrss:edge` image, but it responses with a 404 error, which seems to be from freshrss, not traefik's. 

freshrss log:
```log
docker-freshrss-start[113925]: 172.17.0.1 - - [05/Nov/2023:20:00:27 +0900] "GET /rss HTTP/1.1" 404 196 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0"
```
  
---

I tried traefik with `--entryPoints.web.address=:80` and `--providers.docker`, freshrss with below labels:
- `traefik.http.routers.freshrss.rule=PathPrefix(`/rss`)
- `traefik.http.middlewares.redirect-feed.headers.customrequestheaders.X-Forwarded-Prefix=/rss`
- `traefik.http.middlewares.redirect-feed.headers.customrequestheaders.X-Forwarded-Proto=http`
- `traefik.http.routers.freshrss.middlewares=redirect-feed@docker`;

**Comment by Alkarex** [comment, marked as answer]
I have made an example of `docker-compose.yml` for you (without HTTPS, to test locally):

```yml
volumes:
  data:
  extensions:
  traefik-tmp:

networks:
  network:

services:

  traefik:
    image: traefik:2.10
    container_name: traefik
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    ports:
      - 80:80
    networks:
      - network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --global.sendAnonymousUsage
      - --accesslog=true
      - --api=false
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --log.level=INFO
      - --entryPoints.http.address=:80
    labels:
      - traefik.enable=false

  freshrss:
    image: freshrss/freshrss:edge
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - data:/var/www/FreshRSS/data
      - extensions:/var/www/FreshRSS/extensions
    networks:
      - network
    environment:
      TZ: Europe/Paris
      CRON_MIN: '3,33'
      TRUSTED_PROXY: 172.16.0.1/12
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.freshrssM1.compress=true
      - traefik.http.middlewares.freshrssM3.stripprefix.prefixes=/rss
      - traefik.http.routers.freshrss.entryPoints=http
      - traefik.http.routers.freshrss.middlewares=freshrssM1,freshrssM3
      - traefik.http.routers.freshrss.rule=PathPrefix(`/rss`)
```
