### DISCUSSION TITLE
Deploying FreshRSS to homelab using Ansible and Docker Compose

### DISCUSSION THREAD

**Discussion by elvisd7z** [FreshRSS/FreshRSS#5897] [Q&A]
Hi all,

I'm really struggling making FreshRSS auto update. I also installed the AutoTTL extension but it seams not to work, but there maybe I didn't get the goal correctly.
A manual trigger on the refresh button works as expected so I would rule out a connection issue.

```
---
- name: Deploy
  hosts: all
  become: true

  - name: "Create and start FreshRSS"
      community.docker.docker_compose:
        project_name: freshrss
        recreate: "always"
        pull: yes
        definition:
          services:
            freshrss:
              container_name: freshrss
              image: freshrss/freshrss:latest
              ports: 
                - "80:80"
              environment:
                TZ: "UTC"
                CRON_MIN: "2,17,32,47"
                TRUSTED_PROXY: "192.168.10.0/24"
              volumes:
                - "/data/freshrss/data:/var/www/FreshRSS/data"
                - "/data/freshrss/extensions:/var/www/FreshRSS/extensions"
              deploy:
                restart_policy:
                  condition: on-failure
                resources:
                  limits: 
                    cpus: '0.5'
                    memory: 256M
```

Do you see something that is misconfigured?
