### DISCUSSION TITLE
export-sqlite-for-user.php not working in docker-compose environment with postgresql database

### DISCUSSION THREAD

**Discussion by Fvbor** [FreshRSS/FreshRSS#5926] [Q&A] [answered]
Hi,
I need your help and didn´t found what I needed to solve the problem myself.

**Short Description**
Now:
- Hosting FreshRSS with docker-compose
- Using PostgreSQL

Goal:
- Hosting FreshRSS on a Webhosting 
- Using MySQL

Problem:
`export-sqlite-for-user.php` is not working

**Long Version**
I am using FreshRSS for a long time on my Server at home and want to migrate it now to a Webhosting from netcup.
My Home Server:
- Debian with docker and docker-compose
- FreshRSS in Version 1.21.1 as docker container from you
- All docker-mounts are directly mounted to a subfolder of the folder -> See tree and docker-compose.yml below

I found your guide to export the db for a specific user to a sqlite database. So I have my way to convert the postgresql to sqlite to mysql.

<details><summary>tree from the disk</summary>
I removed some folders from below the newsdomaintld folder in the overview
<p>

```
# cd /
# tree -L 5
.
└── opt
    └── containers
        └── newsdomaintld
            ├── backup_20231204.tar
            ├── data
            │   ├── applied_migrations.txt
            │   ├── cache
            │   ├── config.php
            │   ├── config.php.bak.php
            │   ├── extensions-data
            │   ├── favicons
            │   ├── fever
            │   ├── index.html
            │   ├── PubSubHubbub
            │   ├── tokens
            │   └── users
            ├── db
            │   ├── base
            │   ├── dump.sql
            │   ├── global
            │   ├── pg_commit_ts
            │   ├── pg_dynshmem
            │   ├── pg_hba.conf
            │   ├── pg_ident.conf
            │   ├── pg_logical
            │   ├── pg_multixact
            │   ├── pg_notify
            │   ├── pg_replslot
            │   ├── pg_serial
            │   ├── pg_snapshots
            │   ├── pg_stat
            │   ├── pg_stat_tmp
            │   ├── pg_subtrans
            │   ├── pg_tblspc
            │   ├── pg_twophase
            │   ├── PG_VERSION
            │   ├── pg_wal
            │   ├── pg_xact
            │   ├── postgresql.auto.conf
            │   ├── postgresql.conf
            │   ├── postmaster.opts
            │   └── postmaster.pid
            ├── db_postgres12_old
            │   ├── base
            │   ├── global
            │   ├── pg_commit_ts
            │   ├── pg_dynshmem
            │   ├── pg_hba.conf
            │   ├── pg_ident.conf
            │   ├── pg_logical
            │   ├── pg_multixact
            │   ├── pg_notify
            │   ├── pg_replslot
            │   ├── pg_serial
            │   ├── pg_snapshots
            │   ├── pg_stat
            │   ├── pg_stat_tmp
            │   ├── pg_subtrans
            │   ├── pg_tblspc
            │   ├── pg_twophase
            │   ├── PG_VERSION
            │   ├── pg_wal
            │   ├── pg_xact
            │   ├── postgresql.auto.conf
            │   ├── postgresql.conf
            │   └── postmaster.opts
            ├── docker-compose.yml
            ├── dump.sql
            └── extensions
``` 

</p>
</details> 

<details><summary>docker-compose.yml</summary>
<p>

```
version: '3.3'
services:
  newsdomaintld_db:
    image: postgres:13
    restart: unless-stopped
    container_name: newsdomaintld_db
    volumes:
      - /opt/containers/news.domain.tld/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=freshrss
      - POSTGRES_PASSWORD=Password_is_not_visible_for_you
      - POSTGRES_DB=freshrss
    networks:
      - default
  newsdomaintld:
    image: freshrss/freshrss
    restart: unless-stopped
    container_name: newsdomaintld
    environment:
      - TZ=Europe/Berlin
      - CRON_MIN=*/15
    volumes:
      - /opt/containers/news.domain.tld/data:/var/www/FreshRSS/data
      - /opt/containers/news.domain.tld/extensions:/var/www/FreshRSS/extensions
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.newsdomaintld.entrypoints=http"
      - "traefik.http.routers.newsdomaintld.rule=Host(`news.domain.tld`)"
      - "traefik.http.middlewares.newsdomaintld-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.newsdomaintld.middlewares=newsdomaintld-https-redirect"
      - "traefik.http.routers.newsdomaintld-secure.entrypoints=https"
      - "traefik.http.routers.newsdomaintld-secure.rule=Host(`news.domain.tld`)"
      - "traefik.http.routers.newsdomaintld-secure.tls=true"
      - "traefik.http.routers.newsdomaintld-secure.tls.certresolver=http"
      - "traefik.http.routers.newsdomaintld-secure.service=newsdomaintld"
      - "traefik.http.services.newsdomaintld.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true


``` 

</p>
</details> 

But when I try to export the database to sqlite I got following error

``` 
# docker exec -u www-data -it newsdomaintld /bin/bash
www-data@5b189c4e50bb:~/FreshRSS$ cli/export-sqlite-for-user.php --user user --filename export_20231204.sqlite
FreshRSS exporting database to SQLite for user “user”…
Error while initialising SQLite copy: SQLSTATE[HY000] [14] unable to open database file
FreshRSS[186]: [huseragen] [Mon, 04 Dec 2023 22:32:07 +0100] [error] --- Error while initialising SQLite copy: SQLSTATE[HY000] [14] unable to open database file
export-sqlite-for-user.php failed!
``` 

Same failure if I try it with docker exec directly
```
# docker exec -u www-data -it newsdomaintld cli/export-sqlite-for-user.php --user user --filename export_20231204.sqlite
FreshRSS exporting database to SQLite for user “user”…
Error while initialising SQLite copy: SQLSTATE[HY000] [14] unable to open database file
FreshRSS[193]: [user] [Mon, 04 Dec 2023 22:34:36 +0100] [error] --- Error while initialising SQLite copy: SQLSTATE[HY000] [14] unable to open database file
export-sqlite-for-user.php failed!
```

```
# docker exec -u www-data -it newsdomaintld cli/user-info.php -h
*       | user                | *     | *       | 2023-12-04T22:02:30+01:00 | 539.67 MiB      | 11         | 39         | 181877     | 36         | 3          | 0          | de    |
```

Can you say me where my error is?

If it is possible I don´t want to take a postgresql dumb and convert it with some tricks to mysql. Found a few guides, but a built in tool is better for this job :D
Thanks!
