### DISCUSSION TITLE
[HELP] Can't use API

### DISCUSSION THREAD

**Discussion by p1aintiff** [FreshRSS/FreshRSS#5951] [Q&A] [answered]
i don't why the api can't be used, though  thr url domain.com/api/ show passed

login with fluent reader

![image](https://github.com/FreshRSS/FreshRSS/assets/106045596/b16b1f54-8fe9-47e3-86dd-80f7e4c466d8)

the log when login with feedme
```
freshrss  | ip - - [17/Dec/2023:15:52:32 +0100] "POST /api/api/greader.php/accounts/ClientLogin?Email=edmond&Passwd=redacted HTTP/1.0" 404 196 "-" "FeedMe/3.16 (com.seazon.feedme; build:206; Android SDK 33)"
```
password for api
![截图 2023-12-17 21-19-01](https://github.com/FreshRSS/FreshRSS/assets/106045596/0bbf2d30-deb1-470f-ab6b-f0040ab63d48)

the log
```

```

nginx reserve proxy
```
server {
  server_name abc.com;
  listen 443 ssl http2;
  ssl_certificate /home/nginxWebUI/cert/*..pem;
  ssl_certificate_key /home/nginxWebUI/cert/*..key;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
  listen 80;
  if ($scheme = http) {
    return 301 https://$host:443$request_uri;
  }
  location / {
    proxy_pass http://127.0.0.1:8699;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_redirect http:// https://;
  }
}
```
start command
`docker-compose -f docker-compose.yml up -d --remove-orphans`

the  `docker-compose.yml`

```
version: "2.4"

volumes:
  data:
  extensions:

services:

  freshrss:
    image: freshrss/freshrss:latest
    # Optional build section if you want to build the image locally:
    build:
      # Pick #latest (stable release) or #edge (rolling release) or a specific release like #1.21.0
      context: https://github.com/FreshRSS/FreshRSS.git#latest
      dockerfile: Docker/Dockerfile-Alpine
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    ports:
      - "8699:80"  #前面的port改为你自己的端口
    volumes:
      - data:/var/www/FreshRSS/data
      - extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: Europe/Paris
      CRON_MIN: '3,33'
      TRUSTED_PROXY: 172.16.0.1/12 192.168.0.1/16
```
