### DISCUSSION TITLE
Trouble setting FreshRSS with Authelia

### DISCUSSION THREAD

**Discussion by poperigby** [FreshRSS/FreshRSS#6017] [Q&A] [answered]
I've been trying really hard to get this setup, but am having some serious trouble. I'm using Podman for orchestration and Caddy for my webserver, but that seems mostly irrelevant.

Here's my Podman Kubernetes YAML:

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: freshrss-pod
    io.containers.autoupdate: registry
    io.containers.sdnotify: conmon
  name: freshrss-pod
spec:
  securityContext:
    seLinuxOptions:
      type: spc_t
  containers:
    - name: freshrss
      image: docker.io/freshrss/freshrss:edge
      volumeMounts:
        - name: freshrss-data
          mountPath: /var/www/FreshRSS/data
        - name: freshrss-extensions
          mountPath: /var/www/FreshRSS/extensions
      environment:
        - name: OIDC_ENABLED
          value: true
        - name: OIDC_PROVIDER_METADATA_URL
          value: https://auth.MYDOMAIN.com/.well-known/openid-configuration
        - name: OIDC_CLIENT_ID
          value: freshrss
        - name: OIDC_CLIENT_SECRET
          value: REDACTED UNHASHED CLIENT SECRET
        - name: OIDC_SCOPES
          value: openid groups email profile
        - name: OIDC_X_FORWARDED_HEADERS
          value: X-Forwarded-Host X-Forwarded-Proto
  volumes:
    - name: freshrss-data
      persistentVolumeClaim:
        claimName: freshrss-data
    - name: freshrss-extensions
      persistentVolumeClaim:
        claimName: freshrss-extensions
```

And here's my FreshRSS entry in my Authelia `configuration.yaml`

```yaml
identity_providers:
  oidc:

    clients:
      - id: freshrss
        description: FreshRSS
        secret: REDACTED HASHED CLIENT SECRET
        authorization_policy: one_factor
        redirect_uris:
          - https://news.MYDOMAIN.com/i/oidc
```

I made sure to set the authorization type type to HTTP in the FreshRSS settings, and I can confirm that's the case by looking in the `config.php`

Now for the problem, whenever I navigate to https://news.MYDOMAIN.cc, it redirects me to https://news.MYDOMAIN.com/i/?rid=6594bdc506149, and shows me this:

![Screenshot 2024-01-02 at 17-52-36 Error 403 - Forbidden · FreshRSS](https://github.com/FreshRSS/FreshRSS/assets/20866468/c31b89db-9cb4-4285-846f-315fbf0e9893)

The username is correct, so it's at least picking that up.

This is what shows up in the FreshRSS logs:
```
[Wed Jan 03 01:50:22.646358 2024] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.57 (Debian) configured -- resuming normal operations
[Wed Jan 03 01:50:22.646383 2024] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
10.89.1.39 - - [03/Jan/2024:01:50:45 +0000] "GET / HTTP/1.1" 302 - "https://auth.MYDOMAIN.com/" "Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0"
10.89.1.39 - - [03/Jan/2024:01:50:45 +0000] "GET /i/?rid=6594bd7541c25 HTTP/1.1" 403 4260 "https://auth.MYDOMAIN.com/" "Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0"
```
