### DISCUSSION TITLE
Feeds not updating on cron schedule

### DISCUSSION THREAD

**Discussion by TheRealBenForce** [FreshRSS/FreshRSS#6093] [Q&A]
I'm hosting on my synology. I'm honestly not sure if this has been happening for awhile or the entire time I've run this app. But just to be safe I recreated the container (not the db container). A couple notes:

- I'm running version 1.22.1.
- I set CRON_MIN='0' to try to make it a bit easier to identify logs to troubleshoot. 
- I did previously have '3,33'. 
- I have Archive > Do not automatically refresh more often than > 45 min. 
- Feed settings have Do not automatically refresh more often than default. 
- Inside my container I can I have nothing in /tmp/ folder. 
- Also inside my container crontab -l shows: 
`0 * * * * . /var/www/FreshRSS/Docker/env.txt;           su www-data -s /bin/sh -c 'php /var/www/FreshRSS/app/actualize_script.php'              2>> /proc/1/fd/2 > /tmp/FreshRSS.log`

Inside the running app, if I click the button to update the feeds manually, my feed updates roll in. 

Any help would be super appreciated, thanks!

```
version: "2.4"
volumes:
  data:
  extensions:
  db:
services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - data:/var/www/FreshRSS/data
      - extensions:/var/www/FreshRSS/extensions
    environment:
      CRON_MIN: '0'
      TRUSTED_PROXY: 172.16.0.1/12 192.168.0.1/16 10.88.0.1/24
    ports:
      - "8084:80"
  freshrss-db:
    image: postgres:16
    container_name: freshrss-db
    hostname: freshrss-db
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_BASE:-freshrss}
      POSTGRES_USER: ${DB_USER:-freshrss}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-freshrss}
```
