### DISCUSSION TITLE
How can I add custom font?

### DISCUSSION THREAD

**Discussion by sherlcok314159** [FreshRSS/FreshRSS#6194] [Q&A] [answered]
I want to customize the font. But the font is not prebuilt in freshRSS. How can I do this? A detailed answer please.

**Comment by math-GH** [comment]
Let us know more information what you have:
Which FreshRSS version do you use? Is CustumCSS extension installed? Do you have the font as files or just as a link to (f.e.) Google Fonts?

**Comment by sherlcok314159** [comment]
The latest docker version of FreshRSS. Installed the latest CustomCSS. The font CSS can be like below:

```css
@font-face {
  font-family: LXGW WenKai Screen;
  src: url("https://cdn.jsdelivr.net/npm/lxgw-wenkai-subset@1.235.2/woff2/lxgwwenkaiscreen.subset.v1.235.standard.woff2");
}
```

**Comment by sherlcok314159** [comment, marked as answer]
I have already done it. The below is the procedure.

1. Edit the docker-compose.yml
    ```yml
    - ./fonts:/var/www/FreshRSS/p/themes/fonts
    ```
2. Use the custom CSS.
    ```css
    @font-face {
        font-family: LXGW WenKai Screen;
        src: url("/themes/fonts/lxgwwenkaiscreen.subset.v1.235.standard.woff2");
    }
    ```
