### DISCUSSION TITLE
Multi Container options and High Availability Possibilities

### DISCUSSION THREAD

**Discussion by Aevrin** [FreshRSS/FreshRSS#6320] [General]
I was wondering what the options were having freshrss in any sort of high availability without using swarm and/or kubernetes.  I was thinking either if I use sqlite stored on a shared filesystem (either local, NFS, or something fancy like ceph), or if using mysql and copying the volume data, then they should all reference the same DB.
When testing using sqlite on a local bind mount, it seems to work really well.  I configured it in one container, then they all work, but I suspect this isn't supported.

```yaml
version: "3.3"
  services:
    freshrss-1:
      container_name: Freshrss-Compose-1
      hostname: freshrss-compose-1
      image: freshrss/freshrss:latest
    restart: always
    volumes:
      - /Data/RSSS/data:/var/www/FreshRSS/data/
      - /Data/RSSS/extensions:/var/www/FreshRSS/extensions
    ports:
      - 8081:80
  freshrss-2:
    container_name: Freshrss-Compose-2
    hostname: freshrss-compose-2
    image: freshrss/freshrss:latest
    restart: always
    volumes:
      - /Data/RSSS/data:/var/www/FreshRSS/data/
      - /Data/RSSS/extensions:/var/www/FreshRSS/extensions
    ports:
      - 8082:80
  freshrss-3:
    container_name: Freshrss-Compose-3
    hostname: freshrss-compose-3
    image: freshrss/freshrss:latest
    restart: always
    volumes:
      - /Data/RSSS/data:/var/www/FreshRSS/data/
      - /Data/RSSS/extensions:/var/www/FreshRSS/extensions
    ports:
      - 8083:80
```
