### DISCUSSION TITLE
FreshRSS + Authelia OIDC: unable to login

### DISCUSSION THREAD

**Discussion by zkvvoob** [FreshRSS/FreshRSS#6557] [Q&A] [answered]
Hi all,

I'm trying to get FreshRSS to use Authelia as an OIDC provider. I've used the [integration documentation](https://www.authelia.com/integration/openid-connect/freshrss/). I'm running all services in Docker containers, including Nginx Proxy Manager, which acts as a reverse proxy.  My configuration looks like this:

**Portainer stack**
```yaml
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      PUID: 3000
      PGID: 100
      TRUSTED_PROXY: 172.16.0.1/12 10.0.0.0/16
      TZ: Europe/London
      OIDC_ENABLED: 1
      OIDC_PROVIDER_METADATA_URL: https://auth.mydomain/.well-known/openid-configuration
      OIDC_CLIENT_ID: freshrss
      OIDC_CLIENT_CRYPTO_KEY: WnoO3kRzXynag2XXXXXXXXXX
      OIDC_CLIENT_SECRET: L***Y.
      OIDC_REMOTE_USER_CLAIM: preferred_username
      OIDC_SCOPES: openid groups email profile
      OIDC_X_FORWARDED_HEADERS: X-Forwarded-Host X-Forwarded-Port X-Forwarded-Proto
      CRON_MINМ: "*/15"
    volumes:
      - /mnt/apps/data/freshrss:/config
    ports: 
      - 9084:80
    restart: unless-stopped

networks:
  default:
    name: my-network
    external: true
```

**Authelia client config**
```yaml
identity_providers:
    oidc:
        clients:
         - client_id: freshrss
          client_name: FreshRSS
          client_secret: $pbkdf2-sha512$***
          public: false
          authorization_policy: one_factor
          consent_mode: auto
          pre_configured_consent_duration: 6M
          scopes:
            - openid
            - email
            - profile
            - groups
          grant_types: 
            - authorization_code
          redirect_uris:
          - https://news.mydomain.com:443/i/oidc/
          userinfo_signed_response_alg: none
          token_endpoint_auth_method: 'client_secret_basic'
```

Access control inside FreshRSS was switched to HTTP. Container restarted and then I started getting the following message:

```
Error 403 - Forbidden

You don’t have permission to access this page [HTTP Remote-User= ; Remote IP address=172.20.0.38]

Login
```

where the login link leads to `https://news.mydomain/i/?c=auth&a=login`, but when I click it, I end up at the very same page.

At no moment am I redirected to Authelia's login page and now I'm locked out of FreshRSS, unable to go back to form authentication.

Could you help me figure out what's wrong in my case, please?
