### DISCUSSION TITLE
In reading view photos aren't shown

### DISCUSSION THREAD

**Discussion by tomhusband** [FreshRSS/FreshRSS#6652] [Q&A]
In a few of my feeds I like them in reading view so I can see the accompanying photo. All I get lately is an attached file. Would that be something I change in FreshRSS or is it a feed issue?

The feed [validator show problems](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.archdaily.com%2F.xml).

The feed was not working for several days but now seems to be back. Could that be the issue and I should give it a little more time?

All my other feeds in Reader View show the photos.
![freshrss](https://github.com/user-attachments/assets/0b42156b-c5d1-4488-82f5-ef97e79a83d7)

**Comment by Alkarex** [comment]
Would you be able to try this patch? https://github.com/FreshRSS/FreshRSS/pull/6653

**Reply by tomhusband** [reply]
Sure, I could try the patch. What do I need to do?

Many thanks.

**Reply by Alkarex** [reply]
Assuming you are using our official Docker image, then:

To test a PR, you need to point your Docker or Docker Compose to the right PR, as such:

```yml
  freshrss:
    image: freshrss/freshrss:6653
    build:
      context: https://github.com/Alkarex/FreshRSS.git#enclosure-regex
      dockerfile: Docker/Dockerfile-Alpine
    ...
```

* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose.yml
* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#build-custom-docker-image

And by the way, PR welcome to add some tips [to our documentation](https://github.com/FreshRSS/FreshRSS/blob/edge/docs/en/contributing.md) on how to test patches
