### DISCUSSION TITLE
Where are feeds located on disk?

### DISCUSSION THREAD

**Discussion by shimizurei** [FreshRSS/FreshRSS#6801] [Q&A]
My previous installation stopped working correctly after a messed up upgrade in portainer, so I re-installed using the LSIO version of the docker compose file. Unfortunately for me, the last time I backed up my feeds was in 2022. Is it possible to salvage my latest feeds or am I SOL?

**Comment by Alkarex** [comment]
The answer depends on your previous installation. In particular, what database did you use?

**Reply by shimizurei** [reply]
Postgres

**Reply by Alkarex** [reply]
Right, and installed with Docker? And do you still have the PostgreSQL volume? (try for instance `docker volume ls`) And do you still have your old settings (e.g. credentials)?

**Reply by shimizurei** [reply]
Yes to all.

**Reply by Alkarex** [reply]
You need to show the details 🤓

**Reply by shimizurei** [reply]
I'm sorry, I'm not sure what you're asking for. Here is my old docker compose (before moving to Linuxserver's):

```yaml
version: '3'

services:
  freshrss-db:
    image: postgres:12-alpine
    container_name: freshrss-db
    hostname: freshrss-db
    restart: unless-stopped
    volumes:
      - ./freshrss/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_BASE:-freshrss}
      POSTGRES_USER: ${DB_USER:-freshrss}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-freshrss}

  freshrss-app:
    image: freshrss/freshrss:1.21.0-alpine
    container_name: freshrss-app
    hostname: freshrss-app
    restart: unless-stopped
    ports:
      - '8080:80'
    depends_on:
      - freshrss-db
    volumes:
      - ./freshrss/data:/var/www/FreshRSS/data
      - ./freshrss/extensions:/var/www/FreshRSS/extensions
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: America/Somewhere
      CRON_MIN: '*/20'
```

I have the old folder, manually moved to another directory for dead/old docker installs so I could reuse the folder names for the LSIO install.
