### DISCUSSION TITLE
User CSS/JS for direct label/feed configuration from aside bar on mobile?

### DISCUSSION THREAD

**Discussion by mtalexan** [FreshRSS/FreshRSS#6885] [Q&A] [answered]
I want to be able to easily jump to label and feed configuration from the sidebar even on mobile while using the default theme ([CSS definition](https://github.com/FreshRSS/FreshRSS/blob/edge/p/themes/base-theme/frss.css#L2330)).  
I've gotten the gear icons to show up in the sidebar, and made them permanently visible instead of only on hover by adding User CSS:

```css
/* In mobile view... */
@media (max-width: 840px) {
    /* Keep the drop down in the sidebar tree displayed with tight padding. */
    .aside_feed .tree-folder-items .dropdown {
        padding: 1px;
        display: inline-block;
    }
    /* Reduce the padding and make it fully opaque instead of partially. */
    .aside_feed .tree-folder-items .item .dropdown-toggle {
        padding: 1px;
        opacity: 1;
    }
    /* Icon is always visible instead of only on hover */
    .aside_feed .tree-folder-items .item .dropdown-toggle > .icon {
        visibility: visible;
    }
    /* Tighten up the padding on the sidebar item title text */
    .tree-folder-items > .item > .item-title {
        padding-left: 1px;
        display: inline-block;
    }
}
```

However, when I click the icon it brings up the drop down menu and then immediately hides the entire aside menu. Anyone have any ideas for how to keep the aside menu visible when the drop down menu is shown?

---

It appears the aside menu is set to go between 0 width and normal width when in mobile view based on `:hover`.  The drop down menu is part of the aside menu tree so I would expect the aside menu to remain visible when the drop down menu is shown, but that doesn't seem to be the case.  Maybe it's an issue with the z-layering or something so hover focus doesn't appear to remain in the aside and the hover effect re-hides it?  Or maybe it's because the `:hover` isn't detected as being within the drop down menu right after it's opened?  
I'm not super familiar with this, so I'm not sure. 

---
**EDIT:**
  
This is what my sidebar on mobile looks like FWIW.
![image](https://github.com/user-attachments/assets/027cf5ba-c100-4884-bc8f-507422a1ee7c)
