### DISCUSSION TITLE
How to easily duplicate docker prod environment to use :edge release ?

### DISCUSSION THREAD

**Discussion by Fluidetom** [FreshRSS/FreshRSS#6928] [Q&A] [answered]
Hi,

I have a beginner question in Docker. I'm hosting FreshRSS in Docker on my Synology NAS.
I followed this guide to set it up : https://mariushosting.com/synology-install-freshrss-with-portainer/.

I also use portainer to manage the various containers and I would like to duplicate the working FreshRSS container but use the :edge release instead.
I've been looking around the doc and so on, but I'm not sure which `image:` value I should specify instead of `ghcr.io/linuxserver/freshrss:latest`.
Is it `https://github.com/FreshRSS/FreshRSS.git#edge` or `https://hub.docker.com/layers/freshrss/freshrss/edge/images/sha256-c4b0f60ebe762874d92f604e039a56d54f55b65e3ede43b8d0da3fd330203ce7` ? How could I always point to the latest :edge release in this compose file ?

Thanks in advance

I've used the following compose file:

```
version: "3.9"
services:
  freshrss:
    image: ghcr.io/linuxserver/freshrss:latest
    container_name: freshrss
    hostname: freshrss
    mem_limit: 3g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: curl -f http://localhost:80/ || exit 1
    ports:
      - 9009:80
    volumes:
      - /volume1/docker/freshrss:/config:rw
    environment:
      TZ: Europe/Brussels
      PUID: 10
      PGID: 100
    restart: on-failure:5
```
