### DISCUSSION TITLE
Caddy Reverse Proxy Not Working

### DISCUSSION THREAD

**Discussion by BigTreezZ** [FreshRSS/FreshRSS#7245] [Q&A]
Hello,

I want to use Caddy as the reverse proxy for FreshRSS, since it's what I already use for other services. 
I followed the guide in [here using a subdomain:](http://freshrss.github.io/FreshRSS/en/admins/Caddy.html)

```caddy
subdomain.example.com {
     reverse_proxy freshrss:80
 }
```

I am running FreshRSS via Docker with Docker Compose. Here is how my .env file looks:

```env
BASE_URL=https://subdomain.mydomain.com
ADMIN_EMAIL=my-email
ADMIN_PASSWORD=my-password
ADMIN_API_PASSWORD=my-api-password
PUBLISHED_PORT=8081
SERVER_DNS=subdomain.mydomain.com
DB_HOST=freshrss-db
DB_BASE=freshrss
DB_PASSWORD=freshrss
DB_USER=freshrss`
```

Here is how my docker-compose.yml file looks:

```yaml
version: "2.4"

volumes:
  data:
  extensions:

services:

  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - ./data:/var/www/FreshRSS/data
      - ./extensions:/var/www/FreshRSS/extensions
    ports:
      # If you want to open a port 8080 on the local machine:
      - "8081:80"
    environment:
      TZ: Europe/Paris
      CRON_MIN: '3,33'
      OIDC_ENABLED: 0
```

When I use the Caddy config given on the guide, I am redirected to a blank page, but I can still access the FreshRSS login page via direct IP.

However, if I edit the Caddy config like this:

```caddy
subdomain.example.com {
        reverse_proxy http://localhost:8081
}
```

I can access the FreshRSS login page from my subdomain, but I can also still access it via direct IP, which I do not want to. How can I configure Caddy to access FreshRSS via a subdomain, while not allowing access via direct IP anymore?

I'm fairly new to self-hosting, and my server is held up with glue and prayers, so bear with me.

I appreciate any help in advance.

(Edit: I messed up formatting and cant figure it out)

**Comment by Alkarex** [comment]
Quick answer without having looked into the details: for production, you are not supposed to expose FreshRSS via a local port so comment out or remove the following lines from your Docker Compose:

```yaml
ports:
      # If you want to open a port 8080 on the local machine:
      - "8081:80"
```

Your Caddy is supposed to be on the same Docker network than FreshRSS and therefore should not need that port to be open

**Reply by BigTreezZ** [reply]
> Your Caddy is supposed to be on the same Docker network than FreshRSS and therefore should not need that port to be open

Thank you for replying. But as of right now, it would be really helpful if I could run Caddy on a different network from FreshRSS. I have a lot of applications depending on Caddy as I have it right now. 

Is it possible? If it isn't possible, or it's too difficult to do, I guess I can change Caddy to run on the same compose file as FreshRSS, but it'd be awesome if I didn't have to.

**Reply by Alkarex** [reply]
It needs not be in the same Docker Compose. And your Caddy can be attached to multiple Docker networks. See the corresponding option in the Docker Compose documentation

**Reply by BigTreezZ** [reply]
Well, I have Caddy running with "network mode: host", so I tried making FreshRSS run with "network mode: host" as well, and I also tried with the option 

`networks:
  -host`
  
while doing everything seemingly correctly, such as listing networks and marking them as external, etc. No luck unfortunately, I still have the blank page when I try opening it via my subdomain. I guess I'll have it running like this for the time being.

How my configs looked like on my last attempt:

```
version: "2.4"

volumes:
  data:
  extensions:

services:

  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    network_mode: host
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - ./data:/var/www/FreshRSS/data
      - ./extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: Europe/Paris
      CRON_MIN: '3,33'
      LISTEN: 0.0.0.0:80
      OIDC_ENABLED: 0
```


```
subdomain.example.com {
     reverse_proxy freshrss:80
 }
```
Thanks for the help again.

**Reply by Alkarex** [reply]
I do not advise `network_mode: host`, which is the reason for your problems. If you use this mode, you disable the Docker network logic and isolation, and therefore have to make your firewall / IP routing rules manually.

**Reply by BigTreezZ** [reply]
I need to have Caddy set to host network mode, because I use it to reverse proxy non docker applications as well. 

Concerning FreshRSS, if I set a listening port, it'll be directly accessible via IP. If I don't set it, I don't know which port to have Caddy redirect to, since I can't just have it do `freshrss:80`.

**Reply by Frenzie** [reply]
If you set a local IP instead of 0.0.0.0 that should be fine, shouldn't it?

**Reply by BigTreezZ** [reply]
You mean setting in the docker file the option `LISTEN: 0.0.0.0:80` with my machine's network IP, like for example `LISTEN: 192.168.1.xxx:80`?

**Reply by Frenzie** [reply]
Given the localhost above I meant 127.0.0.1, but if something like that meets your needs better, sure.

**Reply by BigTreezZ** [reply]
I'd have to remove this section in the compose file right?

```
ports:
      # If you want to open a port 8080 on the local machine:
      - "8081:80"
```

and add this to the compose file:

```
LISTEN: 127.0.0.1:80
```

and have the caddyfile like this:

```
subdomain.example.com {
        reverse_proxy http://localhost:8081
}
```

**Reply by Frenzie** [reply]
I would imagine so. Probably about just as fast to try as to ask? :-)

**Reply by BigTreezZ** [reply]
I did try it, I just wanted to make sure I was doing it right.

I tried it with the exact changes I mentioned above. It still fails to redirect me to FreshRSS via my subdomain. Just a black screen.

**Reply by Frenzie** [reply]
If you're saying you did that verbatim rather than as a general idea then of course the ports make no sense.

**Reply by BigTreezZ** [reply]
That's why I asked if what I had written above was correct! How should I do it then? I wouldn't be asking here if I knew how to :sweat_smile:

**Reply by Frenzie** [reply]
You need to separate the steps.

1. Make sure you can reach the server. Just do that however you do it. Take care of this first. Don't work with a black hole.
2. With things working, proxy that.

**Reply by BigTreezZ** [reply]
Concerning point 1, that's done. I can reach the server just fine with the config I sent on the original post, using that .env file, docker-compose file, and the second Caddy config I listed. I can reach the server via:
-The actual subdomain I assigned it, which is what I want
-Direct external IP with port 8081, as well as direct internal IP with port 8081, both which I want to prevent.

From there, I don't know much else.

**Reply by Alkarex** [reply]
All that is not related to FreshRSS and is standard Docker configuration. You can try exactly the same with an image such as `httpd` (like in `docker run -p 8080:80 httpd` to do your debugging.
Check https://docs.docker.com/compose/how-tos/networking/

Quick tip: see your active Docker networks with `docker network ls`

But anyway, some quick points:
* No, no need to add `LISTEN` anywhere. Stick to the defaults.
* If you use *host* as network mode, you need to edit your routes / firewall manually, which I do not recommend. Stick instead to the default bridge mode.
* If you use `ports`, it will open ports locally, which is not a good approach for production. The best is to use the [*networks* section](https://docs.docker.com/compose/how-tos/networking/) properly. You can attach your Caddy to multiple Docker networks. An alternative, as @Frenzie is saying, is to limit the scope of your port by a syntax like `- "127.0.0.1:8080:80"` but this is poorer than using the Docker networks as it makes the rest of the configuration more complicated (access from other containers) and less isolated.

The simplest, default approach, with nothing custom and no ports is also what should work best.

**Comment by BigTreezZ** [comment]
Thank you for your explanation, I figured it out! However, I still went with the host network_mode route.

I set the `network_mode: host` and I removed the `ports` section on my FreshRSS compose file. I then added a listening port with `LISTEN: 127.0.0.1:8081`.

My Caddy docker container is running on a separate docker-compose file, with `network_mode: host` as well. All I had to do was write in the Caddyfile: 

```
subdomain.example.com {
     reverse_proxy 127.0.0.1:8081
 }
```

And that's it! I can access FreshRSS on my browser just fine via the subdomain I wanted, and I can no longer reach it via internal or external IP. 

Thank you for your help guys! I'm leaving my files here in case someone else runs into the same or a similar issue:

docker-compose.yml:

```
version: "2.4"

volumes:
  data:
  extensions:

services:

  freshrss:
    image: freshrss/freshrss:latest
    network_mode: host
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - ./data:/var/www/FreshRSS/data
      - ./extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: Europe/Paris
      CRON_MIN: '3,33'
      LISTEN: 127.0.0.1:8081
      OIDC_ENABLED: 0
```

Caddyfile:

```
subdomain.example.com {
        reverse_proxy 127.0.0.1:8081
}
```
