### DISCUSSION TITLE
Use a custom font from local file system

### DISCUSSION THREAD

**Discussion by chasedmartin** [FreshRSS/FreshRSS#7246] [Q&A]
I'm looking to use a custom font on my local file system that I have. Currently I have the custom CSS set up to use the font but I'm struggling to be able to query the font file from the web service. Here is my docker compose file:

```
version: "3.9"
services:
  freshrss:
    image: ghcr.io/linuxserver/freshrss:latest
    container_name: FreshRSS
    hostname: freshrss
    mem_limit: 3g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: curl -f http://localhost:80/ || exit 1
    ports:
      - 9009:80
    volumes:
      - /volume1/docker/freshrss:/config:rw
      - /volume1/docker/freshrss/fonts:/var/www/FreshRSS/p/themes/fonts
    environment:
      TZ: America/Chicago
      PUID: 1026
      PGID: 100
    restart: on-failure:5
```

Where the font folder is where my custom font file is stored. I've been using #6194 as a resource but I fear that I can't gain anything else from that thread.

**Comment by Alkarex** [comment]
Quick feedback already: watch out that the LinuxServer image is a third party image, not using the same paths than [our official ones](https://hub.docker.com/r/freshrss/freshrss/), so be careful not to mix the documentations

**Reply by chasedmartin** [reply]
Doh, you're right. I was meaning to switch over anyway so here's my updated docker compose file:

```
version: "2.4"

services:
  freshrss:
    image: freshrss/freshrss:latest
    build:
      context: https://github.com/FreshRSS/FreshRSS.git#latest
      dockerfile: Docker/Dockerfile-Alpine
    container_name: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - ./data:/var/www/FreshRSS/data:rw
      - ./extensions:/var/www/FreshRSS/extensions
      - ./fonts:/var/www/FreshRSS/p/themes/fonts
    ports:
      - "8080:80"
    environment:
      TZ: America/Chicago
      CRON_MIN: '*30'
      FRESHRSS_ENV: production
```
