### DISCUSSION TITLE
\''-D: line 0: syntax error: unexpected end of file (expecting ")") when trying to launch container

### DISCUSSION THREAD

**Discussion by bwbuhse** [FreshRSS/FreshRSS#7267] [Q&A] [answered]
Hey y'all, I've been trying to get FreshRSS's OCI container running (using Incus, rather than Docker,) but no matter what I do, I get `\''-D: line 0: syntax error: unexpected end of file (expecting ")")` and it won't start. Does anyone know where I should look into this?

**Comment by Alkarex** [comment]
Hello,
What image, more precisely? And please show your command line.

**Reply by bwbuhse** [reply]
I've tried with all of:

- `latest`
- `edge`
- `latest-alpine`
- `edge-alpine`


With incus, I just am trying to start with `incus start freshrss` and it works more or less like a docker compose setup would. Here's my container's configuration:

```yaml
architecture: x86_64
config:
  environment.COPY_LOG_TO_SYSLOG: "On"
  environment.COPY_SYSLOG_TO_STDERR: "On"
  environment.CRON_MIN: 1,31
  environment.HOME: /root
  environment.PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  environment.TERM: xterm
  environment.TZ: America/Chicago
  image.architecture: x86_64
  image.description: docker.io/freshrss/freshrss (OCI)
  image.id: freshrss/freshrss
  image.type: oci
  volatile.base_image: e7897e90c1e0ab4a68cb643ff509dec4e3b85bbe42e2688ed9f95eb190bcb2b1
  volatile.cloud-init.instance-id: 6d68262e-916f-4489-9d3d-ba8c20ddbbc4
  volatile.container.oci: "true"
  volatile.eth0.hwaddr: 00:16:3e:5c:ce:59
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000},{"Isuid":true,"Isgid":false,"Hostid":1000,"Nsid":1000,"Maprange":1},{"Isuid":true,"Isgid":false,"Hostid":1001001,"Nsid":1001,"Maprange":999998999},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000},{"Isuid":false,"Isgid":true,"Hostid":1000,"Nsid":1000,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":1001001,"Nsid":1001,"Maprange":999998999}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000},{"Isuid":true,"Isgid":false,"Hostid":1000,"Nsid":1000,"Maprange":1},{"Isuid":true,"Isgid":false,"Hostid":1001001,"Nsid":1001,"Maprange":999998999},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000},{"Isuid":false,"Isgid":true,"Hostid":1000,"Nsid":1000,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":1001001,"Nsid":1001,"Maprange":999998999}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: STOPPED
  volatile.last_state.ready: "false"
  volatile.uuid: 04e0a9b7-788f-4143-a2ce-027d41327f98
  volatile.uuid.generation: 04e0a9b7-788f-4143-a2ce-027d41327f98
devices:
  data:
    path: /var/www/FreshRSS/data
    source: /home/ben/oci-configs/freshrss/data
    type: disk
  extensions:
    path: /var/www/FreshRSS/extensions
    source: /home/ben/oci-configs/freshrss/extensions
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
created_at: 2025-01-29T00:59:00.876962567Z
name: freshrss
status: Stopped
status_code: 102
last_used_at: 2025-01-29T01:03:19.21677712Z
location: none
type: container
project: user-1000
```

However, if I check the status after trying to start it, the container shows as stopped:

```
$ incus info freshrss
Name: freshrss
Description:
Status: STOPPED
Type: container (application)
Architecture: x86_64
Created: 2025/01/28 19:27 CST
Last Used: 2025/01/28 20:01 CST
```

I get the title error from checking the container's console log:

```
$ incus console --show-log freshrss
\''-D: -c: line 2: unexpected EOF while looking for matching `)'
```
