### DISCUSSION TITLE
OpenID Connect Issues with FreshRSS Behind Nginx Proxy Manager

### DISCUSSION THREAD

**Discussion by SplendidAppendix** [FreshRSS/FreshRSS#7295] [Q&A]
# OpenID Connect Issues with FreshRSS Behind Nginx Proxy Manager

## Summary

I'm having persistent issues configuring FreshRSS with OpenID Connect (OIDC) authentication when deployed behind Nginx Proxy Manager. Despite setting the necessary headers, `mod_auth_openidc` does not recognize them, causing authentication failures.

## Logs

The following errors appear in my Portainer logs:

```
oidc_proto_parse_idtoken: oidc_jwt_parse failed: [src/jose.c:813: oidc_jwt_parse]: cjose_jws_import failed: invalid argument [file: jws.c, function: cjose_jws_import, line: 834]
oidc_check_x_forwarded_hdr: OIDCXForwardedHeaders configured for header X-Forwarded-Host but not found in request
oidc_check_x_forwarded_hdr: OIDCXForwardedHeaders configured for header X-Forwarded-Host but not found in request
oidc_check_x_forwarded_hdr: OIDCXForwardedHeaders configured for header X-Forwarded-Port but not found in request
oidc_check_x_forwarded_hdr: OIDCXForwardedHeaders configured for header X-Forwarded-Host but not found in request
oidc_check_x_forwarded_hdr: OIDCXForwardedHeaders configured for header X-Forwarded-Port but not found in request
```

## Docker Compose Setup

Here's my `docker-compose.yml` configuration for FreshRSS:

```yaml
version: '3.8'

services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      TZ: America/Chicago
      CRON_MIN: "0,15,30,45"
      OIDC_ENABLED: "1"
      OIDC_PROVIDER_METADATA_URL: "https://auth.jhnsnf.am/application/o/freshrss/.well-known/openid-configuration"
      OIDC_CLIENT_ID: "sLEJAzXbQ21489E2Klzy7IkuY6xh4YK6FkCgzhoS"
      OIDC_CLIENT_SECRET: "REDACTED"
      OIDC_X_FORWARDED_HEADERS: "X-Forwarded-Port X-Forwarded-Proto X-Forwarded-Host"
      OIDC_SCOPES: "openid email profile"
      OIDC_REMOTE_USER_CLAIM: "preferred_username"
      TRUSTED_PROXY: "172.24.10.62/24"
      BASE_URL: "https://fresh.jhnsnf.am"
    volumes:
      - data:/var/www/FreshRSS/data
      - extensions:/var/www/FreshRSS/extensions

volumes:
  data:
  extensions:
```

## Nginx Proxy Manager Configuration

I have configured the following headers under the Advanced tab of Nginx Proxy Manager:

```nginx
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Port $server_port;
```

### Provider Settings
- **Name:** FreshRSS  
- **Authorization Flow:** default-provider-authorization  
- **Redirect URIs:** `https://fresh.jhnsnf.am/i/oidc/`  
- **Client ID:** `freshrss`  
- **Client Secret:** [REDACTED]  

### Application Settings
- **Name:** FreshRSS  
- **Slug:** `freshrss`  
- **Provider:** FreshRSS  
- **Authorization Flow:** default-application-authorization  

## Persistent Issue

Despite these configurations, FreshRSS still reports missing `X-Forwarded-Host` and `X-Forwarded-Port`, preventing successful OIDC authentication.

Has anyone else encountered this issue? Any guidance would be greatly appreciated.
