### DISCUSSION TITLE
Unable to connect to API from an external network with FreshRSS behind NGINX reverse proxy

### DISCUSSION THREAD

**Discussion by Landrin201** [FreshRSS/FreshRSS#7357] [Q&A]
Hello! I'm using the official docker image with the following docker-compose:

```
services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      # Recommended volume for FreshRSS persistent data such as configuration and SQLite databases
      - /storage/rss/data:/var/www/FreshRSS/data
      # Optional volume for storing third-party extensions
      - /storage/rss/extensions:/var/www/FreshRSS/extensions
    ports:
      - "12345:80"
      - "12346:443"
    environment:
      TZ: America/New_York
      # Cron job to refresh feeds at specified minutes
      CRON_MIN: '2,32'
      # 'development' for additional logs; default is 'production'
      FRESHRSS_ENV: development
      FRESHRSS_USER: |-
        --api-password ${FRESH_RSS_ADMIN_API_PASSWORD}
        --email ${ADMIN_EMAIL}
        --language en
        --password ${ADMIN_PASSWORD}
        --user admin
  freshrss-db:
    image: postgres:alpine
    hostname: 'freshrss-postgres'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
      - POSTGRES_USER=user
    restart: always
    volumes:
      - /storage/rss/database:/var/lib/postgresql/data
    ports:
      - 12347:5432
```

I have a CNAME set up in cloudflare for rss.example.com. I also have my rss.example.com entry set up in NGINX Proxy Manager, with its protocol set to HTTP and the correct internal IP/port set. I can confirm that Fresh RSS is in fact working behind the reverse proxy; if I use a browser to go to rss.example.com, the web version of FreshRSS works just fine. I can log in and use it normally.

I'm trying to set up FeedMe on my phone, since I'm primarily going to be using my phone to look at my feeds and would like to have a dedicated app for it. But when I try to connect to FreshRss and send it my API password/username through FeedMe's ui, it says "Authentication error or expired."

If I then go to the API log in /data/users/_ all I see is the following:

```
Sat, 22 Feb 2025 17:35:06 -0500] [warning] --- GReaderAPI::unauthorized
[Sat, 22 Feb 2025 17:35:06 -0500] [debug] --- GReaderAPI::unauthorized Array
(
    [date] => 2025-02-22T17:35:06-05:00
    [headers] => Array
        (
            [Host] => rss.example.com
            [X-Forwarded-Scheme] => https
            [X-Forwarded-Proto] => https
            [X-Forwarded-For] => MY_IP_ADDRESS
            [X-Real-IP] => IP_ADDRESS
            [cf-ray] => IDK if I should obscure this so I am
            [cf-visitor] => {"scheme":"https"}
            [cdn-loop] => cloudflare; loops=1
            [accept-encoding] => gzip, br
            [cf-ipcountry] => US
            [user-agent] => FeedMe/3.16 (com.seazon.feedme; build:206; Android SDK 35)
            [cf-connecting-ip] => PHONE_IP_ADDRESS
        )

    [_SERVER] =>
    [_GET] => Array
        (
            [output] => json
        )

    [_POST] => Array
        (
        )

    [_COOKIE] => Array
        (
        )

    [INPUT] =>
)
```

When I look at other issues on this project, I see a LOT more information in that [_SERVER] tag, but I have no idea how to get it to show up here. My environment in config.php is set to development so I'm not sure why I'm not seeing more in these logs.

If I navigate to http://rss.example.com/api, the Google Reader section reads:

`WARN: Probable invalid base URL in ./data/config.php`

If I go look at config.php, I can see that my base_url is set to http://rss.example.com. 

I'm really not sure what to do from here, so I figured I'd post to ask for help.

**Comment by Alkarex** [comment]
Hello,
The most likely is that your nginx config is wrong, for instance by not forwarding the `Authorization` HTTP header.

For debugging, try the first following commands manually using cURL:
https://freshrss.github.io/FreshRSS/en/developers/06_GoogleReader_API.html#google-reader-compatible-api

**Reply by Landrin201** [reply]
I've run the first few commands in several ways, I'm seeing wildly differing results each time.

1. On my windows machine, same network as the server, running via powershell: I get a 301 Permanently Moved for the first command, curl 'http://freshrss.example.net/api/greader.php/accounts/ClientLogin?Email=alice&Passwd=Abcdef123456'
Quick edit: Adding the -L flag caused this to start working, I now get an SID and Auth token when curling from both my windows machine and the machine the container is hosted on. 

2. Same as 1, except using Chrome to just hit the http address: works fine, gives me an auth token

3. Same as 1, but running the second command using the token I was given by 2: Works fine, gives me a bunch of info on subscriptions. 

4. On the same machine as the docker instance running my FreshRss container: same as 1, a 301. 

I clearly have something wrong in my setup but I'm stumped as to what, any ideas?

Second edit: You were right, I grabbed an app to run these off my phone and when I did the second URL returned Unauthorized. I re-configured the proxy and now when I run the second command

curl -s -H "Authorization:GoogleLogin auth=alice/8e6845e089457af25303abc6f53356eb60bdb5f8" \
  'https://freshrss.example.net/api/greader.php/reader/api/0/subscription/list?output=json'
  
  From my phone I am receiving an actual response.

But, I'm still having trouble with FeedMe; when I put the API link and my username/pass into it, it's still showing Auth Failed. So I'm going to keep digging on what may be wrong there, but I suspect it's nothing to do with FreshRSS itself. Thanks for the help!

**Reply by Landrin201** [reply]
Ok, it's been a few days, but I've tried to get this set up again and I'm still having problems. I'm genuinely pretty stumped about how to get this set up behind my reverse proxy, everything I've tried so far has failed. I have repeatedly tried what I said in the above comment, with multiple different setups in my reverse proxy, and every single one has failed. I've read at least a dozen different threads that all said different things, tried all of them, and failed.

I feel like I'm completely missing something here, this is crazy.

Here's my docker compose: 
```
services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      # Recommended volume for FreshRSS persistent data such as configuration and SQLite databases
      - /storage/rss/data:/var/www/FreshRSS/data
      # Optional volume for storing third-party extensions
      - /storage/rss/extensions:/var/www/FreshRSS/extensions
    ports:
      - "12345:80"
      - "12346:443"
    environment:
      TZ: America/New_York
      # Cron job to refresh feeds at specified minutes
      CRON_MIN: '2,32'
      # 'development' for additional logs; default is 'production'
      FRESHRSS_ENV: development
      FRESHRSS_USER: |-
        --api-password ${FRESH_RSS_ADMIN_API_PASSWORD}
        --email ${ADMIN_EMAIL}
        --language en
        --password ${ADMIN_PASSWORD}
        --user admin
  freshrss-db:
    image: postgres:alpine
    hostname: 'freshrss-postgres'
    environment:
      - POSTGRES_PASSWORD={db_pass}
      - POSTGRES_DB={db_db}
      - POSTGRES_USER={db_admin}
    restart: always
    volumes:
      - /storage/rss/database:/var/lib/postgresql/data
    ports:
      - 12348:5432
```

The web UI works perfectly, no matter where I access it from. The problem I have is *strictly* with the API. 

Honestly the biggest problem, by far, is that *I cannot get any useful logging.* I don't know if that means that the auth header isn't getting through, or if something else is wrong, but *every single log I get* looks different from what other people post. ALL of my logs, no matter what settings I change,  look exactly the same as what I posted in my OP. I cannot get the [_SERVER] header for ANY users to print ANYTHING. 

Here's what I did in my most recent attempt:

1. In nginx proxy manager, make a new proxy host for `rss.example.com`. Set the domain name, scheme = http, ip = ip_addr, forwarded port = 12345 (I set all my apps behind custom ports, I have several applications exposed on this machine so I can't just give it port 80)
2. Under "Advanced" paste the following, which I got from this thread https://github.com/FreshRSS/FreshRSS/discussions/6183 : 
``` 
location /rss-reader/ {
    proxy_pass http://rss.example.com/;
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-XSS-Protection "1; mode=block";
    proxy_redirect off;
    proxy_buffering off;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Prefix /rss-reader/;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header Remote-User $remote_user;
    proxy_read_timeout 90;

    # Do Authorization
    auth_basic "Password Required";
    auth_basic_user_file /storage/rss/users;

    # Forward the Authorization header for the Google Reader API
    proxy_set_header Authorization $http_authorization;
    proxy_pass_header Authorization;
}
        
location ^~ /rss-reader/api/ {
    proxy_pass http://rss.example.com/api/;
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-XSS-Protection "1; mode=block";
    proxy_redirect off;
    proxy_buffering off;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Prefix /rss-reader/;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header Remote-User $remote_user;
    proxy_read_timeout 90;

    # Do not do Authorization
    auth_basic off;

    # Forward the Authorization header for the Google Reader API
    proxy_set_header Authorization $http_authorization;
    proxy_pass_header Authorization;
}
```

Every time I hit this url: 
`http://rss.example.com/api/greader.php/accounts/ClientLogin?Email=alice&Passwd=Abcdef123456`
I get a response with an SID and Auth, I'm assuming that's the auth token since it looks like one.

If I then hit the following:
`https://rss.example.com/api/greader.php/reader/api/0/subscription/list?output=json`

And I add a header: `Authorization=GoogleLogin`
And a second header: `auth= the auth token I got from the first URL`

I just get "unauthorized." I don't get any other information. It just says "Unauthorized" in the response. When I look at the log, I see a log identical to this:

```
[Sun, 02 Mar 2025 22:17:09 -0500] [debug] --- GReaderAPI::unauthorized Array
(
    [date] => 2025-03-02T22:17:09-05:00
    [headers] => Array
        (
            [Host] => rss.example.com
            [X-Forwarded-Scheme] => https
            [X-Forwarded-Proto] => https
            [X-Forwarded-For] => 2600:1003:b1b1:3fa0:2051:304:c24b:ee92
            [X-Real-IP] => 172.70.42.79
            [cf-ray] => 91a5faae0aed3b18-IAD
            [cf-connecting-ip] => 2600:1003:b1b1:3fa0:2051:304:c24b:ee92
            [accept] => */*
            [accept-encoding] => gzip, br
            [cf-ipcountry] => US
            [cdn-loop] => cloudflare; loops=1
            [user-agent] => Teste Android/7.6.1(652)
            [cf-visitor] => {"scheme":"https"}
        )

    [_SERVER] =>
    [_GET] => Array
        (
            [output] => json
        )

    [_POST] => Array
        (
        )

    [_COOKIE] => Array
        (
        )

    [INPUT] =>
) 
```


If, in nginx proxy manager, I change the protocol to HTTPS, and change the port to 12346, instead I just get a BadGateway from literally every single endpoint. I don't even get an auth token in the first place.

I'm at a complete loss here. All of what I wrote above has been 100% identical no matter what configuration I try. I've never encountered anything like this with any of the other apps I self host, I'm starting to get kinda frustrated with this. Any help would be greatly appreciated, I'd like to be able to use this on my phone via an actual app rather than the web browser.
