### DISCUSSION TITLE
Mastodon: too short titles

### DISCUSSION THREAD

**Discussion by davemosk** [FreshRSS/FreshRSS#7525] [Q&A] [answered]
### Is your feature request related to a problem? Please describe.

This is how my list looks in FreshRSS Normal View, using the Origine template with "Full Width" content width. I'd like the title to be a lot wider.  The Title Wrap extension doesn't seem to help, and I can't seem to get the CSS to expand it either.  

![Image](https://github.com/user-attachments/assets/9c4b2e37-1465-47b6-bb10-ec9502a04646)

### Describe the solution you’d like

Ideally, in Full Width (as well as other) view the title should expand out to the full width available.  Failing that, I'd appreciate it if someone could tell me what custom CSS I need to put in to exhibit this behaviour.

**Comment by Frenzie** [comment]
The Title Wrap extension doesn't? I'm still using my original CSS that served as inspiration and that seems to have no issues with it (but beware, it's not 100% perfect on the latest FreshRSS). See https://github.com/FreshRSS/FreshRSS/issues/2344#issuecomment-480271415
![Image](https://github.com/user-attachments/assets/ab42c833-63dd-499c-9254-00bfd9247d4f)

This is what I'm currently using:
```css

.flux .flux_header .item.website .websiteName,
.flux .flux_header .item .title {
	white-space: wrap;
}

.flux .flux_header .item .summary {
	margin-top: -0.5rem;
}

.flux:not(.current):hover .flux_header .item .date {
	opacity: inherit;
}

.flux:not(.current):hover .flux_header .item .title:has(~ .date) {
	padding-right: 155px;
	z-index: auto;
}

@media (max-width: 840px) {
	.flux:not(.current) .flux_header .item.titleAuthorSummaryDate .title:has(~ .date),
	.flux:not(.current):hover .flux_header .item.titleAuthorSummaryDate .title:has(~ .date) {
		padding-right: 0;
		padding-left: 0;
	}
}
```
