### ISSUE TITLE
Any possibility to hide the failure icon for nonworking rss feeds?

### ISSUE THREAD

**Issue by proxforge** [FreshRSS/FreshRSS#2107]
Any possibility to hide the failure icon for nonworking rss feeds?

**Comment by Frenzie** [comment]
You could add some custom CSS with:

```css
.category .title.error::before {content:none}
```

That's with https://github.com/FreshRSS/Extensions/tree/master/xExtension-CustomCSS
