### ISSUE TITLE
Multiline titles

### ISSUE THREAD

**Issue by tiborepcek** [FreshRSS/FreshRSS#2344]
Hi, i would like to ask, if there is some option to enable multiline titles in RSS feeds, so that i can read the whole (long) title of an article. Thank you.

**Comment by Frenzie** [comment]
Not presently, but it may not be too hard to do with some custom CSS. I think I may have once said I'd look into it but I never found the time to.

Part of the problem is that there's no colspan in CSS display:table, so instead a different approach like flexbox needs to be used. A problem in the sense that you probably need at least a good hour to play around with it, not in the sense that it's particularly difficult.

**Comment by Frenzie** [comment]
Quick proof of concept that doesn't look half-bad:

```css
.horizontal-list{display:flex;flex-wrap:wrap}
.flux .item > a {white-space:normal}
.flux:not(.current):hover .item.title {position:relative;max-width:inherit}
.item:last-child{margin-left:auto}
```

![Screenshot_2019-04-04_15-04-37](https://user-images.githubusercontent.com/202757/55557817-fab4ce00-56ea-11e9-8e76-caff1c77665e.png)

**Comment by aledeg** [comment]
See  #1938

**Comment by tiborepcek** [comment]
> Quick proof of concept that doesn't look half-bad:
> 
> ```css
> .horizontal-list{display:flex;flex-wrap:wrap}
> .flux .item > a {white-space:normal}
> .flux:not(.current):hover .item.title {position:relative;max-width:inherit}
> .item:last-child{margin-left:auto}
> ```

Thanks @Frenzie , it works via [Custom CSS](https://github.com/FreshRSS/Extensions/tree/master/xExtension-CustomCSS) user extension on desktop and on mobile too.

**Comment by aledeg** [comment]
Maybe you could add a PR on the extension repository to add your snippet as a tip for other users.

**Comment by Frenzie** [comment]
Not that quick 10 minute proof of concept. But with another 15 minutes, the result is probably about right:

```css
.horizontal-list {
 display: flex;
 /* uncomment to allow title to expand onto its own line */
 /*flex-wrap: wrap;*/
}
.horizontal-list.bottom {
 display: table;
}
.flux .item {
 flex-shrink: 0;
 line-height: normal;
 padding: .3em 0;
}
.flux .item > a {
 white-space: normal;
}
.flux:not(.current):hover .item.title {
 position: relative;
 max-width: inherit;
}
.flux_header .title {
 flex: auto;
}
```

<img width=45% src=https://user-images.githubusercontent.com/202757/55630197-682d3100-57b5-11e9-8fc1-337dd4da2149.png><img width=45% src=https://user-images.githubusercontent.com/202757/55630196-67949a80-57b5-11e9-9c68-82cb89500b55.png>

<img width=45% src=https://user-images.githubusercontent.com/202757/55630188-619eb980-57b5-11e9-82a2-69915e22ae78.png><img width=45% src=https://user-images.githubusercontent.com/202757/55630209-6f543f00-57b5-11e9-834d-d24b207ae774.png>

<img width=45% src=https://user-images.githubusercontent.com/202757/55630212-724f2f80-57b5-11e9-9e5c-522af87eedb2.png><img width=45% src=https://user-images.githubusercontent.com/202757/55630189-619eb980-57b5-11e9-841c-d27d7b936f9e.png>
