### ISSUE TITLE
Feeds are not (or very slow) updating

### ISSUE THREAD

**Issue by smartens83** [FreshRSS/FreshRSS#2529]
Hey there,

I have an issue with my dockerized FreshRSS installation.
I'm coming from TTRSS and have installed FreshRSS as an alternative to another server for testing.
But one think that occurs to me is, that FreshRSS doesn't update my feeds, or updates them very slow. After half an hour, I have 20 Feeds in my TTRSS installation and 5 in my FreshRSS installation.
My Docker File looks like this:
```
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    network_mode: "bridge"
    restart: unless-stopped
    ports:
      - "80"
    volumes:
      - '/path/to/my/freshrss/data:/var/www/FreshRSS/data'
    environment:
      - CRON_MIN=*/5
      - TZ=Europe/Berlin
```

I've also tried to update my feeds manually like described here: https://github.com/FreshRSS/FreshRSS/tree/master/Docker#option-2-cron-on-the-host-machine
The log file says:
```
Starting feed actualization at 2019-09-18T10:36:02+02:00
FreshRSS[1342]: FreshRSS Start feeds actualization...
Actualize the_lux...
Done.
Ending feed actualization at 2019-09-18T10:36:02+02:00
Feed actualizations took 0 day(s), 0 hour(s), 0 minute(s) and 0 seconds for 1 users
Results:
the_lux OK
End.
FreshRSS[1342]: FreshRSS feeds actualization done.
```
But nothing was actually updated. And I don't think it actually updated anything. I have round about 60 - 80 Feeds in my installation. I don't think it checked everyone of them in no time.

Here are a few Feeds, that FreshRSS didn't updated when TTRSS updated them:
http://konsolenschnaeppchen.de/feed/
https://www.googlewatchblog.de/feed/
http://feeds2.feedburner.com/stadt-bremerhaven/dqXM
http://www.heise.de/newsticker/heise-atom.xml

I don't know where to look now. Maybe someone is able to help me? 
If you need more information, please ask.

And thanks in regards for looking into my problem :-)
