### ISSUE TITLE
Database configuration error when deploy with docker compose

### ISSUE THREAD

**Issue by fakegit** [FreshRSS/FreshRSS#2547]
Follow https://github.com/FreshRSS/FreshRSS/blob/master/Docker/README.md

My docker compose config file:
```
version: '2.3'

services:
  freshrss-postgresql:
    image: postgres:latest
    restart: unless-stopped
    volumes:
    - 'pgsql-data:/var/lib/postgresql/data'
    environment:
    - POSTGRES_USER=freshrss
    - POSTGRES_PASSWORD=xxxxxx
    - POSTGRES_DB=freshrss

  freshrss:
    image: freshrss/freshrss:latest
    restart: unless-stopped
    ports:
      - "1201:80"
    depends_on:
      - freshrss-postgresql
    networks:
      - freshrss-network
    volumes:
      - 'freshrss-data:/var/www/FreshRSS/data'
    environment:
      - CRON_MIN=*/20

networks:
  freshrss-network:
    external: true

volumes:
  pgsql-data:
    external: true
  freshrss-data:
    external: true
```
everything works fine until website install step 3: Database configuration

I tried "Host" with localhost, 127.0.0.1, 172.21.0.2(freshrss-postgresql container's network ip), freshrss-postgresql, even my server ip, none of them work.

- localhost:
> Blast! Verify your database information. : SQLSTATE[08006] [7] could not connect to server: Connection refused Is the server running on host "localhost" (127.0.0.1) and accepting TCP/IP connections on port 5432? could not connect to server: Cannot assign requested address Is the server running on host "localhost" (::1) and accepting TCP/IP connections on port 5432?
- 127.0.0.1:
> Blast! Verify your database information. : SQLSTATE[08006] [7] could not connect to server: Connection refused Is the server running on host "127.0.0.1" and accepting TCP/IP connections on port 5432?
- 172.21.0.2:
> Blast! Verify your database information. : SQLSTATE[08006] [7] timeout expired
- freshrss-postgresql:
> Blast! Verify your database information. : SQLSTATE[08006] [7] could not translate host name "freshrss-postgresql" to address: Name or service not known
- server ip:
> Blast! Verify your database information. : SQLSTATE[08006] [7] could not connect to server: Connection refused Is the server running on host "my server ip" and accepting TCP/IP connections on port 5432?

**Comment by Alkarex** [comment]
Hello @fakegit 
This is because your PostgreSQL database is not on the same network than FreshRSS. Please try the docker-compose file below with an additional line to fix your problem:

```yaml
version: '2.3'

services:
  freshrss-postgresql:
    image: postgres:latest
    restart: unless-stopped
    networks:
      - freshrss-network
    volumes:
      - 'pgsql-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=freshrss
      - POSTGRES_PASSWORD=xxxxxx
      - POSTGRES_DB=freshrss

  freshrss:
    image: freshrss/freshrss:latest
    restart: unless-stopped
    ports:
      - "1201:80"
    depends_on:
      - freshrss-postgresql
    networks:
      - freshrss-network
    volumes:
      - 'freshrss-data:/var/www/FreshRSS/data'
    environment:
      - CRON_MIN=*/20

networks:
  freshrss-network:
    external: true

volumes:
  pgsql-data:
    external: true
  freshrss-data:
    external: true
```
