### ISSUE TITLE
Docker & nginx-proxy: empty feed contents in Vienna RSS

### ISSUE THREAD

**Issue by mipmip** [FreshRSS/FreshRSS#2573]
I could not get ViennaRSS working together with FreshRSS, So I debugged both
until I found the problem.

I don't know if this is a known bug or configuration issue, but I could not
find any useful information in the online documentation. I guess my journey
could be helpful for someone.

## Problem summary

When I sync in Vienna it shows new items in the feed list labels, but the tableviews with entries are empty.

![image](http://picdrop.t3lab.com/v69u7Wt7a1.png)

## Problem details

The problem I found was that the SERVER information is formatted in a way FreshRSS cannot extract the correct feed URL. Here's an example:

This is the request made by Vienna RSS:

```
2019-10-16 19:19:20.259 Vienna[12334:16603146] req OK: <NSMutableURLRequest: 0x7f8581f801a0> { URL: https://rss.somedomain.net/api/greader.php/reader/api/0/stream/contents/feed/https%3A%2F%2Fwww.reddit.com%2Fuser%2Fmipselaer%2Fm%2Fbrood_bakken%2F.rss?client=ViennaRSS&comments=false&likes=false&ot=1571073548&n=500&ck=1571246359&output=json }
```

This is the $_SERVER info available for FreshRSS:

```
[REQUEST_URI] => /api/greader.php/reader/api/0/stream/contents/feed/https:/www.reddit.com/user/mipselaer/m/brood_bakken/.rss?client=ViennaRSS&comments=false&likes=false&ot=1571073548&n=500&ck=1571246359&output=json
[PATH_INFO] => /reader/api/0/stream/contents/feed/https:/www.reddit.com/user/mipselaer/m/brood_bakken/.rss
```

The part after */feed/* is missing a slash, but even with this slash, FreshRSS cannot extract URL's when normal slashes are used after feed.

TLTR

It causes FreshRSS to search for items beloning to a feed-URL equal to *https*. It should search for a feed equal to *https:/www.reddit.com/user/mipselaer/m/brood_bakken/.rss*.

I created a quick workaround fix:

```php

  # p/api/greader.php line: 973

  if (preg_match('#/reader/api/0/stream/contents/feed/([A-Za-z0-9:\/\'!*()%$_.~+-]+)#', $include_target, $matches) && isset($matches[1])) {
    if(strpos($matches[1], "https://") === false && strpos($matches[1], "https:/") !== false){
      $include_target = str_replace("https:/", "https://", $matches[1]);

    }
    elseif(strpos($matches[1], "http://") === false && strpos($matches[1], "http:/") !== false){
      $include_target = str_replace("http:/", "http://", $matches[1]);
    }
    else{
      $include_target = urldecode($matches[1]);
    }

  } else {
    $include_target = '';
  }
```

If you find this useful, I'm happy to help solving this issue by giving more information.

## Setup

| item                        | version            |
|-----------------------------|--------------------|
| docker host: os             | Debian GNU/Linux 9 |
| docker host: nginx          | 1.10.3             |
| docker host: docker-compose | 1.24.1             |
| docker host: docker         | 17.05.0-ce         |
| docker guest: FreshRSS      | 1.14.3             |
| macos: os                   | Mojave             |
| macos: Vienna RSS           | 3.5.4              |

I installed freshrss with docker-compose. My docker host machine run's nginx for which I added a vhost proxy configuration.

The docker-compose.yml

```
version: '2.3'

services:
  postgresql:
    image: postgres:latest
    restart: unless-stopped
    volumes:
    - '/opt/freshrss/pgsql-data:/var/lib/postgresql/data'
    environment:
    - POSTGRES_USER=freshrss
    - POSTGRES_PASSWORD=SOMETHING
    - POSTGRES_DB=freshrss
  freshrss:
    image: freshrss/freshrss:latest
    restart: unless-stopped
    ports:
    - "8001:80"
    depends_on:
      - postgresql
    networks:
      - default
    volumes:
      - '/opt/freshrss/data:/var/www/FreshRSS/data'
    environment:
      - CRON_MIN=*/20
```

The nginx conf

```
upstream freshrss {
    server 127.0.0.1:8001;
    keepalive 64;
}

server {
    server_name rss.somedomain.net;

    # Needed for Freshrss cookie/session :
    proxy_cookie_path / "/; HTTPOnly; Secure";

    location / {
        proxy_pass http://freshrss/;
        add_header X-Frame-Options SAMEORIGIN;
        add_header X-XSS-Protection "1; mode=block";
        proxy_redirect off;
        proxy_buffering off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_read_timeout 90;

        # Forward the Authorization header for the Google Reader API.
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
    }

    listen 443 ssl http2; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/rss.somedomain.net/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/rss.somedomain.net/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = rss.somedomain.net) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name rss.somedomain.net;
    listen 80;
    return 404; # managed by Certbot
}

```
