### ISSUE TITLE
Can't connect to DB :(

### ISSUE THREAD

**Issue by aashish108** [FreshRSS/FreshRSS#2801]
Hello, I can't connect to the MariaDB DB container. Not sure what is going wrong? I know I can use sqllite but I'd rather figure out why it can't connect, spent hours today trying postgresql/mariadb etc.

Heres my compose, the .env files contains the mentioned variables:

```
version: '3'
services:

  freshrss:
    image: freshrss/freshrss
    restart: unless-stopped
    ports:
      - "${FRESHRSS_PORT}:80"
    volumes:
      - ${FRESHRSS_DATA_FOLDER}:/var/www/FreshRSS/data
    environment:
      - CRON_MIN=*/20
      - TZ=Europe/London
    depends_on:
      - freshrss-db
    networks:
      - freshrss-net

  freshrss-db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: freshrss
      MYSQL_USER: freshrss
      MYSQL_PASSWORD: freshrss
    networks:
      - freshrss-net

networks:  
  trilium-net:
  seafile-net:
  freshrss-net:
```

The error message is:

```
Blast! Verify your database information. : Access to database is denied for `freshrss`: SQLSTATE[HY000] [2002] Connection timed out
```

The host value I input is `freshrss-db`. That should be it! I shouldn't need to do anything else.

Oh and I'm on Synology platform. Running docker as sudo if that matters.

Any help much appreciated!

Cheers!
