### ISSUE TITLE
[Suggestion] Ajout d'un bouton "Menu à droite"

### ISSUE THREAD

**Issue by Balooforever** [FreshRSS/FreshRSS#2805]
Bonjour,

Petite suggestion : Je souhaiterais une option permettant de basculer le menu (aside) sur la droite de l'écran.

Ca ne me semble pas possible en CSS sauf modification lourde. Une modification de l'ordre des div semble suffisant mais je n'ai pas les connaissances nécessaires pour l'implémenter ..

Merci

**Comment by Alkarex** [comment]
Bonjour,
Est-ce pour utiliser une langue droite-vers-gauche ?

Si, cela devrait pouvoir se faire en CSS. Petit exemple rapide, loin d'être parfait : 

```css
#aside_feed {
	position: absolute;
	right: 0;
}
#stream {
	width: calc(100% - 300px);
}
```
