### ISSUE TITLE
Login fails on docker instance and posts cannot be marked as read.

### ISSUE THREAD

**Issue by Twilek-de** [FreshRSS/FreshRSS#2918]
I run Freshrss on Docker with a sqlite database. I have recreated the container with a new image and now it displays the articles. I cannot login, as it says "password missmatch" in the logs. Posts are not marked as read when opened and when I try to manually mark them as read I get a 404 error. I had the same error some days ago but restarting the container fixed it. Now I cannot get it to work. I checked the sqlite database for corruption but it is ok. Turning off Authorization does not help. Posts can not be marked read.

**Comment by Alkarex** [comment]
Hello,
Can you show your `docker run` or `docker-compose` command / configuration?

**Comment by Twilek-de** [comment]
docker run -d --restart unless-stopped --log-opt max-size=10m -v /opt/docker-freshrss/data:/var/www/FreshRSS/data -v /opt/docker-freshrss/extensions:/var/www/FreshRSS/extensions -e 'CRON_MIN=*/20' -e TZ=Europe/Berlin -p 127.0.0.1:9797:80  --name freshrss freshrss/freshrss

I then use Apache to proxy it with https.

**Comment by Alkarex** [comment]
This sounds like a write access problem.
Can you check:

```sh
ls -alh /opt/docker-freshrss/data/
```

**Comment by Alkarex** [comment]
Then try:

```sh
sudo docker exec freshrss chown www-data:www-data -R data/
```

**Comment by Twilek-de** [comment]
I had thought of that and raised the perimissions. I think it is a problem wirh the proxy. When I bind to 0.0.0.0 and connect without https it works. What is strange is that it worked with the proxy for weeks and I am not aware that I changed something with apache.

```
Here is the output:
 ls -alh /opt/docker-freshrss/data/
insgesamt 60K
drwxrwxrwx 9 root     www-data 4,0K Apr 20 16:28 .
drwxrwxrwx 4 root     root     4,0K Apr 10 16:30 ..
drwxrwxrwx 2 root     www-data 4,0K Apr 20 16:40 cache
-rwxrwxrwx 1 www-data www-data 1,6K Apr 20 16:28 config.php
-rwxrwxrwx 1 www-data www-data 1,6K Apr 10 17:56 config.php.bak.php
drwxrwxrwx 2 root     www-data 4,0K Apr 10 16:39 extensions-data
drwxrwxrwx 2 root     www-data 4,0K Apr 10 16:46 favicons
drwxrwxrwx 2 root     www-data 4,0K Apr 10 16:39 fever
-rwxrwxrwx 1 root     www-data  174 Apr 20 17:59 .htaccess
-rwxrwxrwx 1 root     www-data    0 Apr 20 17:59 index.html
-rwxrwxrwx 1 www-data www-data    3 Apr 10 16:41 last_update.txt
drwxrwxrwx 4 root     www-data 4,0K Apr 10 16:39 PubSubHubbub
drwxrwxrwx 2 root     www-data 4,0K Apr 20 16:27 tokens
-rwxrwxrwx 1 www-data www-data 6,3K Apr 10 16:41 update.php
drwxrwxrwx 4 root     www-data 4,0K Apr 10 16:41 users
```

**Comment by Twilek-de** [comment]
I have set my Apache proxy like that and it used to work

```
  ProxyPreserveHost On
  ProxyPass /fr/ http://127.0.0.1:9797/
  ProxyPassReverse /fr/ http://127.0.0.1:9797/
  RequestHeader set X-Forwarded-Proto "https"

```

**Comment by Twilek-de** [comment]
Might this be related to this (https://github.com/FreshRSS/FreshRSS/issues/2671) ?

**Comment by Alkarex** [comment]
Yes, sounds related. That issue went under my radar.

Try first without proxy to check whether it works (not related to your problem, but when you are done changing your public address, remember to update `base_url` in `data/config.php`).

I have not tried this config, but you need to ensure that e.g. cookies are also forwarded properly (I have not checked the Apache doc for proxying recently).

It should of course be possible to get an Apache proxy config to work (I will try to have a look when I find time), but I suggest [Traefik](https://docs.traefik.io/) as a better alternative. It is a dedicated proxy with built-in Docker support, auto-renewal of HTTPS certificates, and is less error prone than nginx or even Apache. In [our doc](https://github.com/FreshRSS/FreshRSS/tree/master/Docker) we explain how to use Traefik 1.x, but I need to find time to update it to Traefik 2.x. If you are interested in giving it a try, let me know and I will then update our docs shortly. Here is already some substance for Traefik 2.x:

`traefik-tls.yml`:

```yml
tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
```

`docker-compose.yml`

```yml
version: "2"

networks:
  traefik-network:
    external:
      name: traefik-network

services:
  traefik:
    image: traefik:2.1
    container_name: traefik
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    ports:
      - 443:443
    networks:
      traefik-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/ssd/docker/volumes/traefik-tmp:/tmp
      - /mnt/ssd/docker/volumes/traefik-letsencrypt:/etc/traefik/acme
      - /mnt/ssd/RaspberryPi/traefik-tls.yaml:/etc/traefik/traefik-tls.yaml:ro
    command:
      - --global.sendAnonymousUsage
      - --accesslog=true
      - --api=true
      - --providers.docker=true
      - --log.level=INFO
      - --entryPoints.https.address=:443
      - --certificatesResolvers.letsEncrypt.acme.storage=/etc/traefik/acme/acme.json
      - --certificatesResolvers.letsEncrypt.acme.email=your-name@example.net
      - --certificatesResolvers.letsEncrypt.acme.tlsChallenge=true
      - --providers.file.filename=/etc/traefik/traefik-tls.yaml
    labels:
      - traefik.http.middlewares.traefikM0.basicauth.users=admin:$$2y$$05$$R3--a-hashed-password
      - traefik.http.middlewares.traefikM1.compress=true
      - traefik.http.middlewares.traefikM2.headers.forceSTSHeader=true
      - traefik.http.middlewares.traefikM2.headers.stsSeconds=31536000
      - traefik.http.routers.api.middlewares=traefikM0,traefikM1,traefikM2
      - traefik.http.routers.api.entryPoints=https
      - traefik.http.routers.api.rule=Host(`traefik.example.net`)
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certResolver=letsEncrypt
      - traefik.http.routers.api.service=api@internal

  freshrss:
    image: freshrss/freshrss:arm
    container_name: freshrss
    restart: unless-stopped
    depends_on:
      - traefik
    logging:
      options:
        max-size: 10m
    networks:
      traefik-network
    volumes:
      - /mnt/ssd/git/FreshRSS:/var/www/FreshRSS
      - /mnt/ssd/docker/volumes/freshrss-data:/var/www/FreshRSS/data
      - /mnt/ssd/docker/volumes/freshrss-extensions:/var/www/FreshRSS/extensions
    environment:
      - CRON_MIN=4,34
      - TZ=Europe/Paris
    labels:
      - traefik.http.middlewares.freshrssM1.compress=true
      - traefik.http.middlewares.freshrssM2.headers.forceSTSHeader=true
      - traefik.http.middlewares.freshrssM2.headers.stsSeconds=31536000
      - traefik.http.routers.freshrss.middlewares=freshrssM1,freshrssM2
      - traefik.http.routers.freshrss.entryPoints=https
      - traefik.http.routers.freshrss.rule=Host(`freshrss.example.net`)
      - traefik.http.routers.freshrss.tls=true
      - traefik.http.routers.freshrss.tls.certResolver=letsEncrypt
```

![image](https://user-images.githubusercontent.com/1008324/79776171-9edcd780-8335-11ea-8a49-e6639e3a08d6.png)
