### ISSUE TITLE
Docker: high cron cpu load / wrong container time

### ISSUE THREAD

**Issue by jdckr** [FreshRSS/FreshRSS#2939]
Hi,
after updating my container to the newest version I am observing high cron cpu load.
When checking the container logs, the containers time looks really strange:
```
Result: success,
[Sun Jan 00 00:00:00.000000 1900] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations,
[Sat Feb 28 23:30:43.('''0( 1931] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND',
127.0.0.1 - - [04/May/1935:08:04:11 +0100] "GET /i/ HTTP/1.0" 200 5744 "-" "-", 
```
This does not happen when deploying freshrss/fresshrss:1.16.0-arm
```
Result: success,
[Sat May 02 12:14:34.769286 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations,
[Sat May 02 12:14:34.769433 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND',
127.0.0.1 - - [02/May/2020:12:15:01 +0200] "GET /i/ HTTP/1.0" 200 5681 "-" "-",
```

**Comment by Alkarex** [comment]
Hello,
So the date is wrong?
~~Which tag, more precisely? `freshrss/freshrss:latest` on `amd64`?~~ Edit: sorry, you already wrote it

**Comment by Alkarex** [comment]
Could you please show your `docker run` or `docker-compose` ?

**Comment by jdckr** [comment]
My `docker-compose` looks like this:
```yaml
version: "3"
services:
  freshrss:
    container_name: freshrss
    image: freshrss/freshrss:1.16.0-arm
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - /home/pi/freshrss/data:/var/www/FreshRSS/data
    environment:
      - CRON_MIN='*/20'
      - TZ=Europe/Berlin
```
