### ISSUE TITLE
(98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80

### ISSUE THREAD

**Issue by McMac** [FreshRSS/FreshRSS#3341]
Trying to run the latest docker image on my docker but can't start it. docker logs isn't showing much more than that. I have IPv6 exposed to the docker containers. Is it to try to listen to IPv6:80 and then fails to listen via IPv4:80?

```
(98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs
Result: success
```

My docker-compose:

```yaml
version: "2.4"
services:
  freshrss:
    image: freshrss/freshrss
    container_name: freshrss
    environment:
      - PUID=1031
      - PGID=100
      - TZ=Europe/Zurich
    volumes:
      - /volume1/docker/freshrss/data:/var/www/FreshRSS/data
    ports:
      - 8180:80
    network_mode: host
    restart: unless-stopped
```

Idea is to launch this, then go in and modify the config to point to a running mysql instance on my Synology instead of a db in a container. Stuck as it won't launch and keeps restarting.

**Comment by Alkarex** [comment]
Hello,
As you are trying `network_mode: host`, make sure you do not have anything else on your server that runs on port 80 while testing:

```sh
sudo netstat -ltpn
```

When experimenting a setup for the first time, please use our latest stable release, e.g. `freshrss/freshrss:1.17.0` to simplify the tests.

**Comment by Alkarex** [comment]
In Docker, published ports are discarded when using host network mode.

To run FreshRSS in `network_mode: host` together with another service running natively on the host also on port 80, I think the cleanest would be for us to provide an environment variable to change the Apache port:

https://github.com/FreshRSS/FreshRSS/blob/85cbfcedb50b3a579d13697b4ec27c87450f68a7/Docker/FreshRSS.Apache.conf#L2

**Comment by Alkarex** [comment]
Suggestion implemented in https://github.com/FreshRSS/FreshRSS/pull/3343

**Comment by Alkarex** [comment]
@McMac You should be able to try the following:

```sh
docker-compose pull
```

```yml
version: "2.4"
services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    logging:
      options:
        max-size: 10m
    network_mode: host
    volumes:
      - /volume1/docker/freshrss/data:/var/www/FreshRSS/data
    environment:
      - CRON_MIN=5,35
      - TZ=Europe/Zurich
      - LISTEN=0.0.0.0:8180
```
