### ISSUE TITLE
[Docker] Permission is denied for..

### ISSUE THREAD

**Issue by beloso** [FreshRSS/FreshRSS#3382]
I am running FreshRSS via Docker using the official image.
I am constantly getting the following error:

```
### Application problem ###
Permission is denied for `/var/www/FreshRSS/data/users/username/log.txt`
```
If I run `sudo chown -R username:docker freshrss/` it works for a while, but it stops working after a while.

My docker compose looks like this:

```
  # FreshRSS - RSS Feed
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik_proxy
    ports:
      - $FRESHRSS_PORT:80
    depends_on:
      - "mariadb"
    volumes:
      - $DOCKERDIR/freshrss/data:/var/www/FreshRSS/data
      - $DOCKERDIR/freshrss/extensions:/var/www/FreshRSS/extensions
    environment:
      - CRON_MIN=*/20
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
```

**Comment by beloso** [comment]
If there is anything else I can do to troubleshoot this, please let me know.

**Comment by aledeg** [comment]
Are you running it on Linux? If so do you have SELinux enabled?

**Comment by beloso** [comment]
My host is Ubuntu 20.04.
I don't think I have SELinux enabled:

```
~/docker$ getenforce

Command 'getenforce' not found, but can be installed with:

sudo apt install selinux-utils

---
 
~/docker$ sestatus

Command 'sestatus' not found, but can be installed with:

sudo apt install policycoreutils
```

But I may not be looking at the proper place

**Comment by aledeg** [comment]
My first thought was that SELinux reverted the permissions you've set.
Have you used FreshRSS with the command line also? The command line user may have different right than the webserver user.

**Comment by Alkarex** [comment]
I have just fixed a maybe related issue on https://github.com/FreshRSS/FreshRSS/pull/3377
P.S. Only when trying to log in with a non-existing user

**Comment by Alkarex** [comment]
@beloso You observe this error with your own user, right?
Is there any else making changes to `$DOCKERDIR/freshrss/data` ?
Try to check the permissions with `ls -alh` when you observe the error, and post the results

**Comment by Alkarex** [comment]
And also show the permissions for the same folder from within Docker, like

```sh
docker exec freshrss ls -alh data/users/username/
```

**Comment by beloso** [comment]
I am unsure of what fixed it. If @Alkarex or me meddling in my file ownerships, but I am not experiencing this issue anymore.

I'll close this issue as I don't believe there is anything else to be done regarding this.
Thank you for your support. And thank you for your work on this project.

**Comment by beloso** [comment]
@Alkarex @aledeg The error happened again, the permissions on the `data/users/username/` folder were:

Host: 
```
drwxrwxr-x+ 2 beloso beloso 4.0K Jan 13 11:25 .
drwxrwx---+ 4 beloso beloso 4.0K Jan 11 11:56 ..
-rw-rw-r--+ 1 beloso beloso 2.5K Jan 22 11:57 config.php
-rw-rw-r--+ 1 beloso beloso 2.5K Jan 13 11:25 config.php.bak.php
-rw-rw-r--+ 1 beloso beloso 9.0K Jan 22 11:56 log.txt
```

Container:
```
drwxrwxr-x+ 2 1000 1000 4.0K Jan 13 11:25 .
drwxrwx---+ 4 1000 1000 4.0K Jan 11 11:56 ..
-rw-rw-r--+ 1 1000 1000 2.5K Jan 22 11:57 config.php
-rw-rw-r--+ 1 1000 1000 2.5K Jan 13 11:25 config.php.bak.php
-rw-rw-r--+ 1 1000 1000 9.0K Jan 22 11:56 log.txt
```

I checked the logs for FreshRSS and found: 
```
freshrss         | 2021-01-22T11:56:07.310131121Z [Fri Jan 22 11:56:07.310070 2021] [php7:error] [pid 136] [client 141.101.107.55:0] PHP Fatal error:  Uncaught Minz_PermissionDeniedException: Permission is denied for `/var/www/FreshRSS/data/users/_/log_api.txt` in /var/www/FreshRSS/lib/Minz/Log.php:75\nStack trace:\n#0 /var/www/FreshRSS/lib/Minz/Log.php(136): Minz_Log::record('Invalid API aut...', 4, '/var/www/FreshR...')\n#1 /var/www/FreshRSS/p/api/greader.php(168): Minz_Log::warning('Invalid API aut...', '/var/www/FreshR...')\n#2 /var/www/FreshRSS/p/api/greader.php(939): authorizationToUser()\n#3 {main}\n  thrown in /var/www/FreshRSS/lib/Minz/Log.php on line 75
freshrss         | 2021-01-22T11:56:07.310200520Z 141.101.107.55 - - [22/Jan/2021:11:56:07 +0000] "POST /api/greader.php/reader/api/0/edit-tag HTTP/1.1" 500 - "-" "Reeder/5000.49.04 CFNetwork/1209.1 Darwin/20.2.0"
```

I tried to simply restart the container, and it worked. However, the file permissions changed.

Host:
```
drwxrwxr-x+ 2 beloso www-data 4.0K Jan 13 11:25 .
drwxrwx---+ 4 beloso www-data 4.0K Jan 11 12:06 ..
-rw-rw-r--+ 1 beloso www-data 2.5K Jan 22 11:57 config.php
-rw-rw-r--+ 1 beloso www-data 2.5K Jan 13 11:25 config.php.bak.php
-rw-rw-r--+ 1 beloso www-data 9.0K Jan 22 12:00 log.txt
```

Container:
```
drwxrwxr-x+ 2 1000 www-data 4.0K Jan 13 11:25 .
drwxrwx---+ 4 1000 www-data 4.0K Jan 11 12:06 ..
-rw-rw-r--+ 1 1000 www-data 2.5K Jan 22 11:57 config.php
-rw-rw-r--+ 1 1000 www-data 2.5K Jan 13 11:25 config.php.bak.php
-rw-rw-r--+ 1 1000 www-data 9.0K Jan 22 11:57 log.txt
```

My UserID is 1000, and the GroupID is also 1000.
Something during the boot of the container changes the group ownership to `www-data`. And some parts of FreshRSS require it to be with that group it seems. I did not change the group ownership manually.

**Comment by Alkarex** [comment]
Something outside FreshRSS is changing your permissions. `www-data` must have read/write rights
When the container restarts, there is a script that automatically ensures the correct permissions.
What you have in the first part with 1000 or beloso is wrong, but it is not FreshRSS that has done that

**Comment by Alkarex** [comment]
You could also consider using real Docker volumes, do not touch what is inside, and let FreshRSS handle it.

E.g. `freshrss-data:/var/www/FreshRSS/data` instead of `$DOCKERDIR/freshrss/data:/var/www/FreshRSS/data`

**Comment by Alkarex** [comment]
P.S. Our images are not using `PUID` or `GUID` environment variables so I do not know where that comes from, but that has no effect

**Comment by beloso** [comment]
I think that might be a good suggestion. I do have a question though. I had to change one variable in the config.php file.

`base_url` to use my domain, otherwise, I was having trouble using Reeder app to connect to the API.
I am exposing it via Traefik.

```
  # FreshRSS - RSS Feed
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik_proxy
    ports:
      - $FRESHRSS_PORT:80
    depends_on:
      - "mariadb"
    volumes:
      - $DOCKERDIR/freshrss/data:/var/www/FreshRSS/data
      - $DOCKERDIR/freshrss/extensions:/var/www/FreshRSS/extensions
    environment:
      - CRON_MIN=*/20
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.freshrss-rtr.entrypoints=https"
      - "traefik.http.routers.freshrss-rtr.rule=Host(`rss.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.freshrss-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.freshrss-rtr.service=freshrss-svc"
      - "traefik.http.services.freshrss-svc.loadbalancer.server.port=80"
      ## Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
```

I'll remove `PUID` and `GUID` then.

**Comment by Alkarex** [comment]
Here is what I use for Traefik:

```yaml
  freshrss:
    image: freshrss/freshrss
    container_name: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    networks:
      - traefik-network
    volumes:
      - freshrss-data:/var/www/FreshRSS/data
      - freshrss-extensions:/var/www/FreshRSS/extensions
    environment:
      - CRON_MIN=4,34
      - TZ=Europe/Paris
      - FRESHRSS_ENV=development
    labels:
      - traefik.http.middlewares.freshrssM1.compress=true
      - traefik.http.middlewares.freshrssM2.headers.forceSTSHeader=true
      - traefik.http.middlewares.freshrssM2.headers.stsSeconds=31536000
      - traefik.http.routers.freshrss.middlewares=freshrssM1,freshrssM2
      - traefik.http.routers.freshrss.entryPoints=https
      - traefik.http.routers.freshrss.rule=Host(`freshrss.example.net`)
      - traefik.http.routers.freshrss.tls=true
      - traefik.http.routers.freshrss.tls.certResolver=letsEncrypt
```

Please open a new issue for `base_url`. FreshRSS is detecting it at install time (only when using the Web interface to install it), and that should work behind Traefik as well, assuming the correct HTTP headers are provided (which is the case by default). When installing FreshRSS by command line `base_url` can be passed as parameter. See also this new option https://github.com/FreshRSS/FreshRSS/pull/3353

I need to rewrite our Docker documentation, but here is a bit more substance https://github.com/FreshRSS/FreshRSS/issues/2918#issuecomment-616668682

**Comment by beloso** [comment]
I think I know what happened, I first configured FreshRSS using a local address, and only then exposed it via Traefik. That's why it didn't detect the final URL and why I had to change it. 

Since I moved everything into a docker volume (by your suggestion) I had to reconfigure FreshRSS from scratch. The correct URL got detected and everything is working.

About why I was using volumes like before, it's because I figured it would be best.
I'll need to understand what's fiddling with my ownerships. 

Thanks again for your patience and your time. Sorry for my noobiness. xD

**Comment by cswrd** [comment]
I know this issue is old, but it's the top result on google for "FreshRSS permission denied". On my **QNAP NAS** I also ran into a similar issue:

![permission denied issue](https://github.com/user-attachments/assets/c9aee330-07a7-4b9b-b6cf-744b2d041594)

As already mentioned, using a normal docker volume does solve the issue. So if you can live with that, I highly suggest to use that instead. I prefer bind mounts, as I can see the actual files on my host machine. It eases my backup strategy, also.

I think the root cause is that some parts of FreshRSS want to run with the user `www-data` having the `UID` and `GID` of `33`, especially when it comes to ACL lists. As I can't create users or groups with those IDs on my QNAP NAS (IDs start at 1000), **I hook into the start process of the FreshRSS and change the `GID` of the `www-data` user, instead**.

My solution is a dirty workaround with its own drackbacks, e.g. on version updates you need to double check that `CMD` or `ENTRYPOINT` in the dockerfile of FreshRSS are still the same or adapt the scripts below accordingly. The below mentioned ones works with `v1.24.3` for me.

### Step by step:
1) First, create a new user group on your host machine and check the `GID`. On my machine it's `1000`. I didn't need an extra user on my NAS, the group was sufficient.

2) Create a `entrypoint_custom.sh` like that with the above `GID` and store it near to your preferred volumes.

```
#!/bin/sh

groupmod -g 1000 www-data

exec ./Docker/entrypoint.sh "$@"
```
3) Add the following content to your docker compose file: 

```yaml
services:
  freshrss:
    entrypoint: ["./Docker/entrypoint_custom.sh"]
    command: ["/bin/bash", "-o", "pipefail", "-c", "([ -z \"$CRON_MIN\" ] || cron) && \t. /etc/apache2/envvars && \texec apache2 -D FOREGROUND $([ -n \"$OIDC_ENABLED\" ] && [ \"$OIDC_ENABLED\" -ne 0 ] && echo '-D OIDC_ENABLED')"]
    volumes:
      - /share/CE_CACHEDEV1_DATA/<your_fresh_rss_dir>/entrypoint_custom.sh:/var/www/FreshRSS/Docker/entrypoint_custom.sh

```

fyi: Essentially, all it trys to do is to invoke `groupmod -g 1000 www-data` as early as possible. Afaik, if you overwrite `CMD` or `ENTRYPOINT` you have to overwrite them both. That's why it's necessary to repeat that long `command` statement from the Dockerfile (note the added commas for syntactical reasons).

edit: I noticed cron didn't work that way. I figured out "CRON_MIN" is not available that way. I changed `[ -z \"$CRON_MIN\" ] || cron` to just `cron` to fix the built-in cron. OIDC would have the same issue I guess. Not sure why the environment variables aren't available via `$` syntax. They appear via `printenv` though.
