### ISSUE TITLE
Activating 3rd party extensions

### ISSUE THREAD

**Issue by aberja** [FreshRSS/FreshRSS#3599]
I installed FreshRSS as a stack in Portainer using a docker compose file (see below for copy).

Everything appears to be working except I cannot activate 3rd party extensions.

My way of example, I'm trying to active the threepaneview https://framagit.org/nicofrand/xextension-threepanesview/-/tree/master/

The FreshRSS install created a container freshrss-app-01 with 3 volumes: freshrss01_data, freshrss01_db, freshrss01_extensions

freshrss01_extensions volume has the host mount path as:
  ` /var/lib/docker/volumes/freshrss01_extensions/_data 
`

And the container mounted path is: `/var/www/FreshRSS01/extensions`

So I copied xextension-threepanesview-master into:
   `/var/lib/docker/volumes/freshrss01_extensions/_data
`
```
user123@localhost:~$ ls /var/lib/docker/volumes/freshrss01_extensions/_data
xextension-threepanesview-master
```

When the above didn't work, I also put a copy into:
  `/var/lib/docker/volumes/freshrss01_extensions`

```
user123@localhost:~$ sudo ls /var/lib/docker/volumes/freshrss01_extensions/
_data  xextension-threepanesview-master
```

But the extension page again didn't recognize that the extension was there.

It does not appear in the container extensions folder:
 
```
user123@localhost:~$ sudo docker exec -it freshrss-app-01 ls -alh extensions
total 24K
drwxr-xr-x 1 root www-data 4.0K Mar 14 13:08 .
drwxr-xr-x 1 root www-data 4.0K Apr 26 19:42 ..
-rw-r--r-- 1 root www-data    6 Mar 14 13:08 .gitignore
-rw-r--r-- 1 root www-data  197 Mar 14 13:08 README.md

```
It's also not in the data/extensions-data folder:

```
user123@localhost:~$ sudo docker exec -it freshrss-app-01 ls -alh data/extensions-data
total 8.0K
drwxrwx--- 2 root www-data 4.0K Apr 26 19:42 .
drwxrwx--- 9 root www-data 4.0K Apr 27 14:11 ..
-rw-rw-r-- 1 root www-data    0 Apr 30 13:13 index.html
```

I feel that I'm missing something that is obvious, but I just can't see it. Any suggestions?

P.S. For completeness, here is the docker compose file I used:

```
version: "3"

services:
  freshrss-db-01:
    image: postgres:latest
    container_name: freshrss-db-01
    hostname: freshrss-db-01
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql01/data
    environment:
      POSTGRES_USER: pgu_freshrss_01
      POSTGRES_PASSWORD: secretpasswordhere
      POSTGRES_DB: pgdb_freshrss_01

  freshrss-app-01:
    image: freshrss/freshrss:latest
    container_name: freshrss-app-01
    hostname: rss01
    restart: unless-stopped
    ports:
      - "8070:80"
    depends_on:
      - freshrss-db-01
    volumes:
      - data:/var/www/FreshRSS01/data
      - extensions:/var/www/FreshRSS01/extensions
    environment:
      CRON_MIN: '*/30'
      TZ: America/Chicago

volumes:
  db:
  data:
  extensions:


```

**Comment by aledeg** [comment]
When looking at your `docker-compose.yml` file. It seems that your volumes are not defined. If you check the `volumes` section, there is nothing there:
```yaml
volumes:
  db:
  data:
  extensions:
```

I think you need to update your configuration by adding the volume information in that section or by changing the volume information in the service section. Here, `db`, `data` and `extensions` are aliases used in the service section.

**Comment by aberja** [comment]
Thank you @aledeg for your suggestions.

Unfortunately, I'm still learning to use Docker so I'm trying to follow others and learn as I go.  For example, I used the docker-compose.yml file here: https://github.com/FreshRSS/FreshRSS/blob/master/Docker/docker-compose.yml

Which appears to be setup the same way.  I thought the volumes were defined in the services section:

volumes:
      - db:/var/lib/postgresql01/data

 volumes:
      - data:/var/www/FreshRSS01/data
      - extensions:/var/www/FreshRSS01/extensions

Are you suggesting that I need to copy the same lines I have in the services section to the volumes: section, something like:

volumes:
      db:/var/lib/postgresql01/data
      data:/var/www/FreshRSS01/data
      extensions:/var/www/FreshRSS01/extensions

Or alternatively, do I even require the volumes: section?  Can it be deleted since I have defined the volumes in the services section?

**Comment by aledeg** [comment]
I don't know how exactly you need to configure that using the volume section.
What is missing is the link between the volume name and the location on the local FS. One way of doing it is using the local FS path directly in the service section:
```yaml
volumes:
- /path/to/local/data:/var/lib/postgresql01/data
```

I haven't tested that but it should work. You can even add how you want the local FS to be mounted:
```yaml
volumes:
- /path/to/local/data:/var/lib/postgresql01/data:ro
```
Note that I used a read-only volume. Definitely not what you need here.

**Comment by aberja** [comment]
I apologize for my ignorance as this is the first time I'm using named volumes.  I thought we don't need to put a link when we use named volumes.  I've read that by default, "_all Docker-managed named volumes are stored under the installed Docker directory… typically, var/lib/docker/volumes/[path]_."  

I'm also struggling to understand, based on your comments, whether the docker compose file provided by FreshRSS ( https://github.com/FreshRSS/FreshRSS/blob/master/Docker/docker-compose.yml ) is incomplete and missing the links you refer to.  I would have thought that if I used that file, everything should work.

**Comment by aledeg** [comment]
I am not using the `docker-compose.yml`. Neither when developing nor on my server. Hence, I am not sure if it should work out-of-the-box as you're expecting.
You can check the start rule from the Makefile (I am using that for development) which loads different volumes during start-up. It might help you figure out how to configure your environment.

**Comment by aberja** [comment]
I have resolved the extension issue by starting over and using the docker compose file I've enclosed below.

When using a docker compose file and named volumes, linking is not required as docker automatically creates the volumes and links for you.

I was able to install extensions by copying them into the FreshRSS extensions volume.  Which in my case was: 
` /var/lib/docker/volumes/freshrss_02_extensions2/_data`

My issue may have been created during the intial setup.  So for anyone having this issue, ensure the database information matches the docker compose file, i.e.

database: postgresql
host: freshrss-db
database user name: freshrss_user
database password: secretpasswordhere
database name: freshrss_database
table prefix: freshrss

**Docker Compose file:**

```
version: "3"

services:
  freshrss-db:
    image: postgres:12-alpine
    container_name: freshrss-db
    hostname: freshrss-db
    restart: unless-stopped
    volumes:
      - db2:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: freshrss_user
      POSTGRES_PASSWORD: secretpasswordhere
      POSTGRES_DB: freshrss_database

  freshrss-app:
    image: freshrss/freshrss:latest
    container_name: freshrss-app
    hostname: freshrss-app
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - freshrss-db
    volumes:
      - data2:/var/www/FreshRSS/data
      - extensions2:/var/www/FreshRSS/extensions
    environment:
      CRON_MIN: '*/30'
      TZ: America/Chicago

volumes:
  db2:
  data2:
  extensions2:
```
