### ISSUE TITLE
[Question] How is HTTP auth configured?

### ISSUE THREAD

**Issue by cskwrd** [FreshRSS/FreshRSS#3613]
When I try to install FreshRSS, the HTTP auth option is disabled. Authentication is handled in my reverse proxy, and the authenticated user is passed to FreshRSS in the header `Remote-User`. From the code it looks like this is what is required.

**Comment by Alkarex** [comment]
There is probably something wrong with the header.
Try to make a test with a new file `./FreshRSS/p/i/phpinfo.php` with the following content:

```php
<?php
phpinfo();
```

and then access it through your browser https://freshrss.example.net/i/phpinfo.php

Please show the part with user information.

Note that only the `./FreshRSS/p/i/` directory is supposed to be protected by HTTP Basic Auth, not other folders such as `./FreshRSS/p/api/`

**Comment by Alkarex** [comment]
Ok, I see.
For delegated HTTP Authentication, set the `X-WebAuth-User` header.

FreshRSS is using one of the following, by order of preference:
* `REMOTE_USER` (you have `HTTP_REMOTE_USER` instead because you pass it as normal HTTP header)
* `REDIRECT_REMOTE_USER` (no such thing for you)
* `HTTP_X_WEBAUTH_USER` (with your setup, this is the one I would suggest, passing `X-WebAuth-User`)

**Comment by Alkarex** [comment]
P.S. That is quite standard for reverse proxies. See e.g. https://doc.traefik.io/traefik/middlewares/basicauth/

**Comment by cskwrd** [comment]
How must the user be passed to specify `REMOTE_USER`? I am not using basic auth, but offloading auth to another service.

My biggest issue with `X-WebAuth-User`, is that the `X-` prefix is technically [deprecated](https://datatracker.ietf.org/doc/html/rfc6648).

**Comment by Alkarex** [comment]
I do not think you can pass `REMOTE_USER` if you do not have access to the Web Server / CGI environment and are not using the full Basic Auth.

**Comment by Alkarex** [comment]
@cskwrd There would be security implications of accepting random headers. `REMOTE_USER` is safe but `HTTP_REMOTE_USER` is not. We could introduce a variable like Traefik is doing https://doc.traefik.io/traefik/middlewares/basicauth/#headerfield to accept something else than default `X-WebAuth-User` but the more complexity, the higher the risk of wrong or unsafe configurations.
I am not aware of a more standard field than `X-WebAuth-User` for delegated HTTP Authentication, but input welcome.
See another example https://grafana.com/docs/grafana/latest/auth/auth-proxy/

The `X-` in front of existing headers is not a problem at all, and the RFC you are referring to says exactly that.

**Comment by cskwrd** [comment]
> The X- in front of existing headers is not a problem at all, and the RFC you are referring to says exactly that.

I see now that I misread that.

Thank you for taking the time to answer my questions. For now, I will open a ticket with my auth provider and just use the `None` auth option in FreshRSS.

**Comment by duckpuppy** [comment]
@Alkarex I know this is closed, but my guess is that @cskwrd is using Authelia for auth, and that's where the `HTTP_REMOTE_USER` is coming from (rather than `REMOTE_USER`). I have the same problem, and all of the headers that Authelia is setting are prefixed with `HTTP_`.

https://github.com/authelia/authelia

It's possible that he's also using Traefik, and authelia is setting things properly. Traefik can be configured to copy headers from the auth response to the proxied response. In my case, I have this configured via Docker label:

`"traefik.http.middlewares.authelia.forwardauth.authResponseHeaders": "Remote-User, Remote-Groups, Remote-Name, Remote-Email"`

This should copy the headers verbatim, but I'm assuming that Traefik is sending them in such a way they end up prefixed with `HTTP_`? I admit, I'm not a PHP developer at all... I've been a software dev for 20+ years, but never done much in the way of web development.

**Comment by duckpuppy** [comment]
Ah, I see what's happening. Authelia -> traefik -> FreshRSS is passing along the `Remote-User` as an HTTP header, which in turn means it's available via the `$_SERVER[HTTP_REMOTE_USER]` variable, prefixed with `HTTP_` because that's how PHP encodes the HTTP headers from the response. It would seem that checking `HTTP_REMOTE_USER` would make sense, as a lot of external auth services would pass that value back in an HTTP header.

**Comment by anagno** [comment]
I have the same scenario (i.e. Authelia-> Traefik -> FreshRSS) and technically there is a workaroud.

We can instruct the Apach Server to forward the HTTP_REMOTE_USER to x-WebAuth-User with a custom .htacess

```
    SetEnvIf Remote-User (.*) saved_http_remote_user=$1
    RequestHeader set X-WebAuth-User "%{saved_http_remote_user}e"
```

It seems to work.
For the people who are interested this is my deployment in Kubernetes:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-config
  labels:
    app: freshrss-server
data:
  .htaccess: |
    SetEnvIf Remote-User (.*) saved_http_remote_user=$1
    RequestHeader set X-WebAuth-User "%{saved_http_remote_user}e"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshrss
  labels:
    app: freshrss-server
spec:
  selector:
    matchLabels:
      app: freshrss-server
  replicas: 1
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: freshrss-server
    spec:
      dnsPolicy: Default
      containers:
      - name: freshrss-server
        image: freshrss/freshrss:1.18.1-arm
        imagePullPolicy: IfNotPresent
        args:
          - /bin/sh
          - -c
          - |
            . /etc/apache2/envvars \
            && exec apache2 -D FOREGROUND
        ports:
          - name: http
            containerPort: 80
        volumeMounts:
          - mountPath: /var/www/FreshRSS/data
            name: data
            readOnly: false
          - mountPath: /var/www/FreshRSS/p/i/.htaccess
            name: apache-config
            subPath: .htaccess
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: news-data
            readOnly: false
        - name: apache-config
          configMap:
            name: apache-config
```
