### ISSUE TITLE
[BUG] unknown error for feed,https://www.tandfonline.com/feed/rss/trsl20

### ISSUE THREAD

**Issue by monkiq** [FreshRSS/FreshRSS#3786]
**Describe the bug**
Hi
when adding this feed [https://www.tandfonline.com/feed/rss/trsl20]
，freshrss report unknown error for feed,
but i try to use curl ,it works.

**Environment information (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - FreshRSS version: [1.18.1]

**Comment by Frenzie** [comment]
It works for me. What does the error log say?

**Comment by monkiq** [comment]
> It works for me. What does the error log say?

![image](https://user-images.githubusercontent.com/27727951/130195198-17103afa-8638-4fb6-8cef-073c5dfd9b65.png)
cURL error 22: The requested URL returned error: 403

**Comment by Frenzie** [comment]
And you don't get a 403 (not permitted) if you use curl on the same machine?

**Comment by monkiq** [comment]
> And you don't get a 403 (not permitted) if you use curl on the same machine?

I deploy freshrss on docker, in my machine use curl can got data,
![image](https://user-images.githubusercontent.com/27727951/130196399-c514e8b7-5628-4a6b-8519-82544668e238.png)

**Comment by monkiq** [comment]
> And you don't get a 403 (not permitted) if you use curl on the same machine?
maybe it's my cloud host problem. I try to use someone's freshrss, it also can get feed with no error

**Comment by Frenzie** [comment]
Were you able to solve the problem with your Docker configuration?

**Comment by monkiq** [comment]
use this feed - http://rss.sciencedirect.com/publication/science/00344257 replace https://www.tandfonline.com/feed/rss/trsl20

**Comment by monkiq** [comment]
> Were you able to solve the problem with your Docker configuration?

this is my docker configuration,but i don't know how to solve it
```
version: '3'

services:
    freshrss:
        image: freshrss/freshrss
        restart: always
        container_name: freshrss
        networks:
            - traefik_default
        ports:
            - "1234:80"
        volumes:
            - freshrss-data:/var/www/FreshRSS/data
            - freshrss-extensions:/var/www/FreshRSS/extensions

volumes:
  freshrss-data:
  freshrss-extensions:
networks:
  traefik_default:
    external: true
```
