### ISSUE TITLE
[BUG] Installation stuck on step 0 when accessing with a domain

### ISSUE THREAD

**Issue by xyqyear** [FreshRSS/FreshRSS#3816]
**Describe the bug**
I was using freshrss with docker, when I access freshrss with `http://{ip_address}:8081`, i can finish the installation process just fine. But when I access freshrss with `http://{domain}:8081`, i couldn't proceed to step 1. 

When I inspect the network connections, I can see the request URL is `http://{domain}:8081/i/index.php?step=1`. But the status code is `302 Found` then it redirect me to `http://{domain}:8081/i/index.php?step=0`.

this is my docker-compose.yaml file:

```yaml
version: "3"

services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    restart: unless-stopped
    ports:
      - 8081:80
    volumes:
      - ./data/data:/var/www/FreshRSS/data
      - ./data/extensions:/var/www/FreshRSS/extensions
    environment:
      CRON_MIN: '*/20'
      TZ: Asia/Shanghai
```

**To Reproduce**
1. prepare a domain name and point it to the IP address of the server
2. launch the server with docker using the docker-compose.yaml described above
3. access the server with `http://{domain}:8081`
4. stuck on step 0

**Expected behavior**
The server behaves normally, meaning I can finish the installation process.

**Screenshots**
When using domain name to access the server (behaves abnormally):
![image](https://user-images.githubusercontent.com/29950788/131608182-8283a450-799a-47d3-8fd9-66b751afc069.png)

When using IP address to access the server (behaves normally):
![image](https://user-images.githubusercontent.com/29950788/131608228-a311aa41-500c-46b1-bc77-7899fb5400df.png)

**Environment information (please complete the following information):**
 - Device: Windows 10 21H2
 - Browser: Chrome 92.0.4515.159
 - Server OS: Debian 10
 - FreshRSS version: 1.18.1
 - Database version: sqlite
 - PHP version: 7.3.27-1~deb10u1
 - Installation type: Docker
