### ISSUE TITLE
Alternative Dark theme: not best buttons color, not fully optimized for mobile

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4585]
> Question: `Which one do you use?` and `Why do you like it?`
> 
Alternative Dark
best dark version but sadly not best buttons color and also not fully optimized for mobile.

_Originally posted by @beerisgood in https://github.com/FreshRSS/FreshRSS/issues/4295#issuecomment-1237418148_

**Comment by math-GH** [comment]
Hey @beerisgood,
thank you for your additional feedback. Let's use this ticket here to gain more insights.

What do you mean with "best buttons"?
What do you mean with "not fully optimized for mobile"?

Which FreshRSS version do you use?

**Comment by beerisgood** [comment]
layout for mobile isn't that nice:
![telegram-cloud-photo-size-4-5816864034098625245-y](https://user-images.githubusercontent.com/9625159/188702502-3545a7b2-a7f4-4387-a4e6-eebe80a84b2e.jpg)

clicking on folder icon sometimes results in "mark all as read" button below. the other icons are also very close together.
i would also move the icons themselves.

color of the button does not read well with black theme:
![image](https://user-images.githubusercontent.com/9625159/188703051-1aef2787-343d-4e17-a513-f977b2db0328.png)
(this is on desktop)

FreshRSS 1.19.2

**Comment by math-GH** [comment]
Thanks for this insights.

I cannot reproduce the little stairs in the mobile view.

There is some work left to improve the mobile layout in general.

The "buttons" are select lists. Your operating system or browser theme change it to a very "special" design. 

Which operating system and browser do you use?

**Comment by beerisgood** [comment]
> Which operating system and browser do you use?
>

latest stable Safari in MacOS & iOS

**Comment by Frenzie** [comment]
I'll submit a quick fix.

**Comment by math-GH** [comment]
I will keep it open for the other thing.

**Comment by math-GH** [comment]
I checked it now with Safari and can confirm the "stairs" in the menu. Will try to fix it

**Comment by Poorchop** [comment]
I liked the alternative dark theme the best when I first started using FreshRSS but I had some issues with it. There were some bugs, some of which I think I tried to address, but there are also some cosmetic changes that I personally preferred. I use the custom CSS extension with my own additions:

```css
@media (min-width: 841px) {
	.header {
		height: 40px;
	}

	.header > .item {
		padding: 0;
	}

	.header > .item.title h1 {
		font-size: 1em;
		margin: 0;
	}

	.header > .item.title .logo {
		height: 25px;
	}

	.header > .item.search input {
		padding: 1px 5px;
	}

	a.btn, .stick .btn {
		min-height: 20px;
		line-height: 20px;
	}

	.tree-folder-title {
		font-size: 0.9rem;
		line-height: 2.25rem;
	}

	.aside_feed .category .title:not([data-unread="0"])::after {
		font-size: 0.8rem;
		margin: 5px 0;
	}

	#nav_entries {
		border-top: 1px solid #333;
	}
}

@media (max-width: 840px) {
	.header {
		height: unset;
		table-layout: unset;
	}

	/* Stopgap for Safari since it doesn't support overflow-wrap: anywhere; */
	.flux {
		overflow-x: auto;
	}

	.flux .item.title a {
		overflow-wrap: anywhere;
	}
}

html, body {
	font-family: "Helvetica", sans-serif;
}

.btn {
	background: linear-gradient(to bottom, #272727, #171717);
}

.btn.active, .btn:active, .dropdown-target:target ~ .btn.dropdown-toggle {
	background: #363636;
	box-shadow: 0px 2px 4px #1f1f1f inset, 0px 1px 2px #050505;
}

.btn-important {
	background: linear-gradient(to bottom, #0084cc, #0045cc);
}

.btn-important:hover {
	background: linear-gradient(to bottom, #06c, #0045cc);
}

.content {
	line-height: 1.45;
}

.text {
	font-family: "Charter", serif;
	font-size: 1.125rem;
}

.text a {
	color: #58a6ff;
	text-decoration: underline;
}
```

I don't remember what all of these rules were meant to address but I believe the first several rules are to reduce padding and make things more compact. The button changes are meant to make buttons look more 3D, which is how I think they look with the default theme. I'm not a fan of flat buttons. There are also some changes here to make things more mobile-friendly
