### ISSUE TITLE
Theme Alternative Dark: Custom CSS for compact view

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4601]
Originally posted by @Poorchop in https://github.com/FreshRSS/FreshRSS/issues/4585#issuecomment-1242878393

I liked the alternative dark theme the best when I first started using FreshRSS but I had some issues with it. There were some bugs, some of which I think I tried to address, but there are also some cosmetic changes that I personally preferred. I use the custom CSS extension with my own additions:

```css
@media (min-width: 841px) {
	.header {
		height: 40px;
	}

	.header > .item {
		padding: 0;
	}

	.header > .item.title h1 {
		font-size: 1em;
		margin: 0;
	}

	.header > .item.title .logo {
		height: 25px;
	}

	.header > .item.search input {
		padding: 1px 5px;
	}

	a.btn, .stick .btn {
		min-height: 20px;
		line-height: 20px;
	}

	.tree-folder-title {
		font-size: 0.9rem;
		line-height: 2.25rem;
	}

	.aside_feed .category .title:not([data-unread="0"])::after {
		font-size: 0.8rem;
		margin: 5px 0;
	}

	#nav_entries {
		border-top: 1px solid #333;
	}
}

@media (max-width: 840px) {
	.header {
		height: unset;
		table-layout: unset;
	}

	/* Stopgap for Safari since it doesn't support overflow-wrap: anywhere; */
	.flux {
		overflow-x: auto;
	}

	.flux .item.title a {
		overflow-wrap: anywhere;
	}
}

html, body {
	font-family: "Helvetica", sans-serif;
}

.btn {
	background: linear-gradient(to bottom, #272727, #171717);
}

.btn.active, .btn:active, .dropdown-target:target ~ .btn.dropdown-toggle {
	background: #363636;
	box-shadow: 0px 2px 4px #1f1f1f inset, 0px 1px 2px #050505;
}

.btn-important {
	background: linear-gradient(to bottom, #0084cc, #0045cc);
}

.btn-important:hover {
	background: linear-gradient(to bottom, #06c, #0045cc);
}

.content {
	line-height: 1.45;
}

.text {
	font-family: "Charter", serif;
	font-size: 1.125rem;
}

.text a {
	color: #58a6ff;
	text-decoration: underline;
}
```

I don't remember what all of these rules were meant to address but I believe the first several rules are to reduce padding and make things more compact. The button changes are meant to make buttons look more 3D, which is how I think they look with the default theme. I'm not a fan of flat buttons. There are also some changes here to make things more mobile-friendly

_Originally posted by @Poorchop in https://github.com/FreshRSS/FreshRSS/issues/4585#issuecomment-1242878393_
