### ISSUE TITLE
[BUG] Error during context user init!

### ISSUE THREAD

**Issue by Savanta** [FreshRSS/FreshRSS#4945]
``**Describe the bug**
After deploing linuxserver.io page shows up but during initial configuration error pops: Error during context user init!

**To Reproduce**
1. Deploy FreshRSS through docker compose
2. Go through configuration phase
3. Login as regular user
4. Error pops up through entire process, refresh several times allows to continue

**Expected behavior**
Normal usage

**Screenshots**

**Environment information (please complete the following information):**
- Device: Docker container
- OS: Linux 8dd715a7d4ac 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux
- Browser: Vivaldi
- FreshRSS version: Linuxserver.io version:- 1.20.2-ls157 Build-date:- 2022-12-08T12:23:51+01:00
- Database version: [e.g. Mysql 5.7]
- PHP version: [e.g. PHP 7.4]
- Installation type: Docker

**Additional context**
Compose:
```
version: "2.1"
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:1.18.1
    container_name: FreshRSS
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - /media/Dane/.docker/freshrss:/config
    restart: unless-stopped
    networks:
      - InternalNPM

networks:
  InternalNPM:
      external: true
```

**Comment by Alkarex** [comment]
* The current version of FreshRSS is 1.20.2, so please update instead of 1.18.1
* Do you have any logs?
* Can you try without a volume and potentially without PUID / PGID, just for narrowing the problem
* If you can, give a try to our `freshrss/freshrss` image https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md

**Comment by Alkarex** [comment]
Potentially similar to https://github.com/FreshRSS/FreshRSS/issues/4795

**Comment by Savanta** [comment]
So I changed my compose to:
```
version: "2.1"
services:
  freshrss:
    image: freshrss/freshrss:1.20.2
    container_name: FreshRSS
    environment:
      - TZ=Europe/Warsaw
    restart: unless-stopped
    networks:
      - InternalNPM

networks:
  InternalNPM:
      external: true
```
But error persists.
```
[Mon Dec 19 10:17:31.790956 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.54 (Debian) configured -- resuming normal operations
[Mon Dec 19 10:17:31.790991 2022] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
80.49.50.10 - - [19/Dec/2022:10:17:39 +0100] "GET /i/?rid=63a02c33bb36d HTTP/1.1" 200 1138 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
```
