### ISSUE TITLE
[BUG] Can't see which unread article is focused

### ISSUE THREAD

**Issue by alexklapheke** [FreshRSS/FreshRSS#5207]
**To Reproduce**

1. Using Origine or Origine-compact theme, load a page of unread articles
2. Use keyboard shortcuts for "focus previous/next without opening"
3. You can't see which one is focused because the CSS for "unread" (pale red background) seems to be overriding the CSS for "focused" (white background)

**Environment information:**

- Browser: Firefox 110.0.1
- FreshRSS version: 1.21.0
- PHP version: 7.4.33

**Comment by alexklapheke** [comment]
FYI, I've worked around this using the custom CSS extension and the following style:

```css
.flux.current .item { background-color: var(--background-color-light) !important; }
```
