### ISSUE TITLE
[BUG] error: "SQL error markRead 1: database is locked"

### ISSUE THREAD

**Issue by Luxtech** [FreshRSS/FreshRSS#5208]
**Describe the bug**
I run FreshRSS for some time and I really enjoy it.
Lately when reading articles the UI gets really slow and I cannot mark articles as read. When I go to the logs I get the following error: "SQL error markRead 1: database is locked"

It happens about a few times a day, the error fixes it self after a couple of minutes and I can continue as normal.

I run the docker container on a Raspberry Pi 4 with a external HDD, I have about 72000 articles around (260 MiB). With the external HDD the Pi has some problems with long IO-waits. Optimizing the database seems to do nothing than slowing down the Pi for a couple of minutes and getting a "504 Gateway Time-out" error, after a refresh this error goes a way and I can get to the FreshRSS homepage.

**To Reproduce**
Run FreshRSS in a Docker container and mark articles as read.

**Expected behavior**
Mark articles as read when clicking on the icon.

**Screenshot**
After trying to optimize database:
![image](https://user-images.githubusercontent.com/27952645/225599658-78bec2d8-494b-4c4a-904f-4c8a1d9f7b35.png)

**Environment information (please complete the following information):**
- Device: Raspberry pi 4
- OS: Raspbian-lite
- Browser: Firefox
- FreshRSS version: 1.12.0
- Database version: ?
- PHP version: PHP 8.1.1.6
- Installation type: Docker

**Comment by Alkarex** [comment]
Hello,
What database are you using? (SQLite, MySQL, MariaDB, PostgreSQL)
I would like to ask you to run a couple of SQL commands to locate the problem more precisely, and hopefully solve it.
What type of file system are you using on the disk where your database data is?

**Comment by Luxtech** [comment]
Filesystem is EXT4.
I run de default database. 

This is my docker-compose file:
```
version: '3'
services:
    freshrss:
        image: lscr.io/linuxserver/freshrss:latest
        container_name: freshrss
        environment:
             - PUID=1000
             - PGID=1000
             - TZ=Europe/Amsterdam
        volumes:
             - ./volumes/freshrss:/config
        ports:
             - 8002:80
        restart: unless-stopped
```
