### ISSUE TITLE
[BUG] exec ./Docker/entrypoint.sh: exec format error

### ISSUE THREAD

**Issue by eMUQI** [FreshRSS/FreshRSS#5236]
**Describe the bug**
Hello, 
While attempting to deploy FreshRSS on my Raspberry Pi using Docker Compose, I encountered the following error despite having used an ARM image as directed in the README. Can anyone offer advice on how to resolve this issue? Thank you.
```
exec ./Docker/entrypoint.sh: exec format error
```

**To Reproduce**
`docker-compose.yml`:
```
version: "2.4"

volumes:
  data:
  extensions:

services:

  freshrss:
    image: freshrss/freshrss:arm
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - data:/var/www/FreshRSS/data
      - extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: Asia/Shanghai
      CRON_MIN: '3,33'
```

`docker-compose-local.yml`:
```
version: "2.4"

services:

  freshrss:
    ports:
      - "${PUBLISHED_PORT:-8080}:${LISTEN:-80}"
```

``` bash
docker-compose pull
docker-compose -f docker-compose.yml -f docker-compose-local.yml up -d --remove-orphans
```
log：
```
freshrss  | 2023-03-28T15:11:56.142222115Z exec ./Docker/entrypoint.sh: exec format error
freshrss  | 2023-03-28T15:11:57.471806717Z exec ./Docker/entrypoint.sh: exec format error
freshrss  | 2023-03-28T15:11:58.801749038Z exec ./Docker/entrypoint.sh: exec format error
freshrss  | 2023-03-28T15:12:00.091093743Z exec ./Docker/entrypoint.sh: exec format error
freshrss  | 2023-03-28T15:12:01.835861314Z exec ./Docker/entrypoint.sh: exec format error
freshrss  | 2023-03-28T15:12:04.341191644Z exec ./Docker/entrypoint.sh: exec format error
freshrss exited with code 1
```

**Expected behavior**
freshrss is working properly

**Environment information (please complete the following information):**
- aarch64
- Device: [raspberry pi 4b ]
- OS: [ OpenWrt 5.4.203]
- Installation type: [docker-compose]
- 

**Additional context**

**Comment by Alkarex** [comment]
Hello,
Are you in 64-bit by any chance? If yes, same as https://github.com/FreshRSS/FreshRSS/issues/4089

In your docker-compose.yml, try the following:

```yml
    ...
    image: freshrss/freshrss:git
    build:
      context: https://github.com/FreshRSS/FreshRSS.git#latest
      dockerfile: Docker/Dockerfile-Alpine
    ...
```
