### ISSUE TITLE
[BUG] Change Visibility in latest Docker EDGE version not working

### ISSUE THREAD

**Issue by quella** [FreshRSS/FreshRSS#5273]
**Describe the bug**
After applying the latest EDGE-ARM Docker image a few of my feeds reset their VISIBILITY from Category Only to Main Stream.  When I go to change them back to Category Only, it says the change was saved, but the Visibility seems top go back to Main Stream.  Just a heads up.

**To Reproduce**
1. Noticed feeds previously shown only in Category show up in Main feed.
2. Opened the feed under subscription and click to change setting
3. Noticed it was set to Main (after a Docker Upgrade to Edge-ARM Docker
4. Tried to change the setting back to Category and save
5. Get save message, but the setting reverts back to Main.

**Expected behavior**
Described above.

**Screenshots**
None

**Environment information (please complete the following information):**
- Device: MacOS latest Chrome
- OS: [e.g. Ubuntu 20.04]
- Browser: Latest Chrome
- FreshRSS: Docker Edge-ARM
- Database version: Docker
- PHP version: Latest RaspberryPi (v7.4)
- Installation type: Docker

**Additional context**

**Comment by Alkarex** [comment]
Thanks for the bug report and for using the edge version. Should be fixed by https://github.com/FreshRSS/FreshRSS/pull/5274
Tests welcome

The Docker images are being rebuilt and should be available in a few minutes. Otherwise, you can instruct your Docker or docker-compose to automatically build from git:

```yml
    build:
      # Pick #latest (stable release) or #edge (rolling release) or a specific release like #1.21.0
      context: https://github.com/FreshRSS/FreshRSS.git#edge
      dockerfile: Docker/Dockerfile-Alpine
```

* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#build-custom-docker-image
* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose.yml
