### ISSUE TITLE
[BUG] Impossible to change 'Thumbnail' option in 'Display'

### ISSUE THREAD

**Issue by camHQ** [FreshRSS/FreshRSS#5276]
Hello, 
I am unable to change the 'Thumbnail' option in the 'Display' settings. Whenever I try to modify the option and save the changes, the setting reverts back to its previous state. 

I set the option to 'None', then I click on 'submit', and the message 'Configuration has been updated' is displayed. Then I click on the FreshRSS logo to go back to the home page and the browser informs me that 'This page is asking you to confirm that you want to leave - data you have entered may not be saved.' I have the option to 'Stay on the page' or 'Leave the page'. I choose 'Leave the page', but the thumbnails are still present.

- Raspberry Pi
- Debian GNU/Linux 11 (bullseye)
- FreshRSS version 1.21.1-dev
- Firefox 102.9
- mysql Ver 15.1
- PHP 8.1.17

**Comment by Alkarex** [comment]
Thanks for the bug report and for using the edge version. Should be fixed by https://github.com/FreshRSS/FreshRSS/pull/5278
Tests welcome.

If you use git, just pull the latest changes.

If you use Docker, the images are being rebuilt and should be available in a few minutes. Otherwise, you can instruct your Docker or docker-compose to automatically build from git:

```yml
    build:
      # Pick #latest (stable release) or #edge (rolling release) or a specific release like #1.21.0
      context: https://github.com/FreshRSS/FreshRSS.git#edge
      dockerfile: Docker/Dockerfile-Alpine
```

* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#build-custom-docker-image
* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose.yml
