### ISSUE TITLE
[BUG] Shortcut not saved in current edge version

### ISSUE THREAD

**Issue by lbalogh** [FreshRSS/FreshRSS#5293]
**Describe the bug**

Hi,

I'm trying to change the "Open the next unread article" shortcut from "h" to "ArrowRight", but after selecting "ArrowRight" in the drop menu and clicking "Submit", the shortcut is not saved and reverted to "h".

This is not limited  to  the"Open the next unread article" shortcut, as it seems to affect others, too.

**To Reproduce**

1. Go to 'Settings' > 'Shortcuts'
2. Change shortcut 'Open the next unread article' from 'h' to 'ArrowRight'
3. Click 'Submit'
4. See that the shortcut is reverted to the old value ('h')

**Expected behavior**

The shortcut is saved correctly.

**Environment information:**
- Device: Computer
- OS: Windows 11
- Browser: Google Chrome 112
- FreshRSS version: 1.21.1-dev
- Database version: PostgreSQL 15.2
- PHP version: 7.4.33
- Installation type: self hosted Docker edge image

**Comment by Frenzie** [comment]
I can't confirm. Could it have something to do with the Docker config?

**Comment by math-GH** [comment]
I can confirm outside of Docker

**Comment by Alkarex** [comment]
Thanks for the bug report and for using the edge version. Should be fixed by https://github.com/FreshRSS/FreshRSS/pull/5294
Tests welcome.

If you use git, just pull the latest changes.

If you use Docker, the images are being rebuilt and should be available in a few minutes. Otherwise, you can instruct your Docker or docker-compose to automatically build from git:

```yml
    build:
      # Pick #latest (stable release) or #edge (rolling release) or a specific release like #1.21.0
      context: https://github.com/FreshRSS/FreshRSS.git#edge
      dockerfile: Docker/Dockerfile-Alpine
```

* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#build-custom-docker-image
* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose.yml
