### ISSUE TITLE
[BUG] Latest ARM-Edge Docker No Longer AutoUpdates Feeds

### ISSUE THREAD

**Issue by quella** [FreshRSS/FreshRSS#5310]
**Describe the bug**
After pulling and deploying the latest Docker ARM-EDGE version this morning, the application no longer auto updates the feeds based on the set schedule in the Archive section.  I have mine set to hourly and with previous Docker images, this has maintained the auto update setting, but the latest build seems to not perform this update, but I can force a manual update via the web UI.  I have also tried to change the reapply the setting under Archive and save, but that did not seem to have any affect.  

**To Reproduce**
None, the previous setting for Auto Update of Feeds is not working as expected, but a manual update does work.

**Expected behavior**
I would expect the application to auto update feeds based on the setting as previously was the case until an update today.

**Screenshots**

**Environment information (please complete the following information):**
- Device: Docker Image Edge-Arm
- OS: RasbianOS (Latest Updates)
- Browser: N/A
- FreshRSS version: Edge-ARM on Docker
- Database version: N/A
- PHP version: [e.g. PHP 7.4]
- Installation type: EDGE-ARM Docker

**Additional context**
None.

**Comment by Alkarex** [comment]
Thanks for the bug report and for using the edge version. Should be fixed by https://github.com/FreshRSS/FreshRSS/pull/5311
Tests welcome.

If you use git, just pull the latest changes.

If you use Docker, the images are being rebuilt and should be available in a few minutes. Otherwise, you can instruct your Docker or docker-compose to automatically build from git:

```yml
    build:
      # Pick #latest (stable release) or #edge (rolling release) or a specific release like #1.21.0
      context: https://github.com/FreshRSS/FreshRSS.git#edge
      dockerfile: Docker/Dockerfile-Alpine
```

* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#build-custom-docker-image
* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose.yml
