### ISSUE TITLE
[BUG] FreshRSS suddenly changes back to installation

### ISSUE THREAD

**Issue by cfpwastaken** [FreshRSS/FreshRSS#5442]
**Describe the bug**

FreshRSS seemlingly randomly keeps changing back to the installation page, clicking on next shows "Blast! Check permissions on ..." for all the permission checks except for the temp one.

**To Reproduce**
1. Set up FreshRSS in Docker
2. Wait
3. Reload page
4. See install page again

**Expected behavior**

It should never switch back to installation, or report that the perms are bad.

**Screenshots**

![image](https://github.com/FreshRSS/FreshRSS/assets/44261356/1807c3cb-518a-45b7-ab46-95341080acc8)

**Environment information (please complete the following information):**
- Installation type: Docker, using the linuxserver image (also happens with the official one)

**Docker Compose file:**
```yml
version: "3"
services:
   freshrss:
      image: lscr.io/linuxserver/freshrss:latest
      container_name: freshrss
      environment:
         - PUID=1000
         - PGID=1000
         - TZ=Europe/Berlin
      volumes:
         - /media/vol/srv/freshrss:/config
      ports:
         - 1020:80
      restart: unless-stopped
```

**Additional context**

The volumes are on an NFS volume, which is on an HDD with NTFS. Because of that, I can't change any permissions, its all owned by root. FreshRSS works fine before this bug happens.
