### ISSUE TITLE
[BUG] Config and Data Not Persisting

### ISSUE THREAD

**Issue by NotGovernor** [FreshRSS/FreshRSS#5520]
I doubt this is a valid bug -- probably something with my config... But I cant get the data to persist between compose down / ups.

Here is my compose file:

```
version: '3'

services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    environment:
      - TZ=America/Chicago
      - CRON_MIN='2,32'
      - PUID=1000
      - PGID=1000
    logging:
      options:
        max-size: 10m
    container_name: freshrss
    restart: unless-stopped
    volumes:
      - ./freshrss_data:/var/www/FreshRSS/data
      - ./freshrss_extensions:/var/www/FreshRSS/extensions
    ports:
      - 50000:80
```

I up the compose -- hit the site, go through the set up, everything works great. Nothing is ever stored in either of the volume folders that get created though... And if I down and up it I loose all settings and rss feeds.

Any help would be appreciated. I'm not seeing anything in the documentation on it.

Thanks!
