### ISSUE TITLE
[BUG] Cannot login

### ISSUE THREAD

**Issue by wayner6** [FreshRSS/FreshRSS#5535]
**Describe the bug**
I successly install freshrss in my VPS, but a few days later:
It will loading for a long time when I want to login and finally it hints **Gateway time-out**

**To Reproduce**

Visit the website, input correct uid and passwd, the click login.

**Expected behavior**
I want to login successfully.

**Screenshots**
![image](https://github.com/FreshRSS/FreshRSS/assets/88063517/d9e385ad-8f3a-4725-b56c-112356185c8a)

**Environment information (please complete the following information):**
- Device: All devices
- OS: Ubuntu 20.04
- Browser: Chrome
- FreshRSS version: latest
- Database version: latest
- PHP version: [e.g. PHP 7.4]
- Installation type: Docker-compose
Here is my `docker-compose.yml` file
```
version: "3"

services:
  freshrss-db:
    image: postgres:latest
    container_name: freshrss-db
    hostname: freshrss-db
    restart: unless-stopped
    volumes:
      - freshrss-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: wayne111
      POSTGRES_PASSWORD: balabala
      POSTGRES_DB: freshrss

  freshrss-app:
    image: freshrss/freshrss:latest
    container_name: freshrss-app
    hostname: freshrss-app
    restart: unless-stopped
    ports:
      - "9090:80"
    depends_on:
      - freshrss-db
    volumes:
      - ./data:/var/www/FreshRSS/data
      - ./extensions:/var/www/FreshRSS/extensions
    environment:
      CRON_MIN: '*/30'
      TZ: Asia/Shanghai

volumes:
  freshrss-db:
```

**Additional context**
I am using nginx-proxy-manager as a proxy tools. I have checked `config.php` file and made sure `base_url` is my domain.
I ran `docker-compose up` to check performance：
```
docker-compose up
Creating network "ttrss_default" with the default driver
Creating freshrss-db ... done
Creating freshrss-app ... done
Attaching to freshrss-db, freshrss-app
freshrss-db     | 
freshrss-db     | PostgreSQL Database directory appears to contain a database; Skipping initialization
freshrss-db     | 
freshrss-db     | 2023-07-18 07:33:52.362 UTC [1] LOG:  starting PostgreSQL 15.3 (Debian 15.3-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
freshrss-db     | 2023-07-18 07:33:52.365 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
freshrss-db     | 2023-07-18 07:33:52.366 UTC [1] LOG:  listening on IPv6 address "::", port 5432
freshrss-db     | 2023-07-18 07:33:52.369 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
freshrss-db     | 2023-07-18 07:33:52.380 UTC [29] LOG:  database system was shut down at 2023-07-18 07:33:47 UTC
freshrss-db     | 2023-07-18 07:33:52.393 UTC [1] LOG:  database system is ready to accept connections
freshrss-app    | [Tue Jul 18 15:33:54.409658 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.54 (Debian) configured -- resuming normal operations
freshrss-app    | [Tue Jul 18 15:33:54.409886 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
freshrss-app    |   [18/Jul/2023:15:36:44 +0800] "GET / HTTP/1.1" 302 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
FreshRSS[93]: [wayne3602] [Tue, 18 Jul 2023 16:02:41 +0800] [error] --- Access to database is denied for `wayne111`: SQLSTATE[08006] [7] timeout expired
```
