### ISSUE TITLE
[BUG]: Recurring 504 Timeouts and High Resource Usage with MariaDB Operations

### ISSUE THREAD

**Issue by Emporea** [FreshRSS/FreshRSS#5707]
I just have to create a new issue since its still problematic for me..

**Description**:
Upon utilizing FreshRSS with MariaDB (version 10.6) under the Docker edge tag, there’s still an evident high resource usage and subsequent 504 timeouts during specific operations. The FreshRSS database CPU utilization spikes to approximately only 20% (should use more in my opinion since this states its not really optimized) and high IO disk usage, which reaches around 1GB/s, have been observed to last for a few minutes during several actions.

**Problematic Actions**:
1. **Actualize Script Execution**: Triggering the script manifests in a substantial resource strain for ~ 4 minutes.
2. **Adding New Feeds**: While the feed does get added, the operation culminates in a 504.
3. **Viewing Idle Feeds**: Invariably results in a 504 and is never accessible.
4. **General Feed Statistics**: Unreachable due to a perpetual 504.

**Insights and Potentials**:
Although the functions eventually serve their intended purpose (aside from viewing idle feeds and statistics), the undue strain and resulting timeouts mar the usability and efficiency of the system. A deductive observation points towards the possibility that the database queries still might not be wholly optimized for use with MariaDB, potentially requiring a revisit and refinement to enhance performance, especially in the aforementioned contexts.
I hope I can be of any help.by providing logs or testing development builds.

**Previous Discussion**:
It’s notable that the 504 issue has been broached before, its been solved for "Marking all News as Read" which is now done in a matter of seconds, yet it still pervasively persists through these other actions. Alleviating this would drastically improve the overall user experience and system reliability.

**Potential Resolution**:
Optimizing how MariaDB processes queries, especially during intensive operations such as those highlighted, might hold the key to alleviating the resource burdens and the subsequent 504 timeouts.

Any insights, assistance, or pointers on this would be massively appreciated!

Kind Regards.

**Comment by Alkarex** [comment]
Hello,
Please provide the usual information such as your FreshRSS version (please try with our edge version), how you installed FreshRSS (precise image in case of Docker install), size of your DB, etc.

**Comment by Emporea** [comment]
Freshrss version:  1.21.1-dev
database size: ~2.5GB
new articles per day: ~6000

Never deleting articles (purge policy disabled, purge exceptions enabled)

docker-compose.yml:
```
freshrss_db:
    image: mariadb:10.6
    container_name: freshrss_db
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - freshrss_db:/var/lib/mysql
    environment:
      - TZ=${TIMEZONE}
      - MYSQL_ROOT_PASSWORD=${FRESHRSS_DB_PASSWORD}
      - MYSQL_PASSWORD=${FRESHRSS_DB_PASSWORD}
      - MYSQL_DATABASE=${FRESHRSS_DB_DATABASE}
      - MYSQL_USER=${FRESHRSS_DB_USER}
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1

  freshrss:
    image: freshrss/freshrss:edge
    container_name: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - freshrss_data:/var/www/FreshRSS/data
      - freshrss_extensions:/var/www/FreshRSS/extensions
    environment:
      VIRTUAL_HOST: ${FRESHRSS_HOST}
      LETSENCRYPT_HOST: ${FRESHRSS_HOST}
      FRESHRSS_INSTALL: |-
        --api_enabled
        --base_url "https://${FRESHRSS_HOST}"
        --db-base ${FRESHRSS_DB_DATABASE}
        --db-host ${FRESHRSS_DB_HOST}
        --db-password ${FRESHRSS_DB_PASSWORD}
```

For some reference: #5008 #5648
