### ISSUE TITLE
[BUG] Translation broken since 1.22.0 

### ISSUE THREAD

**Issue by LiloBzH** [FreshRSS/FreshRSS#5724]
**Describe the bug**
FreshRSS stay in english
Change language in admin dont change the language

**Environment information (please complete the following information):**
- OS: Docker version
- FreshRSS version: 1.22.0

Thank you !

**Comment by math-GH** [comment]
I cannot reproduce your issue. For me it works fine (without having a Docker version).

Which docker version/repro do you use?

**Comment by LiloBzH** [comment]
Hi,

CT on promox with Docker version 24.0.6

Very classic

**Comment by LiloBzH** [comment]
I tried to change in config file

'language' => 'fr',

same thing !

**Comment by Alkarex** [comment]
I cannot reproduce either, with Docker. Do you use a docker-compose to start FreshRSS? If yes, please share the relevant parts.
It could be a sign of wrong volume mapping, or wrong rights.
Are you able to change & save any other settings?

**Comment by LiloBzH** [comment]
It's a stack

version: '3.3'
```
services:
  freshrss:
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Paris
      - CRON_MIN=*/10
    ports:
      - '3001:80'
    volumes:
      - 'data:/var/www/FreshRSS/data'
      - 'extensions:/var/www/FreshRSS/extensions'
      - 'api:/var/www/FreshRSS/p/api'
    restart: unless-stopped
    image: freshrss/freshrss
volumes:
  data:
  extensions:
  api:
```
