### ISSUE TITLE
[BUG] Issue with OIDC (The request fails due to a missing, invalid, or mismatching redirection URI (redirect_uri).)

### ISSUE THREAD

**Issue by foux** [FreshRSS/FreshRSS#5743]
**Describe the bug**
I've got an issue with OIDC and Authentik.
Each time I try to login, I receive the following error from Authentik : 
```
The request fails due to a missing, invalid, or mismatching redirection URI (redirect_uri).
```

The redirect URI I set in AUthentik is `https://mydomain.tld/i/oidc/`

And here is my Docker compose : 
```
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=longpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./postgres/15/data:/var/lib/postgresql/data
    networks:
      - freshrss

  freshrss:
    image: freshrss/freshrss
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - TZ=Europe/Paris
      - CRON_MIN=0,10,20,30,40,50
      - OIDC_ENABLED=1
      - OIDC_PROVIDER_METADATA_URL=https://myauthentik.tld/application/o/freshrss/.well-known/openid-configuration
      - OIDC_CLIENT_ID=client_id
      - OIDC_CLIENT_SECRET=client_secret
      - OIDC_X_FORWARDED_HEADERS=X-Forwarded-Port X-Forwarded-Proto X-Forwarded-Host
      - OIDC_SCOPES=openid email profile 

    volumes:
      - ./freshrss/data:/var/www/FreshRSS/data
      - ./freshrss/extensions:/var/www/FreshRSS/extensions
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.freshrss.rule=Host(`mydomain.tld`)
    networks:
      - web
      - freshrss

networks:
  web:
    name: web
    external: true
  freshrss:
```

**Expected behavior**
I should be redirected to FreshRSS home page

**Screenshots**
![CleanShot 2023-10-25 at 18 00 35](https://github.com/FreshRSS/FreshRSS/assets/246550/a63f2006-2041-4a86-8622-da2f2edcbf71)

**Environment information (please complete the following information):**
- Device: N.A
- OS: Docker
- Browser: Any
- FreshRSS version: 1.22.0
- Database version: Postgres 15
