### ISSUE TITLE
[BUG] Overall display page broken

### ISSUE THREAD

**Issue by derdide** [FreshRSS/FreshRSS#5801]
Hi
I just updated to 1.22 from 1.21 and the main display page is broken in multiple ways (see screenshot):
- no scrollbars anymore
- no categories structure on the left pane
- the name of the website is replaced by "example.net/" on all articles

I've cleared cache and cookies and tried again, same result. 
I've checked in the admin menu and in the DB, the data are still there

![Screenshot 2023-11-01 091058](https://github.com/FreshRSS/FreshRSS/assets/11669676/c63ca67e-ed0a-4791-b4fa-5dc69c87c67e)

Issue is similar on mobile, only difference is that the scrolling is possible through the touchscreen.

Installation check is all green:
 Your PHP version (7.4.3-4ubuntu2.19) is compatible with FreshRSS.
You have the cURL library.
You have PDO and at least one of the supported drivers (pdo_mysql, pdo_sqlite, pdo_pgsql).
You have the required library for regular expressions (PCRE).
You have the required library for character type checking (ctype).
You have the fileinfo library.
You have the required library to browse the DOM.
You have the JSON extension.
You have the recommended mbstring library for Unicode.
You have the ZIP extension. 
Permissions on the data directory are good.
Permissions on the cache directory are good.
Permissions on the users directory are good.
Permissions on the favicons directory are good.
Permissions on the tokens directory are good. 

Web server is Ubuntu 20.04.6 with Caddy webserver 2.6.4, DB is on Synology DSM 6.2.4-25556 Update 7 with MariaDB 5.5.68

**Comment by derdide** [comment]
Problem solved itself. Not sure what happened here.

**Comment by jhf2442** [comment]
Same issue here. How did it "solve itself" ?
Also for me, installation check is fine - docker setup, mariadb 10.3, php8.2
Tried logout/login, clean browser cache - did not help
force refresh of streams -> "there are no streams to refresh" !?!?!

**Comment by jhf2442** [comment]
cleaned /data/cache/*spc and restarted docker solved the problem

**Comment by Alkarex** [comment]
The `/data/cache/` content is completely unrelated to the issue,
@jhf2442 Could you share the relevant part of your `docker-compose.yml`, or command you use to run FreshRSS?

**Comment by derdide** [comment]
> How did it "solve itself" ? 

I don't know, sorry, I would have said. It just worked. There was a feed update (scheduled) in the meantime, this is the only thing that happened

**Comment by jhf2442** [comment]
@Alkarex I have to revise my statement, did too many updates yesterday and mixed things up a bit :-(
I actually run docker, but using 3 containers : nginx, php-fpm and mariadb.
(PHP) code is bind-mounted inside the nginx and php-fpm containers. I had removed all files besides the /data and then unpacked the zip from github with the new version

here's the docker-compose for these
```
services:
  freshrss_db:
    container_name: freshrss_db
    image: mariadb:10.3
    volumes:
      - ./db:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
    environment:
      MARIADB_ROOT_PASSWORD: xxxx
      MYSQL_DATABASE: freshrss
    restart: always
    networks:
      - default

  freshrss_app:
    container_name: freshrss_app
    image: nginx:1.23
    networks:
      - default
      - proxy
    volumes:
      - ./webroot:/webroot
      - ./site.conf:/etc/nginx/conf.d/site.conf:ro
      - ./logs:/var/logs
      - /etc/timezone:/etc/timezone:ro
    restart: always
    depends_on:
        - freshrss_db
        - freshrss_php

  freshrss_php:
    container_name: freshrss_php
    image: jhf/php:8.2-fpm
    networks:
      - default
    volumes:
      - ./webroot:/webroot
      - /etc/timezone:/etc/timezone:ro
    restart: always
```

the fpm image is my own, basically the original fpm along with some more PHP modules I install, as they are not contained in the original fpm image, and also composer
