### ISSUE TITLE
[BUG] ./Docker/entrypoint.sh: no such file or directory

### ISSUE THREAD

**Issue by yumeng426** [FreshRSS/FreshRSS#5807]
**Describe the bug**
After updating to the latest image, I was not able to access fresshrss,. The image does not run and shows the error. 
`freshrss     | exec ./Docker/entrypoint.sh: no such file or directory`

**To Reproduce**

This issue happens after I pulled the latest release, both 1.22.0 and 1.22.1. After I did `docker-compose pull` and `docker-compose up`, the error shows up. I was able to overcome the issue by reverting back to 1.21.0. 

**Expected behavior**
Expect to up the image and access the website. 
**Screenshots**

<img width="492" alt="image" src="https://github.com/FreshRSS/FreshRSS/assets/11802847/3c5a3c71-91f7-4ed5-bbc7-fe789bfc8d48">

**Environment information (please complete the following information):**
- Device: [N/A]
- OS: [Ubuntu 22.04.3 LTS (GNU/Linux 6.0.10-x86_64-linode158 x86_64)]
- Browser: [N/A]
- FreshRSS version: [1.22.0, 1.22.1]
- Database version: [e.g. Mysql 5.7]
- PHP version: [PHP 7.4]
- Installation type: [docker]

**Additional context**

**Comment by Alkarex** [comment]
Hello,
Can you please show the relevant section of your `docker-compose.yml`?
What version of Docker do you have?

Could you try to manually run the simplest manual version, e.g.:

```
docker run --rm freshrss/freshrss:1.22.1
```

**Comment by Alkarex** [comment]
And could you try with `freshrss/freshrss:1.22.1-alpine` ?

**Comment by yumeng426** [comment]
Thanks!

Here is my `docker-compose.yml`. I will try the manual version later. 
``` 
freshrss:
  image: freshrss/freshrss:1.21.0 (was latest)
  container_name: freshrss
  hostname: freshrss
  restart: unless-stopped
  logging:
    options:
      max-size: 10m
  volumes:
    - freshrss:/var/www/FreshRSS
    - freshrss_etc:/etc
    - freshrss_usr:/usr
  environment:
    - TZ=${TM_TZ}
    - CRON_MIN=9,25,45
   ```
