### ISSUE TITLE
[BUG] Greader API, newly created feed not correctly named.

### ISSUE THREAD

**Issue by martinrotter** [FreshRSS/FreshRSS#5866]
**Describe the bug**
Calling google reader API operation gives unexpected result. The feeds is indeed created with correct label, but title "bbb" is not given to newly created feed.

`http://<server>/api/greader.php/reader/api/0/subscription/edit?ac=subscribe&s=feed/https://servis.idnes.cz/rss.aspx&t=bbb&a=user/-/label/aaa`

This API call returns `HTTP/200` - feed is added but incorrectly named.

**Comment by Alkarex** [comment]
Thanks for the bug report 👍🏻 
Would you be able to try this fix? https://github.com/FreshRSS/FreshRSS/pull/5868 (not tested)
What client are you using?

**Comment by martinrotter** [comment]
Hi, I just test this via docker.

https://hub.docker.com/r/freshrss/freshrss

Maybe if you could merge into "edge" then I would be able to test via "edge" docker image.

**Comment by Alkarex** [comment]
To try a PR, if you can, try to instruct your Docker or docker-compose to build from git:

```yml
  freshrss:
    image: freshrss/freshrss:pr5866
    build:
      context: https://github.com/Alkarex/FreshRSS.git#api-title
      dockerfile: Docker/Dockerfile-Alpine
    ...
```

* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose.yml
* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#build-custom-docker-image
