### ISSUE TITLE
[BUG] Docker cron not working

### ISSUE THREAD

**Issue by meminens** [FreshRSS/FreshRSS#5894]
**Describe the bug**
FreshRSS does not auto update the feed with CRON_MIN variable set.

**To Reproduce**
Wait at least half an hour for feed auto-refresh. Nothing happens. I know this for sure because when I click the refresh button on the web interface, all of my feeds are updated and the number of unread articles increases.

**Expected behavior**
Auto update feed every 30 minutes.

**Screenshots**
N/A

**Environment information (please complete the following information):**
- Device: Mini PC Server, Intel N100
- OS: Debian 12
- Browser: Firefox 119
- FreshRSS version: 1.22.1
- Database version: SQlite
- PHP version: I don't know
- Installation type: Docker

**Additional context**
See docker compose below. I've tried both `2,32` and `'2,32'`. Same result.

```
version: "3.8"
services:
  freshrss:
    network_mode: bridge
    environment:
      - TZ=America/New_York
      - CRON_MIN=2,32
    image: freshrss/freshrss:latest
    container_name: freshrss
    ports:
      - 8080:80
    restart: always
    volumes:
      - /home/lab/.freshrss/data:/var/www/FreshRSS/data
      - /home/lab/.freshrss/extensions:/var/www/FreshRSS/extensions

```
