### ISSUE TITLE
help with extensions

### ISSUE THREAD

**Issue by huzzyz** [FreshRSS/FreshRSS#6083]
![Screenshot 2024-02-01 at 1 48 56 AM](https://github.com/FreshRSS/FreshRSS/assets/69323208/94573751-d446-4d12-820c-774d6127d522)
Trying to figure out how to make extensions work. I am using a docker instance.

```
version: '3.3'
services:
    linuxserver:
        container_name: freshrss
        network_mode: mine
        ports:
            - '9009:80'
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Dubai
        volumes:
            - ./freshrss:/config
            - ./freshrss/extensions:/var/www/FreshRSS/extensions
        restart: unless-stopped
        image: ghcr.io/linuxserver/freshrss
```

```
docker exec freshrss ls -alh /var/www/FreshRSS/extensions
total 72K
drwxr-sr-x 18 root root 4.0K Feb  1 01:18 .
drwxr-xr-x  3 root root 4.0K Feb  1 01:34 ..
drwxrwxrwx  3 root root 4.0K Feb  1 01:13 xExtension-ColorfulList
drwxrwxrwx  4 root root 4.0K Feb  1 01:13 xExtension-CustomCSS
drwxrwxrwx  4 root root 4.0K Feb  1 01:13 xExtension-CustomJS
drwxr-sr-x  3 root root 4.0K Feb  1 00:59 xExtension-FixedNavMenu
drwxrwxrwx  3 root root 4.0K Feb  1 01:13 xExtension-ImageProxy
drwxr-sr-x  3 root root 4.0K Feb  1 00:59 xExtension-KeepFolderState
drwxr-sr-x  3 root root 4.0K Feb  1 00:59 xExtension-MobileScrollMenu
drwxrwxrwx  7 root root 4.0K Feb  1 01:13 xExtension-QuickCollapse
drwxrwxrwx  3 root root 4.0K Feb  1 01:13 xExtension-ReadingTime
drwxrwxrwx  8 root root 4.0K Feb  1 01:13 xExtension-ShareByEmail
drwxr-sr-x  3 root root 4.0K Feb  1 00:59 xExtension-SmartMobileMenu
drwxrwxrwx  3 root root 4.0K Feb  1 01:13 xExtension-StickyFeeds
drwxrwxrwx  2 root root 4.0K Feb  1 01:13 xExtension-TTRSS_API
drwxrwxrwx  3 root root 4.0K Feb  1 01:13 xExtension-TitleWrap
drwxr-sr-x  3 root root 4.0K Feb  1 00:59 xExtension-TouchControl
drwxrwxrwx  3 root root 4.0K Feb  1 01:13 xExtension-showFeedID
```
Any help would be appreciated.
