### ISSUE TITLE
[Feature] Hide/Unhide sidebar

### ISSUE THREAD

**Issue by lamyergeier** [FreshRSS/FreshRSS#6119]
**Is your feature request related to a problem? Please describe.**
When I have a lot of new articles in a particular category, I would like to hide the sidebar so that I have more space to display the title of articles.

**Describe the solution you’d like**
Button to Hide/Unhide sidebar

**Describe alternatives you’ve considered**
-

**Additional context**
-

**Comment by Alkarex** [comment]
While waiting for better solutions, the "reader" view already hides the sidebar.
![image](https://github.com/FreshRSS/FreshRSS/assets/1008324/c5aac213-efc3-49fa-a1fe-f5b03b0c4895)

Related to https://github.com/FreshRSS/FreshRSS/discussions/5900

**Comment by lamyergeier** [comment]
I wanted to read the title in normal view (as I just want to scan the list to see which articles I want to read), as we can see that long titles are truncated

![image](https://github.com/FreshRSS/FreshRSS/assets/42092626/de43bdb1-9220-43e6-8e55-856da087f4c4)

**Comment by Alkarex** [comment]
See https://github.com/FreshRSS/FreshRSS/discussions/5900 and also the extension https://github.com/FreshRSS/Extensions/tree/master/xExtension-TitleWrap

**Comment by lamyergeier** [comment]
I did `docker run -it freshrss/freshrss sh` and got a shell to the container.  Then I did `cd extensions`. But how to copy the extension there?

**Comment by jesuslop** [comment]
Just bumping this. Came from ino{cough}reader and miss it dearly.

**Comment by Wytoo** [comment]
Bump, cause I too want to see the whole list unopened without the sidebar

**Comment by Inverle** [comment]
Use this UserCSS:
```css
:root {
  /* adjust if incorrectly aligned for your theme */
  --csidebar-top: 0;
  --csidebar-left: -5px;
}

@media screen and (orientation: portrait) {
	.show-sidebar, .close-sidebar {
	  display: none;
	}
}

@media screen and (orientation: landscape) {
	/* toggle sidebar */

	@media (prefers-color-scheme: dark) {
		:root.darkMode_auto:not(.theme_Pafat):not(.theme_Ansum):not(.theme_Swage):not(.theme_Mapco):not(.theme_Flat) {
			.show-sidebar img,
			.close-sidebar img {
				filter: invert(1) brightness(2);
			}
		}
	}
	
	:root.theme_Nord,
	:root.theme_Dark-pink,
	:root.theme_Dark,
	:root.theme_Alternative-Dark {
	  .show-sidebar img,
		.close-sidebar img {
			filter: invert(1) brightness(2);
		}
	}

	:root.theme_Flat,
	:root.theme_Mapco,
	:root.theme_Swage {
	  .close-sidebar img {
	    filter: invert(1) brightness(2);
	  }
	}
		
	.sidebar-container {
	  display: flex;
	  margin-left: 0.9rem;
	  gap: 1rem;
	}
	
	.close-sidebar:hover,
	.show-sidebar:hover {
	  cursor: pointer;
	  opacity: 0.5;
	}

	body.reader .show-sidebar, body.global .show-sidebar {
		display: none;
	}
	
	.show-sidebar {
	  position: fixed;
	  top: 0;
	  border-right: 1px dashed black;
	  padding: 0.3rem;
	}
	
	.show-sidebar img {
	  width: 24px;
	  height: 100vh;
	  transform: rotate(45deg);
	  user-select: none;
	}

	.close-sidebar img {
	  width: 100%;
	  height: 100%;
	  position: relative;
	  top: var(--csidebar-top);
	  left: var(--csidebar-left);
	}
	
	body.normal.hidden_sidebar #stream {
	  padding-left: 2.6rem;
	}
	
	#aside_feed,
	body.normal.hidden_sidebar nav#nav_entries {
	  width: 300px;
	  transition: width 0.8s;
	}
	
	body.normal.hidden_sidebar #aside_feed,
	body.normal.hidden_sidebar nav#nav_entries,
	body.normal.hidden_sidebar nav#nav_entries * {
	  transition: width 0.8s;
	  width: 0;
	}
	
	body.normal.hidden_sidebar #aside_feed *,
	body.normal:not(.hidden_sidebar) .show-sidebar {
	  display: none;
	}

	:root:not(.theme_Swage) .header {
		position: relative;
		z-index: 10;
	}
}


```

along with this UserJS:
```js
window.addEventListener("load", () => {
  // toggle sidebar

  const iconUrl = `
  data:image/svg+xml;base64,${btoa('<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#1f1f1f"><path d="m177-120-57-57 184-183H200v-80h240v240h-80v-104L177-120Zm343-400v-240h80v104l183-184 57 57-184 183h104v80H520Z"/></svg>')}
  `;

  const configureFeeds = document.querySelector("div.stick.configure-feeds");
  if (configureFeeds === null)
    return;
  
  configureFeeds.outerHTML = `
  <div class="sidebar-container">
    ${configureFeeds.outerHTML}
	  <div class="close-sidebar">
      <img src="${iconUrl}"></div>
    </div>
  </div>`;
  
  document.querySelector("nav.nav_menu").insertAdjacentHTML("afterEnd", `
  <div class="show-sidebar">
    <img src="${iconUrl}">
  </div>
  `);

  const showSidebar = document.querySelector(".show-sidebar");
  const closeSidebar = document.querySelector(".close-sidebar");

  showSidebar.onclick = closeSidebar.onclick = () => {
    document.body.classList.toggle("hidden_sidebar");
  };
});
```

implemented a few weeks ago, expect bugs - I plan to turn this into an extension soon
the CSS depends on #7559 (theme classes), only on edge branch right now (1.26.3 isn't released yet)
if you're not on edge, you may see the close icon wrongly displayed on dark themes
