### ISSUE TITLE
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#6163]
From the automated test pipeline:

![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/d57e8a5e-d2f0-4d2a-b9ae-211dcd69e9fb)

**Comment by Frenzie** [comment]
That's not for us exactly, but it should stop complaining when updated to v4.

https://github.com/FreshRSS/FreshRSS/blob/5aeab896e9042478e8de0c0989fe1be3b208d31f/.github/workflows/tests.yml#L32C13-L32C29

You could also consider creating a `dependabot.yml` with something like this and enabling it, see [here](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot).
```
version: 2
updates:
 - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
```
