### ISSUE TITLE
[BUG] http auth fails " cURL error 6: Could not resolve host"

### ISSUE THREAD

**Issue by robertolopezlopez** [FreshRSS/FreshRSS#6176]
**Describe the bug**
HTTP auth fails when username is an email address.

**To Reproduce**
1. Click 'subscription management'
2. Click 'add a feed' and provide a feed (in my case: https://www.ivoox.com/feed_fg_f1372665_filtro_1.xml)
3. Expand 'Advanced' section
4. Provide HTTP username (email address) and password
5. Click button 'Add' below
6. See error

**Expected behavior**
* The subscription should be added.
* Instead, I get an error `The newsfeed could not be added. Check FreshRSS logs for details. You can try force adding by appending #force_feed to the URL` (that workaround does not work).

**Screenshots**
<img width="798" alt="image" src="https://github.com/FreshRSS/FreshRSS/assets/1519467/f7968c23-ac80-4883-86a5-888413fdff83">

**Environment information (please complete the following information):**
- Device: web UI.
- OS: Debian 10 host - Docker instance (freshrss/freshrss)
- Browser: Firefox 123.0 64 bit Mac OS
- FreshRSS version:  1.23.1
- Database version: sqlite3
- PHP version: 8.2.7
- Installation type: ovhcloud VPS

**Additional context**
* From the logs: "2024-03-06 14:11:08 	A feed could not be found at `https://my.email@gmail.com/`; the status code is `200` and content-type is `text/html; charset=utf-8` [https://www.ivoox.com/feed_fg_f1372665_filtro_1.xml]"
* docker-compose.yaml:
```yaml
version: "2.4"

services:

  freshrss:
    image: freshrss/freshrss:latest
    build:
      context: https://github.com/FreshRSS/FreshRSS.git#latest
      dockerfile: Docker/Dockerfile-Alpine
    container_name: freshrss
    ports:
      - "8080:80"
    hostname: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - /docker/freshrss/volumes/data:/var/www/FreshRSS/data
      - /docker/freshrss/volumes/extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: Europe/Warsaw
      CRON_MIN: '3,33'
```

**Comment by Alkarex** [comment]
Hello,
Would you be able to test https://github.com/FreshRSS/FreshRSS/pull/6177 ?

```yml
  freshrss:
    image: freshrss/freshrss:6177
    build:
      context: https://github.com/Alkarex/FreshRSS.git#CURLOPT_USERPWD
      dockerfile: Docker/Dockerfile-Alpine
    ...
```

* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose.yml
* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#build-custom-docker-image
