### ISSUE TITLE
[BUG] Fail to disable authentication token

### ISSUE THREAD

**Issue by Zebartin** [FreshRSS/FreshRSS#6184]
**Describe the bug**
Fail to disable authentication token in profile management

**To Reproduce**
1. Go to 'Profile management'
2. Set any authentication token
3. Try setting token to blank and submit
4. Token does not change

**Expected behavior**
Token should be disabled

**Screenshots**
None

**Environment information (please complete the following information):**
- OS: Ubuntu 20.04
- Browser: Chrome
- FreshRSS version: 1.23.1
- Database version: default, should be sqlite
- PHP version: 8.2.7
- Installation type: docker compose

**Additional context**
None

**Comment by Alkarex** [comment]
Please try this patch https://github.com/FreshRSS/FreshRSS/pull/6185

```yml
  freshrss:
    image: freshrss/freshrss:6185
    build:
      context: https://github.com/Alkarex/FreshRSS.git#fix-token
      dockerfile: Docker/Dockerfile-Alpine
    ...
```

* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose.yml
* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#build-custom-docker-image
