### ISSUE TITLE
[Bug] Table styles should not affect the content

### ISSUE THREAD

**Issue by nicofrand** [FreshRSS/FreshRSS#6263]
### Describe the bug

When an article content includes tables for its layout, the article's display is really broken (at least with Nord theme) due to margins/paddings/borders added to `table` directly (even on `.content`).

See 
![image](https://github.com/FreshRSS/FreshRSS/assets/3419050/e3aaa761-a12b-45eb-a69c-84e111dca347)

### To Reproduce

Unfortunately the feed on which I reproduce is private, but you can try with such a layout I guess:

![image](https://github.com/FreshRSS/FreshRSS/assets/3419050/c51a63cb-be60-435d-bb08-6dc319147118)

### Expected behavior

Content's layout is not altered.

### FreshRSS version

1.23.1

### Environment information

- Database version: [e.g. Mysql 5.7, SQLite]
- PHP version: [e.g. PHP 8.1]
- Installation type: [e.g. Docker, Docker image source, git, Yunohost]
-Web server type: [e.g. Apache, nginx]
- Device: [e.g. iPhone13]
- OS: [e.g. Ubuntu 22.04, Win10, MacOS14]
- Browser: Firefox 126

**Comment by nicofrand** [comment]
A bit better with the CSS below:

```css
.content table, .content tr, .content th, .content td {
  margin: initial;
  border: initial;
  padding: initial;
 float: none;
}
```
