### ISSUE TITLE
[Bug] Duplicates not getting removed from BBC News feed

### ISSUE THREAD

**Issue by johnsturgeon** [FreshRSS/FreshRSS#6521]
### Describe the bug

The BBC World News feed is a bit of a mess, which is actually *why* I started using FreshRSS recently, specifically so I could filter duplicates.

I'm having the same issue happening even after FreshRSS

https://feeds.bbci.co.uk/news/world/rss.xml

<img width="1012" alt="image" src="https://github.com/FreshRSS/FreshRSS/assets/9746310/ef0d78eb-e5a8-4a6e-a0ca-14eaa502b531">

I have indeed set the filter duplicates setting:
<img width="714" alt="image" src="https://github.com/FreshRSS/FreshRSS/assets/9746310/17a62708-bafd-451f-9c43-c73e90443b7a">

### To Reproduce

1. Add feed: https://feeds.bbci.co.uk/news/world/rss.xml
2. Turn on "mark article read ...1000..."
3. Wait a few days

### Expected behavior

I expect no duplicate articles

### FreshRSS version

1.24.0

### Environment information

- Database version: Sqlite

Here's my docker compose

```yaml
version: "2.4"
volumes:
  data:
  extensions:
services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - data:/var/www/FreshRSS/data
      - extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: US/Pacific
      CRON_MIN: '3,33'
      LISTEN: 0.0.0.0:80
      TRUSTED_PROXY: 0
```

- Device: [e.g. iPhone13]
- OS: [e.g. Ubuntu 22.04, Win10, MacOS14]
- Browser: [e.g. Firefox 124]

**Comment by Alkarex** [comment]
Could you please check some tips here https://github.com/FreshRSS/FreshRSS/discussions/6101 and let us know if that is not sufficient, especially if you can identify a pattern more precisely

**Comment by johnsturgeon** [comment]
> Could you please check some tips here #6101 and let us know if that is not sufficient, especially if you can identify a pattern more precisely

Thank you for the pointer, I updated a couple settings, I think this is an issue of them 're-publishing' old articles, so I changed the purge settings, we'll see how it behaves over the next couple days.

Do you mind if I keep this open until I see it resolve itself?  I'll come back in a few days and close it if it's resolved.

**Comment by johnsturgeon** [comment]
Issue did not resolve itself.

Here are some bits of info -- screen shot of feed with the article:
[German football coach condemns 'racist' TV survey](https://www.bbc.com/news/articles/cw4437m0gkpo)
[German football coach condemns 'racist' TV survey](https://www.bbc.com/news/articles/cw4437m0gkpo)
and
[Heat kills more than 50 people in India in three days](https://www.bbc.com/news/articles/cprrv9zp8wyo)
[Heat kills more than 50 people in India in three days](https://www.bbc.com/news/articles/cprrv9zp8wyo)
in there twice

<img width="1141" alt="image" src="https://github.com/FreshRSS/FreshRSS/assets/9746310/407ccc23-4cc7-42d1-8493-6eb3760c9d9d">

I have the following settings:

<img width="677" alt="image" src="https://github.com/FreshRSS/FreshRSS/assets/9746310/273b1609-77b5-4bf4-b5fc-85341616e21d">

<img width="579" alt="image" src="https://github.com/FreshRSS/FreshRSS/assets/9746310/4d644f6c-7cd2-45f7-bcf1-f6ec4f007e8a">

Log error
<img width="762" alt="image" src="https://github.com/FreshRSS/FreshRSS/assets/9746310/86426cb7-6f0a-45a7-b2ff-02164e6d9623">


I'm not sure what else I can do to help debug the situation.

**Comment by Alkarex** [comment]
So this seems to be a case 4 of https://github.com/FreshRSS/FreshRSS/discussions/6101#discussioncomment-8479032, i.e. *Feeds, with broken GUIDs (non-unique GUIDs)*
But the option to *mark an article as read if an identical title already exists* seems to fail

**Comment by Alkarex** [comment]
P.S. What options do you have for that specific feed (your screenshots seems to be at global level)

**Comment by johnsturgeon** [comment]
> So this seems to be a case 4 of [#6101 (comment)](https://github.com/FreshRSS/FreshRSS/discussions/6101#discussioncomment-8479032), i.e. _Feeds, with broken GUIDs (non-unique GUIDs)_
> But the option to _mark an article as read if an identical title already exists_ seems to fail

**Correct**

**Comment by johnsturgeon** [comment]
> P.S. What options do you have for that specific feed (your screenshots seems to be at global level)

Nope, those were specific for the BBC feed

**Comment by Alkarex** [comment]
Could you please test this patch? https://github.com/FreshRSS/FreshRSS/pull/6536
It might not be enough, but it should at least help with one case.

To test a PR, you need to point your Docker or Docker Compose to the right PR, as such:

```yml
  freshrss:
    image: freshrss/freshrss:6536
    build:
      context: https://github.com/Alkarex/FreshRSS.git#array_fill_keys
      dockerfile: Docker/Dockerfile-Alpine
    ...
```

* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose.yml
* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#build-custom-docker-image
