### ISSUE TITLE
[Bug] Docker Installation Fever API Favicons Error

### ISSUE THREAD

**Issue by wasabipesto** [FreshRSS/FreshRSS#6573]
### Describe the bug

Calling the fever API requesting favicons causes an error in 1.24.1. From the logs:

`[Tue Jun 18 18:24:52.753539 2024] [php:error] [pid 2656] [client 172.19.0.1:34546] PHP Fatal error:  Uncaught Error: Call to undefined function exif_imagetype() in /var/www/FreshRSS/p/api/fever.php:367\nStack trace:\n#0 /var/www/FreshRSS/p/api/fever.php(206): FeverAPI->getFavicons()\n#1 /var/www/FreshRSS/p/api/fever.php(575): FeverAPI->process()\n#2 {main}\n  thrown in /var/www/FreshRSS/p/api/fever.php on line 367
172.19.0.1 - - [18/Jun/2024:18:24:52 -0400] "POST /api/fever.php?api&favicons HTTP/1.1" 500 - "-" "python-requests/2.28.2"`

I am running this from the provided default docker image. My docker compose:

```
  freshrss:
    image: freshrss/freshrss:1.23.1
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    ports:
      - 8524:80
    volumes:
      - /opt/freshrss/data:/var/www/FreshRSS/data
      - /opt/freshrss/extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: America/New_York
      CRON_MIN: 13,43
```

Rolling back to 1.23.1 fixes this.

### To Reproduce

1. Call `/api/fever.php?api&favicons` with proper API key
2. Get a 500 error

### Expected behavior

The output on docker image 1.23.1 returns the icons for each feed per the fever API spec, as expected.

### FreshRSS version

1.23.1 is ok, 1.24.1 fails

### Environment information

- Database version: Docker-included default (SQLite)
- PHP version: Docker-included default (8.2?)
- Installation type: Docker (compose, above)
- Web server type: Docker-included default (Apache)
- Device: Any
- OS: Any
- Browser: N/A
