### ISSUE TITLE
[Bug] Unable to load extension list over IPv6

### ISSUE THREAD

**Issue by mlabuhn** [FreshRSS/FreshRSS#6744]
### Describe the bug

When attempting to view extensions in the GUI, FreshRSS attempts to [load available extensions](https://github.com/FreshRSS/FreshRSS/blob/9b2bb50e410607fc67ecafbdaf85ffc4830723e2/app/Controllers/extensionController.php#L45):

```
protected function getAvailableExtensionList(): array {
	$extensionListUrl = 'https://raw.githubusercontent.com/FreshRSS/Extensions/master/extensions.json';
	$json = @file_get_contents($extensionListUrl);
	...
```

I have not tested this across other installation types, but in my environment, this always fails if https://raw.githubusercontent.com resolves to an IPv6 address. Logging into the same Kubernetes pod, and installing some additional tools, I was able to verify that I can reach that address over IPv6 (ping succeeds, curl is able to download the file over IPv6), and also that it is the `file_get_contents` call that fails.

Disabling IPv6 globally, or overriding DNS resolution for that particular address to force it onto IPv4 A records only is a viable workaround.

### To Reproduce

1. Go to _Configuration -> Extensions_
2. Wait
3. Connection times out

### Expected behavior

Extensions settings page loads.

### FreshRSS version

1.23.1

### Environment information

- Database version: PostgreSQL 14.1.0
- PHP version: PHP 8.2.7
- Installation type: Kubernetes, based on official Docker image version 1.23.1
- Web server type: Apache

**Comment by Alkarex** [comment]
Could you please try both our Debian and Alpine-based images?

**Comment by mlabuhn** [comment]
I have tried both images now, and they are both showing the same behaviour.

I used the latest stable images, so 1.24.2 and 1.24.2-alpine.

For reference, I am adding host aliases to the deployment as a workaround:

```
  hostAliases:
    - ip: 185.199.110.133
      hostnames:
        - raw.githubusercontent.com
```

**Comment by Alkarex** [comment]
Would you be able to test this patch to use curl instead of `file_get_contents`:
https://github.com/FreshRSS/FreshRSS/pull/6767

Example for docker compose, to be adapted:

```yml
  freshrss:
    image: freshrss/freshrss:6767
    build:
      context: https://github.com/Alkarex/FreshRSS.git#curl-extensions-list
      dockerfile: Docker/Dockerfile-Alpine
    ...
```

* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose.yml
* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#build-custom-docker-image
