### ISSUE TITLE
Error during context user init! error when launching after upgrading

### ISSUE THREAD

**Issue by Elmeromoto** [FreshRSS/FreshRSS#7040]
### Describe the bug

Running via portainer on a synology device.  When watchtowner recently re-pulled the image I started getting the error "Error during context user init!" when navigating to freshrss.  I also updated the compose file permissions from 1026/100 to a custom docker group, which I thought caused the issue, but re-setting everything during testing with chmod 777 didn't fix it. 

Logs on freshrss return the following:

```
192.168.xxx - - [30/Nov/2024:14:18:33 -0800] "GET /i/?rid=6423d2fd427b8 HTTP/1.1" 200 31 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:132.0) Gecko/20100101 Firefox/132.0"

192.168.xxx - - [30/Nov/2024:14:21:15 -0800] "GET /i/?rid=6423d2fd427b8 HTTP/1.1" 200 31 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:132.0) Gecko/20100101 Firefox/132.0"

[mpm_prefork:notice] [pid 1:tid 1] AH00169: caught SIGTERM, shutting down

[mpm_prefork:notice] [pid 1:tid 1] AH00163: Apache/2.4.62 (Debian) configured -- resuming normal operations

[core:notice] [pid 1:tid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

192.168.xxx- - [30/Nov/2024:14:28:44 -0800] "GET /i/?rid=6423d2fd427b8 HTTP/1.1" 200 31 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:132.0) Gecko/20100101 Firefox/132.0"

192.168.xxx- - [30/Nov/2024:14:29:30 -0800] "GET /i/?rid=6423d2fd427b8 HTTP/1.1" 200 31 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:132.0) Gecko/20100101 Firefox/132.0"
```

Here's the docker compose:
```

`services:
  freshrss:
    image: freshrss/freshrss
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    ports:
       - '4228:80'
    logging:
      options:
        max-size: 10m
    volumes:
      - /volume3/docker/freshrss/data:/var/www/FreshRSS/data
      - /volume3/docker/freshrss/extensions:/var/www/FreshRSS/extensions
      - /volume3/docker/freshrss/config:/var/www/FreshRSS/config
    environment:
      - PUID=1033
      - PGID=65540
      - TZ=America/Los_Angeles
      - DB_HOST=freshrss-db
      - DB_BASE=freshrss-dp
      - DB_PASSWORD=xxxxxxxx
      - DB_USER=freshrss-dp
      - CRON_MIN=25,55
    depends_on:
      - freshrss-db

  freshrss-db:
    image: postgres:14
    container_name: freshrss-db
    hostname: freshrss-db
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - /volume3/docker/freshrss/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: freshrss-dp
      POSTGRES_USER: freshrss-dp
      POSTGRES_PASSWORD: xxxxxxxx
      
`
```

### To Reproduce

[restart the docker container, using the above compose file).

### FreshRSS version

1.24.3

### Environment information

- Installation type: [docker]
- Device: [synology]

**Comment by Alkarex** [comment]
Could you please try with `freshrss/freshrss:edge` ?

**Comment by Alkarex** [comment]
This Docker Compose contains several things which are not from our documentation.
See https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#docker-compose

Try for instance the following, to start with:

```yaml
services:
  freshrss:
    image: freshrss/freshrss
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    ports:
       - '4228:80'
    logging:
      options:
        max-size: 10m
    volumes:
      - /volume3/docker/freshrss/data:/var/www/FreshRSS/data
      - /volume3/docker/freshrss/extensions:/var/www/FreshRSS/extensions
    environment:
      - TZ=America/Los_Angeles
      - CRON_MIN=25,55
```
