### ISSUE TITLE
unable to pull the latest version from dockerhub

### ISSUE THREAD

**Issue by yumeng426** [FreshRSS/FreshRSS#7146]
Can I get some help on updating the local version? Thanks!

My current version works fine and refreshes feeds. I tried to pull the latest version from docker hub. I used `docker compose pull` and then `docker compose up -d` to refresh. No obvious error is reported on the two operations. However, my local version is always on 1.24.1. I also tried to change my image from `image: freshrss/freshrss:latest` to `image: freshrss/freshrss:1.25.0` and got no luck. 

Here is my `docker-compose.yml`

```
services:  
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    build:
      # Pick #latest (stable release) or #edge (rolling release) or a specific release like #1.21.0
      context: https://github.com/FreshRSS/FreshRSS.git#latest
      dockerfile: Docker/Dockerfile-Alpine
    logging:
      options:
        max-size: 10m
    volumes:
      - freshrss:/var/www/FreshRSS
      # Recommended volume for FreshRSS persistent data such as configuration and SQLite databases
      # - freshrss_data:/var/www/FreshRSS/data
      # Optional volume for storing third-party extensions
      # - freshrss_extensions:/var/www/FreshRSS/extensions
      - freshrss_etc:/etc
      - freshrss_usr:/usr
    environment:
      - TZ=${TM_TZ}
      - CRON_MIN=9,25,45
    cap_drop:
      - all
  ```
