### ISSUE TITLE
[Bug] OIDC not working with Authentik (redirect_uri error)

### ISSUE THREAD

**Issue by thibmart1** [FreshRSS/FreshRSS#7255]
### Describe the bug

I try to set up OIDC authentication with Authentik following the documentation (https://freshrss.github.io/FreshRSS/en/admins/16_OpenID-Connect-Authentik.html) but keep struggling with a redirect_uri error whenever I try to connect into the app.

I use FreshRSS behind a caddy reverse-proxy and I had set up Authentik with other apps successfully before.

I've tried nearly all combinations of redirect URIs in Authentik provider setup for FreshRSS (see additional context for the complete config):
```
https://rss.mydomain.com:443/i/oicd/
https://rss.mydomain.com:80/i/oicd/
https://rss.mydomain.com:8020/i/oicd/
http://<ip of server with FreshRSS>:8020/i/oicd/
```

Also, I'm trying to do this on an already-installed FreshRSS instance. I don't believe it is stated somewhere in the doc it can't be done, but I'm not sure so...

Thank you for your help!

### To Reproduce

1. Set up OIDC authentication as per https://freshrss.github.io/FreshRSS/en/admins/16_OpenID-Connect-Authentik.html and https://freshrss.github.io/FreshRSS/en/admins/16_OpenID-Connect.html
2. Try to log in into FreshRSS

### FreshRSS version

1.25.0

### System information

- Database version: SQLite
- PHP version: 8.2.26
- Installation type: Docker with native image
- Web server type: caddy 2.9.1-alpine
- Device: Custom NAS
- OS: Debian 12
- Browser: Firefox 134

### Additional context

FreshRSS docker compose setup:
```
---
services:
  app:
    image: docker.io/freshrss/freshrss:1.25.0
    container_name: freshrss
    environment:
      TZ: Europe/Paris
      CRON_MIN: "*/10"
      TRUSTED_PROXY: <ip of the server with caddy>
      OIDC_ENABLED: 0
      OIDC_PROVIDER_METADATA_URL: https://auth.mydomain.com/application/o/freshrss/.well-known/openid-configuration
      OIDC_CLIENT_ID: clientid
      OIDC_CLIENT_SECRET: clientsecret
      OIDC_CLIENT_CRYPTO_KEY: cryptokey
      OIDC_REMOTE_USER_CLAIM: preferred_username
      OIDC_SCOPES: openid email profile
      OIDC_X_FORWARDED_HEADERS: X-Forwarded-Host X-Forwarded-Proto
    volumes:
      - /volume/freshrss/data:/var/www/FreshRSS/data
      - /volume/freshrss/extensions:/var/www/FreshRSS/extensions
    ports:
      - 8020:80
    restart: always
```

FreshRSS config:
```
<?php
return array (
  'environment' => 'production',
  'salt' => 'randomsalt',
  'base_url' => 'https://rss.mydomain.com/',
  'auto_update_url' => 'https://update.freshrss.org',
  'language' => 'en',
  'title' => 'FreshRSS',
  'meta_description' => '',
  'logo_html' => '',
  'default_user' => 'admin',
  'force_email_validation' => false,
  'allow_anonymous' => false,
  'allow_anonymous_refresh' => false,
  'auth_type' => 'http_auth',
  'http_auth_auto_register' => true,
  'http_auth_auto_register_email_field' => '',
  'api_enabled' => true,
  'unsafe_autologin_enabled' => false,
  'simplepie_syslog_enabled' => true,
  'pubsubhubbub_enabled' => true,
  'allow_robots' => false,
  'allow_referrer' => false,
  'nb_parallel_refresh' => 10,
  'limits' => 
  array (
    'cookie_duration' => 7776000,
    'cache_duration' => 800,
    'cache_duration_min' => 60,
    'cache_duration_max' => 86400,
    'timeout' => 20,
    'max_inactivity' => 9223372036854775807,
    'max_feeds' => 131072,
    'max_categories' => 16384,
    'max_registrations' => 1,
  ),
  'curl_options' => 
  array (
  ),
  'db' => 
  array (
    'type' => 'sqlite',
    'host' => '',
    'user' => '',
    'password' => '',
    'base' => '',
    'prefix' => '',
    'connection_uri_params' => '',
    'pdo_options' => 
    array (
    ),
  ),
  'mailer' => 'mail',
  'smtp' => 
  array (
    'hostname' => '',
    'host' => 'localhost',
    'port' => 25,
    'auth' => false,
    'auth_type' => '',
    'username' => '',
    'password' => '',
    'secure' => '',
    'from' => 'root@localhost',
  ),
  'extensions_enabled' => 
  array (
  ),
  'extensions' => 
  array (
  ),
  'disable_update' => true,
  'trusted_sources' => 
  array (
    0 => '127.0.0.0/8',
    1 => '::1/128',
  ),
);
```

Authentik provider setup for FreshRSS:
- Client type: `Confidential`
- Client ID: `clientid`
- Client secret `clientsecret`
- Redirect URIs:
```
https://rss.mydomain.com/i/oicd/
https://rss.mydomain.com:443/i/oicd/
```
- Signing Key: `authentik Self-signed Certificate`

Caddy setup for FreshRSS:
```
rss.mydomain.com {
        reverse_proxy <ip of server with FreshRSS>:8020
}
```
