### ISSUE TITLE
[Bug] SQlite file not created with docker-compose

### ISSUE THREAD

**Issue by pollocluck** [FreshRSS/FreshRSS#7321]
### Describe the bug

When I try to set up freshrss it allows me to add feeds, but the database is 2.50 MB which only includes my profile. I searched the data directory for the sqlite database file, but the directory is empty. Here is my compose file:

```yml
services:
  freshrss:
   image: freshrss/freshrss:latest
    container_name: freshrss
    network_mode: 'host'
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      # Recommended volume for FreshRSS persistent data such as configuration and SQLite databases
      - /home/user/snap/docker/freshrss/data:/data
      # Optional volume for storing third-party extensions
      - /home/user/snap/docker/freshrss/extensions:/extensions
    #ports:
      # If you want to open a port 8080 on the local machine:
      #- "8080:80"
    environment:
      # A timezone http://php.net/timezones (default is UTC)
      TZ: America/Los_Angeles
      # Cron job to refresh feeds at specified minutes
      CRON_MIN: '2,32'
      # 'development' for additional logs; default is 'production'
      FRESHRSS_ENV: development
      # Optional advanced parameter controlling the internal Apache listening port
      #LISTEN: 0.0.0.0:80
      # Optional parameter, remove for automatic settings, set to 0 to disable,
      # or (if you use a proxy) to a space-separated list of trusted IP ranges
      # compatible with https://httpd.apache.org/docs/current/mod/mod_remoteip.html#remoteipinternalproxy
      # This impacts which IP address is logged (X-Forwarded-For or REMOTE_ADDR).
      # This also impacts external authentication methods;
      # see https://freshrss.github.io/FreshRSS/en/admins/09_AccessControl.html
      #172.16.0.1/12 192.168.0.1/16
      TRUSTED_PROXY: 0
      # Optional parameter, set to 1 to enable OpenID Connect (only available in our Debian image)
      # Requires more environment variables. See https://freshrss.github.io/FreshRSS/en/admins/16_OpenID-Connect.html
      OIDC_ENABLED: 0
```

### To Reproduce

1. Pull the latest version and run "docker compose up -d"
2. Set up the container and select SQLite
3. Go to the data directory inside the freshrss directory

### FreshRSS version

latest

### System information

- Database version: SQLite,
- PHP version: [e.g. PHP 8.2]
- Installation type: Docker Compose (hub.docker.com)
- Web server type: default
- Device: Windows 11
- OS: Ubuntu server 24.01 
- Browser: Firefox 134.02
