### ISSUE TITLE
Unable to connect to API from an external network with FreshRSS behind NGINX reverse proxy

### ISSUE THREAD

**Issue by Landrin201** [FreshRSS/FreshRSS#7353]
Hello! I'm using the official docker image with the following docker-compose:

```
services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      # Recommended volume for FreshRSS persistent data such as configuration and SQLite databases
      - /storage/rss/data:/var/www/FreshRSS/data
      # Optional volume for storing third-party extensions
      - /storage/rss/extensions:/var/www/FreshRSS/extensions
    ports:
      - "12345:80"
      - "12346:443"
    environment:
      TZ: America/New_York
      # Cron job to refresh feeds at specified minutes
      CRON_MIN: '2,32'
      # 'development' for additional logs; default is 'production'
      FRESHRSS_ENV: development
      FRESHRSS_USER: |-
        --api-password ${FRESH_RSS_ADMIN_API_PASSWORD}
        --email ${ADMIN_EMAIL}
        --language en
        --password ${ADMIN_PASSWORD}
        --user admin
  freshrss-db:
    image: postgres:alpine
    hostname: 'freshrss-postgres'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
      - POSTGRES_USER=user
    restart: always
    volumes:
      - /storage/rss/database:/var/lib/postgresql/data
    ports:
      - 12347:5432
```

I have a CNAME set up in cloudflare for rss.example.com. I also have my rss.example.com entry set up in NGINX Proxy Manager, with its protocol set to HTTP and the correct internal IP/port set. I can confirm that Fresh RSS is in fact working behind the reverse proxy; if I use a browser to go to rss.example.com, the web version of FreshRSS works just fine. I can log in and use it normally.

I'm trying to set up FeedMe on my phone, since I'm primarily going to be using my phone to look at my feeds and would like to have a dedicated app for it. But when I try to connect to FreshRss and send it my API password/username through FeedMe's ui, it says "Authentication error or expired."

If I then go to the API log in /data/users/_ all I see is the following:

```
Sat, 22 Feb 2025 17:35:06 -0500] [warning] --- GReaderAPI::unauthorized
[Sat, 22 Feb 2025 17:35:06 -0500] [debug] --- GReaderAPI::unauthorized Array
(
    [date] => 2025-02-22T17:35:06-05:00
    [headers] => Array
        (
            [Host] => rss.example.com
            [X-Forwarded-Scheme] => https
            [X-Forwarded-Proto] => https
            [X-Forwarded-For] => MY_IP_ADDRESS
            [X-Real-IP] => IP_ADDRESS
            [cf-ray] => IDK if I should obscure this so I am
            [cf-visitor] => {"scheme":"https"}
            [cdn-loop] => cloudflare; loops=1
            [accept-encoding] => gzip, br
            [cf-ipcountry] => US
            [user-agent] => FeedMe/3.16 (com.seazon.feedme; build:206; Android SDK 35)
            [cf-connecting-ip] => PHONE_IP_ADDRESS
        )

    [_SERVER] =>
    [_GET] => Array
        (
            [output] => json
        )

    [_POST] => Array
        (
        )

    [_COOKIE] => Array
        (
        )

    [INPUT] =>
)
```

When I look at other issues on this project, I see a LOT more information in that [_SERVER] tag, but I have no idea how to get it to show up here. My environment in config.php is set to development so I'm not sure why I'm not seeing more in these logs.

If I navigate to http://rss.example.com/api, the Google Reader section reads:

`WARN: Probable invalid base URL in ./data/config.php`

If I go look at config.php, I can see that my base_url is set to http://rss.example.com. 

I'm really not sure what to do from here, so I figured I'd post to ask for help.
