### ISSUE TITLE
[Bug] States not saved for Queries on 1.26.0

### ISSUE THREAD

**Issue by piotrkustal** [FreshRSS/FreshRSS#7371]
### Describe the bug

Since 1.26.0 upgrade, already created queries don't remember it's states. E.g. if state "Show read" was unchecked, and now you check it on and Save it's still unchecked after refresh.

It's same for any state - read,unread,favourite etc.

### To Reproduce

1. Go to User Queries
2. Click on any User Query
3. Then change state "see read" "see unread"
4. Save
5. Refresh same query
6. State will not be remembered

### FreshRSS version

1.26.0

### System information

- Database version: [SQLite,]
- PHP version: [ PHP 8.2]
- Installation type: [Docker]
- Web server type: [nginx]
- OS: [ Win11]
- Browser: [Chrom 133]

**Comment by Fletch-99** [comment]
I can confirm this bug.

**Comment by Alkarex** [comment]
Thanks for the bug report.
Could you please test https://github.com/FreshRSS/FreshRSS/pull/7400 ?

@piotrkustal To test this branch, you can modify your Docker Compose like so:

```yml
  freshrss:
    image: freshrss/freshrss:7400
    build:
      context: https://github.com/Alkarex/FreshRSS.git#fix-paramArray
      dockerfile: Docker/Dockerfile-Alpine
    ...
```

* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose.yml
* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#build-custom-docker-image
