### ISSUE TITLE
[Bug] Docker image requires write permissions to /tmp but it doesnt have those

### ISSUE THREAD

**Issue by kausar007** [FreshRSS/FreshRSS#7373]
### Describe the bug

I tried both 1.25.0 and 1.26.0 versions with new installation and already configured instance. New installation does not go further and says to resolve the issue. Alpine version of the image doesnt even show the message but cant go beyond step 1. The logs however do show that its because of missing write access to /tmp.

Current instance did not refresh any feeds until i did `chmod 777 /tmp`.

### To Reproduce

1. Pull image from Docker hub and run it
2. Go to web ui and click next on step 1
3. See error

### Expected behavior

New installation should work and should have access to /tmp
Current installation should refresh feeds

### FreshRSS version

1.26.0

### System information

- Database version: SQLite
- PHP version: 8.2.26
- Installation type: Docker
- OS: Ubuntu 22.04.5 LTS
- Browser: Firefox

**Comment by Alkarex** [comment]
Hello,
Please show your docker compose, docker run, or equivalent configuration.

**Comment by kausar007** [comment]
Here is the docker compose file

```yaml
services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    hostname: freshrss
    restart: "unless-stopped"
    volumes:
      - /home/freshrss/data:/var/www/FreshRSS/data
      - /home/freshrss/extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: Europe/London
      CRON_MIN: '27,57'
    labels:
      - traefik.enable=true
      - traefik.http.services.freshrss.loadbalancer.server.port=80
      - traefik.http.routers.freshrss.rule=Host(`freshrss.example.com`)
      - traefik.http.routers.freshrss.service=freshrss
```

When I tried with new installation I just pointed to different volume dir `/home/freshrss2`
