### ISSUE TITLE
[Bug] Docker automatic Healthcheck seems to be missing

### ISSUE THREAD

**Issue by Pugglewuggle** [FreshRSS/FreshRSS#7377]
### Describe the bug

From pull requests https://github.com/FreshRSS/FreshRSS/pull/2438 and https://github.com/FreshRSS/FreshRSS/pull/2455 and subsequently https://github.com/FreshRSS/FreshRSS/pull/2451 it appears that an automatic healthcheck was implemented for Docker images a long time ago, but as of release 1.26.0 the FreshRSS container does not report a status other than "Running" even if things are working correctly. Furthermore, running `docker inspect <container_name>` does not show a Healthcheck element anywhere in the JSON.

### To Reproduce

1. Deploy FreshRSS 1.26.0 in Docker.
2. After the container is up and running, run `docker inspect <container_name> | grep Healthcheck`
3. There is no Healthcheck element present in the JSON

### Expected behavior

It appears there should be a built-in Healthcheck in the image from past correspondence.

### FreshRSS version

1.26.0

### System information

- Database version: PostgreSQL 17
- PHP version: PHP 8.2
- Installation type: Dockerhub image

**Comment by Alkarex** [comment]
Hello,
It does not look like providing a `healthcheck` at Dockerfile level is so popular (anymore).

On our side, it has been difficult to find a default `healthcheck` that made sense, and it ended up being more negative than positive (unreliable on some setups, energy consuming, delaying the service after restart when used with a proxy such as Traefik that is using the `healthcheck` information).

Consequently, `healthcheck` was removed in FreshRSS 1.17.0
* https://github.com/FreshRSS/FreshRSS/pull/3161 
* https://github.com/FreshRSS/FreshRSS/issues/3085
* https://github.com/FreshRSS/FreshRSS/issues/3870

However, it is possible to add a `healthcheck` that makes sense for you in your docker compose or equivalent:
https://docs.docker.com/reference/compose-file/services/#healthcheck

PR welcome to add an example to our docker compose documentation (commented out by default):
* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#docker-compose
* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose.yml

**Comment by hozza** [comment]
@Alkarex Do you have a recommended endpoint to test for health in a docker compose healthcheck? Something that tests database connection etc.

I'd usually run something like this in docker compose files, where "/health" will send HTTP status of 200 on OK, but 400+ on any sort of unhealthy error that warrants a restart:

```yaml
healthcheck:
  test: curl --fail http://localhost/health || exit 1
  interval: 60s
  retries: 5
  start_period: 20s
  timeout: 10s
```

**Comment by hozza** [comment]
It seems there's no "curl" or "wget" so I've gone for this - not sure it'll exit on a 400+ error though. Ideally there would be a dedicated light weight health check endpoint.

```yaml
    healthcheck:
      test: php -r "readfile('http://localhost/i/');" || exit 1
      interval: 5m
      retries: 2
      start_period: 1m
      timeout: 30s
```

**Comment by Frenzie** [comment]
That's why the one that used to be there also included `| grep -q 'jsonVars')` to make sure you weren't just seeing a server error.

**Comment by hozza** [comment]
Thanks, this is what I'll use now in the docker-compose.

```yaml
    healthcheck:
      test: php -r "readfile('http://localhost/i/');" | grep -q 'jsonVars') || exit 1
      interval: 5m
      retries: 2
      start_period: 1m
      timeout: 30s
```
