### ISSUE TITLE
[Bug] Article tags not escaped when searched

### ISSUE THREAD

**Issue by jonsmy** [FreshRSS/FreshRSS#7466]
### Describe the bug

Article tags that include search operators (i.e: `(`, `)`) are not searchable when clicking on them.

### To Reproduce

![Image](https://github.com/user-attachments/assets/bdfc218a-16f9-47af-bb4b-eb29517e7e5f)
Under an article with tags, click one with one or more search operator characters.

<br>

![Image](https://github.com/user-attachments/assets/202aa162-430e-46b8-8f6c-977513e9ccfa)
The resulting search query should return no results

<br>

![Image](https://github.com/user-attachments/assets/b576b201-758e-4057-9eec-4da35def4abd)
When the resulting search query is manually escaped, results should be properly returned.

### Expected behavior

Search queries generated as links from article tags should escape search operators.

### FreshRSS version

1.26.1

### System information

- Database version: MariaDB
- PHP version: 8.3.16
- Installation type: git
- Web server type: Nginx
- Device: n/a
- OS: Fedora Server 41
- Browser: n/a

**Comment by Alkarex** [comment]
Thanks for the bug report.
Could you please test https://github.com/FreshRSS/FreshRSS/pull/7468 ?

To test this branch, you can modify your Docker Compose like so:

```yml
  freshrss:
    image: freshrss/freshrss:7468
    build:
      context: https://github.com/Alkarex/FreshRSS.git#fix-tag-search
      dockerfile: Docker/Dockerfile-Alpine
    ...
```

* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose.yml
* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#build-custom-docker-image
