### ISSUE TITLE
[Feature] Change "favorite" icon for a spinner when processing the request

### ISSUE THREAD

**Issue by pe1uca** [FreshRSS/FreshRSS#7563]
### Is your feature request related to a problem? Please describe.

There's no feedback the action to favorite an article is being processed and makes me believe the site has frozen.  

### Use case

Not sure what part of my setup makes the action to take a bit of time, I'm guessing it's the sqlite DB being locked during updating the feeds, since I notice this issue more at the times I have the cron setup.  

It's more noticeable on feeds with small articles where I can easily use the keyboard to go "J" -> "F".  

### Describe the solution you’d like

Change the "start" icon to some kind of spinner which makes the user know the action is being processed.  

### Describe alternatives you’ve considered

Change to postgres to see if updating the feeds doesn't slow down the UI requests.  

### Additional context

This is also noticeable when going quickly through the articles with "J" and just watching the "unread" envelope not change for a bit for all the articles passed.

**Comment by Frenzie** [comment]
It's mostly the frontend waiting to send the request at all (no more often than ever x ms), though the underlying DB might also play a role depending. You can see it in the network console.

There's a giant collection at https://cssloaders.github.io/
I'm not sure if I like any of them. Maybe this one:
```css
.loader {
  width: 48px;
  height: 48px;
  display: inline-block;
  position: relative;
  color: #FFF;
  border: 1px solid;
  box-sizing: border-box;
  animation: fill 2s linear infinite alternate;
}
```
