### ISSUE TITLE
[Bug] Important feeds are marked as read when scrolling in the reader view.

### ISSUE THREAD

**Issue by a474c** [FreshRSS/FreshRSS#7601]
### Describe the bug

Using the "important feeds" feature and the "mark an article as read while scrolling (except for important feeds)" option, the reader view will still mark all important feeds as read. However, it works as expected in the normal view. https://github.com/FreshRSS/FreshRSS/pull/5782

Thanks :)

### To Reproduce
1. Turn on "Mark an article as read while scrolling (except for important feeds)"
2. Mark a feed as important.
3. Scroll down in the reader view

https://github.com/user-attachments/assets/f4813484-92c2-4764-a199-a06b1b45ca81

### Expected behavior

Important feed items should not be marked as read.

### FreshRSS version

1.26.2

### System information

- Docker version from dockerhub freshrss/freshrss:latest on Debian 12.11 / Podman

**Comment by Alkarex** [comment]
Thanks for the bug report.
Could you test https://github.com/FreshRSS/FreshRSS/pull/7602 ?

To test this branch, you can modify your Docker Compose or equivalent like so:

```yml
  freshrss:
    image: freshrss/freshrss:7602
    build:
      context: https://github.com/Alkarex/FreshRSS.git#fix-reader-important
      dockerfile: Docker/Dockerfile-Alpine
    ...
```

* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose.yml
* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#build-custom-docker-image
