### ISSUE TITLE
[Bug] Unable to delete all sharing methods – always at least one remaining

### ISSUE THREAD

**Issue by LinxHex** [FreshRSS/FreshRSS#7612]
### Describe the bug

When adding a sharing method in FreshRSS, it cannot be fully deleted. Once a sharing method is added, you must add a new one before the delete option appears for the previous one. However, no matter what, there is always at least one sharing method that cannot be removed. The system does not allow all sharing methods to be deleted, leaving one remaining permanently.

### To Reproduce

1. Go to Settings → Sharing
2. Add a new sharing method
3. Attempt to delete it – notice that delete option is not available unless you create another sharing method first
4. After creating another, delete one of the entries
5. Observe that at least one sharing method always remains and cannot be removed

### Expected behavior

Users should be able to delete all sharing methods if desired, including the last one. There should not be a requirement to always keep at least one sharing method.

### FreshRSS version

1.26.2

### System information

- Database version: sqlite 3.40.1
- PHP version: 8.2.28
- Installation type: Docker Compose
- Web server type: Nginx
- OS: Debian 12
- Browser: Chrome 136

### Additional context

https://github.com/user-attachments/assets/a12c1cbe-cea9-41b7-8a74-26320b83017d

**Comment by Alkarex** [comment]
Thanks for the bug report. Fixed in https://github.com/FreshRSS/FreshRSS/pull/7613

To test this branch, you can modify your Docker Compose or equivalent like so:

```yml
  freshrss:
    image: freshrss/freshrss:7613
    build:
      context: https://github.com/Alkarex/FreshRSS.git#fix-remove-last-share
      dockerfile: Docker/Dockerfile-Alpine
    ...
```

* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose.yml
* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#build-custom-docker-image
