### ISSUE TITLE
[Bug] Authelia OIDC no longer working

### ISSUE THREAD

**Issue by yieldhog** [FreshRSS/FreshRSS#7658]
### Describe the bug

At some point in the past several months FreshRSS OIDC login has quit working for me. I tried the above (removing :443) and neither way allows me to login. Authelia OIDC had previously been working well, no other changes on my end. Thank you

As it stands today I receive the following error: "Error: invalid_request"

Description: The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.

Hint: The 'redirect_uri' parameter does not match any of the OAuth 2.0 Client's pre-registered 'redirect_uris'.

--
My configuration is setup exactly per the documentation here: https://www.authelia.com/integration/openid-connect/freshrss/

However, I am currently on v1.26.3, something broke in the interim and removing 443 from the URL does not fix it. Authelia logs as follows:

`time="2025-06-04T18:56:04-06:00" level=info msg="Access to https://rss.mydomain.com/ (method GET) is not authorized to user , responding with status code 401" method=GET path=/api/verify path_raw=/authelia/api/verify remote_ip=174.XX.XXX.XXX

time="2025-06-04T18:56:16-06:00" level=warning msg="https://rss.mydomain.com/ requires 2FA, cannot be redirected yet" method=POST path=/api/firstfactor path_raw=/authelia/api/firstfactor remote_ip=174.XX.XXX.XXX

time="2025-06-04T18:56:17-06:00" level=error msg="Error occurred generating a WebAuthn authentication challenge for user 'myusername': error occurred starting the authentication session" error="Found no credentials for user (invalid_request)" method=GET path=/api/secondfactor/webauthn path_raw=/authelia/api/secondfactor/webauthn remote_ip=174.XX.XXX.XXX

time="2025-06-04T18:56:26-06:00" level=error msg="Authorization Request failed with error: The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. The 'redirect_uri' parameter does not match any of the OAuth 2.0 Client's pre-registered 'redirect_uris'. The 'redirect_uris' registered with OAuth 2.0 Client with id 'freshrss' did not match 'redirect_uri' value '[https://rss.mydomain.com:443/i/oidc/](https://rss.mydomain.com/i/oidc/)'." method=GET path=/api/oidc/authorization remote_ip=174.XX.XXX.XXX`

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

### FreshRSS version

1.26.3

### System information

- Database version: SQLite
- Installation type: Docker

**Comment by Alkarex** [comment]
Hello, 
Which Docker image, more precisely, on which architecture?

**Comment by yieldhog** [comment]
Hi --

I am using docker image (latest) .. this is on a Synology system, had been working up until a few versions ago.

**Comment by ipsi** [comment]
I'm just trying to set FreshRSS up and ran into the same issue. Docker image `freshrss/freshrss:edge`, pulled today (ID: `sha256:6511170ad5b0c00e8cc7f73e442dbd37b3ef2763e0c464e8423d13efc3c7ebb8`).

It looks like it's using HTTP for the redirect URL instead of HTTPS, despite the `BASE_URL` being set to `HTTPS` - so `...&redirect_uri=http%3A%2F%2Ffreshrss.example.com%2Fi%2Foidc%2F&...`, or `...&redirect_uri=http://freshrss.example.com/i/oidc/&...`

**Comment by Alkarex** [comment]
This redirection is not controlled by FreshRSS but by Authelia. Have you checked your `redirect_uris` parameter in Authelia?
(I do not have a running Authelia setup to test)

**Comment by ipsi** [comment]
AFAIK it's controlled by FreshRSS, as that needs to tell Authelia which URL to redirect to (it's possible to register more than one). It's highly unlikely it's an Authelia issue as I haven't updated it recently, and all my other OIDC configs are working expected. Also, it's Authelia that's displaying the error message. and looking at the network tab in the browser, I see the following:

* GET `https://freshrss.example.com` responds with 302 → `https://freshrss.example.com/i/?rid=684f3434e5da9`
* GET `https://freshrss.example.com/i/?rid=684f3434e5da9` responds with 302 → `https://sso.example.com/api/oidc/authorization?response_type=code&scope=openid%20profile%20groups%20email&client_id=freshrss&state=Pi-WuYmW-p53E8wAihSo4-PSPEw&redirect_uri=http%3A%2F%2Ffreshrss.example.com%2Fi%2Foidc%2F&nonce=sVviq-R1t-X2rCglT5PHL2Y2x4o2pEFd3EhzWKh6SpI`

**Comment by Alkarex** [comment]
Please show your Docker Compose or similar, focussing on the `OIDC_*` environment variables passed to Docker, in particular `OIDC_X_FORWARDED_HEADERS` (looking for `X-Forwarded-Proto`)

Cf. https://freshrss.github.io/FreshRSS/en/admins/16_OpenID-Connect.html#configuration-environment-variables

**Comment by ipsi** [comment]
```yaml
    environment:
      TZ: Europe/Berlin
      # Cron job to refresh feeds at specified minutes
      CRON_MIN: '2,12,22,32,42,52'
      # 'development' for additional logs; default is 'production'
      FRESHRSS_ENV: production
      # Optional advanced parameter controlling the internal Apache listening port
      LISTEN: 0.0.0.0:80
      # Optional parameter, remove for automatic settings, set to 0 to disable,
      # or (if you use a proxy) to a space-separated list of trusted IP ranges
      # compatible with https://httpd.apache.org/docs/current/mod/mod_remoteip.html#remoteipinternalproxy
      # This impacts which IP address is logged (X-Forwarded-For or REMOTE_ADDR).
      # This also impacts external authentication methods;
      # see https://freshrss.github.io/FreshRSS/en/admins/09_AccessControl.html
      TRUSTED_PROXY: 172.16.0.1/12 192.168.0.1/16 10.0.0.0/8
      OIDC_PROVIDER_METADATA_URL: "https://sso.example.com/.well-known/openid-configuration"
      OIDC_CLIENT_ID: 'freshrss'
      OIDC_CLIENT_SECRET: '<secret>'
      OIDC_CLIENT_CRYPTO_KEY: '<secret>'
      OIDC_SCOPES: 'openid profile groups email'
      OIDC_X_FORWARDED_HEADERS: 'Forwarded X-Forwarded-Host X-Forwarded-Port X-Forwarded-Proto'
      OIDC_SESSION_MAX_DURATION: 0
      # Optional parameter, set to 1 to enable OpenID Connect (only available in our Debian image)
      # Requires more environment variables. See https://freshrss.github.io/FreshRSS/en/admins/16_OpenID-Connect.html
      OIDC_ENABLED: 1
      # Optional auto-install parameters (the Web interface install is recommended instead):
      # ⚠️ Parameters below are only used at the very first run (so far).
      # So if changes are made (or in .env file), first delete the service and volumes.
      # ℹ️ All the --db-* parameters can be omitted if using built-in SQLite database.
      FRESHRSS_INSTALL: |-
        --api-enabled
        --base-url ${BASE_URL}
        --db-base ${DB_BASE}
        --db-host ${DB_HOST}
        --db-password ${DB_PASSWORD}
        --db-type pgsql
        --db-user ${DB_USER}
        --default-user admin
        --language en
      FRESHRSS_USER: |-
        --api-password ${ADMIN_API_PASSWORD}
        --email ${ADMIN_EMAIL}
        --language en
        --password ${ADMIN_PASSWORD}
        --user admin
```

**Comment by Alkarex** [comment]
Would you be able to try with the latest version of FreshRSS that was working for you, to confirm that this is due to a change in the FreshRSS image?
Maybe a change in [mod_auth_openidc](https://github.com/OpenIDC/mod_auth_openidc)

**Comment by ipsi** [comment]
Nope, this is my first time setting it up 😬 Though I could probably try a version from a few weeks ago, see if that does it.

**Comment by ipsi** [comment]
So I've tried it with the following versions:

* 1.23.0 - won't even start due to a change in how configuration is defined
* 1.24.0, 1.24.1 - Something (probably Apache) segfaults when I try to access FreshRSS
* 1.24.2 and later - same error as above

Note that 1.24.2 and later all share the same version of `mod_auth_oidc`, or least a file that has the same hash.

**Comment by ipsi** [comment]
I'm not sure if it's a bug, exactly, but the configuration for Apache2 OIDC sets this `OIDCRedirectURI /i/oidc/`, and given that Apache is listening on port 80, that's almost certainly going to result in an HTTP URL. Note that the examples in the docs use an explicit scheme and domain `OIDCRedirectURI https://www.example.com/protected/redirect_uri`, probably for this reason.

This can probably be worked around by allowing Authelia to redirect to the HTTP version of the URL, though it's not ideal.

**Comment by ipsi** [comment]
Ah, no, Authelia refuses to process the request when the provided redirect URL uses HTTP:

```
Authorization Response for Request with id 'd3ff40cd-fd10-423f-82bc-caff3b224644' on client with id 'freshrss' could not be created:
The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.
Redirect URL is using an insecure protocol, http is only allowed for hosts with suffix 'localhost', for example: http://myapp.localhost/.
```

The [Authelia Docs](https://www.authelia.com/integration/openid-connect/freshrss/) for FreshRSS say they were tested against `1.23.1`, which seems plausible, and they note the following:

> The [FreshRSS](https://freshrss.github.io/FreshRSS/) implementation seems to always include the port in the requested redirect_uri. As Authelia strictly conforms to the specifications this means the client registration MUST include the port for the requested redirect_uri to match.

So it looks like _something_ has changed, but it's not clear what, or when, especially since the relevant bits of `Docker/FreshRSS.Apache.conf` haven't changed since OIDC support was added.

**Comment by yieldhog** [comment]
I tend to agree here; I had it working for many months (late 2024 I believe), something changed in the interim, I can't figure out where. Suspect it has something to do with the port? I've tried with and without the port (see original post above), neither work.

**Comment by ipsi** [comment]
Welp, it's working for me now 🤔 The only thing I changed was mounting the Apache Config file, by adding this to `volumes:`

```
- ./apache.conf:/etc/apache2/sites-enabled/FreshRSS.Apache.conf
```
to enable debug logging for the OIDC module, at which point it immediately started working. Reverted the configuration back again, removed the file, nuked the volumes and the database, and it's still working fine.

I wonder if it's because I didn't have all the environment variables set up correctly, originally? I wouldn't have thought it would make a difference given the structure of the file, but it's hard to see any other possible explanation 🤔

**Comment by yieldhog** [comment]
@ipsi I tried your fix by including 

```
volumes:
  - /volume1/docker/freshrss/data:/var/www/FreshRSS/data 
  - /volume1/docker/freshrss/extensions:/var/www/FreshRSS/extensions
  - ./apache.conf:/etc/apache2/sites-enabled/FreshRSS.Apache.conf #fix for OIDC potentially
```

but when trying to build I get a bind mount error as the file doesn't exist. I am using Docker on a Synology, Swag and Authelia -- any thoughts? Thanks

**Comment by ipsi** [comment]
@yieldhog You'll want to make sure you've got the file `apache.conf` in the same directory as your `docker-compose.yml` file. You can either grab it out of the docker image (safest), or grab the one from here: https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/FreshRSS.Apache.conf and save it as `apache.conf` (bit riskier, depends how often it changes).

**Comment by yieldhog** [comment]
Thank you -- I tried it, I'm not sure if this is a step in the right direction, but I am seemingly getting forwarded but with the following error:

```
Error 403 - Forbidden
You don’t have permission to access this page [HTTP Remote-User= ; Remote IP address=172.17.0.1]

Login
```

My relevant config:

```
---
services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1026
      - PGID=1000
      - CRON_MIN=1,31
      - OIDC_ENABLED=1
      - OIDC_PROVIDER_METADATA_URL=https://auth.mydomain.com/.well-known/openid-configuration
      - OIDC_CLIENT_ID=freshrss
      - OIDC_CLIENT_SECRET=mysecretpassword
      - OIDC_CLIENT_CRYPTO_KEY=1234567890
      - OIDC_REMOTE_USER_CLAIM=preferred_username
      - OIDC_SCOPES=openid groups email profile
      - OIDC_X_FORWARDED_HEADERS=X-Forwarded-Host X-Forwarded-Port X-Forwarded-Proto
    network_mode: bridge
    volumes:
      - /volume1/docker/freshrss/data:/var/www/FreshRSS/data 
      - /volume1/docker/freshrss/extensions:/var/www/FreshRSS/extensions
    ports:
      - 9009:80
    restart: unless-stopped

```
